### ISSUE TITLE
julia-1.5.2-win64.exe republished?

### ISSUE THREAD

**Issue by tianon** [JuliaLang/www.julialang.org#1013]
Hi again! :wave: :heart:

It looks like `julia-1.5.2-win64.exe` was recently (sometime in the last ~7 hours) reuploaded with a different checksum -- was this intentional?

I can't find a reference to it anywhere -- apologies if it's already mentioned somewhere and I've missed it!

(https://github.com/docker-library/julia/commit/3d1e79c)

**Comment by DilumAluthge** [comment]
@staticfloat

**Comment by giordano** [comment]
My understanding is that a new binary with signing fixed has been uploaded: https://discourse.julialang.org/t/julia-v1-5-2-has-been-released/47181/11

**Comment by staticfloat** [comment]
Yes, that is correct! We apologize for the noise. We update the official checksum files at the same time, which is the best way to ensure that you’re getting what we intend you to receive, but we’re always happy to confirm.

**Comment by tianon** [comment]
Rock on, thanks for confirming! 👍
