### ISSUE TITLE
Make the headings on the community page links 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1017]
I want to be able to link to specific headings on the community page. We should add this in.

**Comment by ViralBShah** [comment]
Can do it the same way as: https://julialang.org/downloads/platform/#linux_and_freebsd

**Comment by PseudoCodeNerd** [comment]
Hey!
This issue still persists and I can work on it. Can I get assigned?
Thanks

**Comment by logankilpatrick** [comment]
Sure, feel free to tackle this. I can assign later tonight.
