### ISSUE TITLE
Make the community calendar show each users local time zone

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1018]
Right now the calendar shows the time defaulted to UTC, we should have it display the local time zone of each user visiting the site.

**Comment by devil-cyber** [comment]
Can i work on this

**Comment by logankilpatrick** [comment]
Sure!

**Comment by devil-cyber** [comment]
thanks

**Comment by devil-cyber** [comment]
I am working on this issue

**Comment by devil-cyber** [comment]
@logankilpatrick can you please prove me some insight on how to start after cloning the repo

**Comment by logankilpatrick** [comment]
You can open it in an IDE and then do `using Franklin; serve()` to get the site running locally. Then you need to figure out how to make this work in the time zones.

**Comment by devil-cyber** [comment]
thanks already done Julia and franklin had a great documentation

**Comment by tlienart** [comment]
as explained in PR #1024 I don't think Franklin can help here, it needs to be resolved at visit time, something like http://www.onlineaspect.com/2007/06/08/auto-detect-a-time-zone-with-javascript/

**Comment by devil-cyber** [comment]
Can we used javascript to fetch timezone from client browser

**Comment by tlienart** [comment]
> Can we used javascript to fetch timezone from client browser
> […](#)

did you check out the two links?

**Comment by devil-cyber** [comment]
Yes i checked that

**Comment by tlienart** [comment]
I'm a bit unclear on whether you still have a question or not. Assuming you do and your initial question was "how do you add javascript to a page" then you just add something like this on a markdown file

```
~~~
<script> ... </script>
~~~
```

or something like this in the `layout/head.html` 

```
{{ispage path/to/relevant/page}}
<script> ... </script>
{{end}}
```

**Comment by devil-cyber** [comment]
Ok
