### ISSUE TITLE
Turn on fastly gzip compresison for asciinema casts

### ISSUE THREAD

**Issue by Keno** [JuliaLang/www.julialang.org#1026]
They end in `.cast`, which is not on our fastly gzip whitelist. I don't see any reason not to serve them compressed, so I'm gonna turn it on, unless @staticfloat thinks its a bad idea for whatever reason.

**Comment by staticfloat** [comment]
Seems fine to me.

**Comment by Keno** [comment]
Added `.cast` to the gzip extensions, as well as the `application/x-asciicast` mime type and activated as Version 20 on fastly.
