### ISSUE TITLE
Use AMP for blog pages

### ISSUE THREAD

**Issue by Keno** [JuliaLang/www.julialang.org#1027]
Our blog pages are simple enough that it seems like it should be trivial enough to AMP-ify them, which would make them eligible to appear in the top carousel of search results.

**Comment by ViralBShah** [comment]
@tlienart Should we have a franklin label for improvements to Franklin?

**Comment by tlienart** [comment]
But... isn't AMP evil? 🙀 

Jokes aside, @ViralBShah yes a label sounds good, and I can link to relevant issues. Re AMP-ifying, I don't know what's involved, at what stage (pre or post build) or how easy this is so I need to do some research.

**Comment by ViralBShah** [comment]
:-)

Added a few `franklin` labels, but may not be always correct.

**Comment by tlienart** [comment]
So from a short amount of research it looks really easy to do, it's mostly a templating thing where you add specific stuff on the pages so that Google can cache them more easily (https://amp.dev/documentation/guides-and-tutorials/start/create/basic_markup/?referrer=ampproject.org) I'll try to give that a shot soon for blog pages.

**Comment by garrison** [comment]
> AMP-ify them, which would make them eligible to appear in the top carousel of search results

AMP is no longer necessary to achieve the carousel, and there may no longer be any benefit to using AMP.  From a recent [Google update](https://developers.google.com/search/blog/2021/04/more-details-page-experience#details):

> This means that using the AMP format is no longer required and that any page, irrespective of its Core Web Vitals score or page experience status, will be eligible to appear in the Top Stories carousel.

I first learned about this from a (highly editorialized) [post on the Plausible blog](https://plausible.io/blog/google-amp).

**Comment by ViralBShah** [comment]
Great!
