### ISSUE TITLE
The best installation instruction is missing :P

### ISSUE THREAD

**Issue by PeterNorlindh** [JuliaLang/www.julialang.org#1047]
I've been struggling to install Julia properly on Linux. This almost kept me from adopting Julia at all, and has made me reluctant to upgrade to new releases. Until I came across this suggestion in a forum post: 

sudo ln -s home/user/path/to/julia/bin/julia /usr/bin/julia

Adding the path to /usr/bin was really easy and works like a charm. I can't seem to find this among the alternatives mentioned on [Platfom Specific Instructions](https://julialang.org/downloads/platform/). Please add it, I'm sure it would make life easier for a bunch of beginners like myself.

Thanks :)

**Comment by logankilpatrick** [comment]
Feel free to open a PR with this updated info and include some screenshots of the behavior working in the PR if possible.

**Comment by ViralBShah** [comment]
It is generally not recommended to link binaries in `/usr/bin/julia`. The common thing is `/usr/local/bin` but it is not guaranteed that all linux users have /usr/local/bin in their PATH.

**Comment by timholy** [comment]
Your best answer is to add `/home/user/path/to/julia/bin` to your personal `PATH` environment variable, and that's already documented. Did it not work for you? Did you forget the leading `/`? (You did in your OP.)

**Comment by apparluk** [comment]
> reluctant to upgrade

I've upgraded three times in the last year.

I repackage for my Linux distribution the precompiled download.

But if `/opt` is not otherwise being used one could manually install like this.

For 64-bit substitute julia-1.5.2-linux-x86_64.tar.gz in the following.

```
bash-4.3# cd /tmp
bash-4.3# tar xf julia-1.5.2-linux-i686.tar.gz && cd julia-1.5.2
bash-4.3# chown -R root:root .
bash-4.3# find -L . \
>  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
>  -o -perm 511 \) -exec chmod 755 {} \; -o \
>  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
>  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
bash-4.3# cp -r bin /opt/bin
bash-4.3# cp -r etc /opt/etc
bash-4.3# cp -r include /opt/include
bash-4.3# cp -r lib /opt/lib
bash-4.3# cp -r libexec /opt/libexec
bash-4.3# mkdir /opt/share && cp -r share/{doc,julia} /opt/share
bash-4.3# cp -r share/man /opt/man
bash-4.3# 
```

Then for `/etc/profile.d` create an executable that is read on startup.

```
bash-4.3# cat julialang.sh
#!/bin/sh
export MANPATH="$MANPATH:/opt/man"
export PATH="${PATH}:/opt/bin"
bash-4.3# chown root:root julialang.sh
bash-4.3# chmod 755 julialang.sh
bash-4.3# mv julialang.sh /etc/profile.d/
bash-4.3# 
```

To uninstall julia-1.5.2 run the following.

```
bash-4.3# rm -rf /opt/{bin,etc,include,lib,libexec,man,share}
bash-4.3# 
```

The same `/etc/profile.d/julialang.sh` can be used for an upgrade.

NB: I presume `/opt/libexec/7z` can be found by `julia`.

**Comment by apparluk** [comment]
> can't seem to find this among the alternatives mentioned

your `ln` command creates link in `/usr/bin` to a file with other perms than are used in `/usr/bin`

**Comment by ViralBShah** [comment]
I should also point out that many people do not upgrade Julia, but install new versions of Julia to co-exist with older ones.

**Comment by apparluk** [comment]
One can also `source` a file to load variables; `.` is a bash shorthand for the `source` builtin.

```
bash-4.3$ echo $LD_LIBRARY_PATH

bash-4.3$ cat ~/pgplot
PGPLOT_DIR="/usr/local/pgplot/"; export PGPLOT_DIR
LD_LIBRARY_PATH="/usr/local/pgplot/"; export LD_LIBRARY_PATH
bash-4.3$ ls -l pgplot
-rw-r--r-- 1 eric eric 112 Oct 26 06:37 pgplot
bash-4.3$ . ~/pgplot
bash-4.3$ echo $LD_LIBRARY_PATH
/usr/local/pgplot/
bash-4.3$ 
```

**Comment by apparluk** [comment]
@ViralBShah 

This would be more concise and less verbose.

[Linux and FreeBSD
](https://julialang.org/downloads/platform/#linux_and_freebsd)
The following downloads and installs the latest Linux x86_64 version of Julia.

```
sudo wget https://julialang-s3.julialang.org/bin/linux/x64/{{stable_release_short}}/julia-{{ stable_release }}-linux-x86_64.tar.gz
sudo tar zxvf julia-{{ stable_release }}-linux-x86_64.tar.gz -C /usr/local
sudo ln -sf /usr/local/julia*/bin/julia /usr/local/bin/julia
```
The `ln`command can be substituted with setting `$PATH` in shell customization files or sourced from a flat file.

The above installs all files in a single tree, the symlink notwithstanding.

To uninstall `sudo rm -rf /usr/local/julia* && rm -f /usr/local/bin/julia`. 

To remove user installed packages `rm -rf ~/.julia/{compiled,environment,logs,packages}`.

**Comment by ViralBShah** [comment]
You can also use the `jill` scripts that folks are maintaining for this. I think we list them somewhere on the platforms pages.

**Comment by PeterNorlindh** [comment]
Thanks for your feedback :) I have no strong opinions on the matter, and frankly know almost nothing about it. But I think I'll stick to the suggestion I found in that forum post until I run into issues with it :)
