### ISSUE TITLE
Add Julia teaching activities at University

### ISSUE THREAD

**Issue by LUISSMR** [JuliaLang/www.julialang.org#1048]
Hi, I would like to add Julia teaching activities at Academia Politécnica Militar (Chile) based on two courses:
- System Engineering Design (Spring 2020)
- Operational Research (Fall 2020)

Both taugh by Prof. Luis San Martín.

Best wishes

**Comment by logankilpatrick** [comment]
Hey! Thanks for including this info. Please make a PR to the respective file for this with the required info so we can get these courses added. Thanks!
