### ISSUE TITLE
Add Yao.jl to quantum computing/change to quantum physics

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/www.julialang.org#105]
I see the scientific domain mentioned quantum computing, but... however, I guess [Yao.jl](https://github.com/QuantumBFS/Yao.jl) is the only Julia package that is able to simulate/run an arbitrary quantum circuit at the moment (It was designed to do this job). Another library [BBN-Q/Cliffords.jl](https://github.com/BBN-Q/Cliffords.jl) is also for quantum computing.

[QuantumOptics](https://qojulia.org) like is described as it is, is for open quantum systems. I was wondering if your guys want to add it to quantum computing with [QuantumOptics](https://qojulia.org) or just change **quantum computing** to **quantum physics** or something, cause this is quite misleading... In python community, they have [OpenFermion](https://github.com/quantumlib/OpenFermion), [ProjectQ](https://github.com/ProjectQ-Framework/ProjectQ) which will use quantum circuit for quantum algorithms, if you want to mention quantum computing.

**Comment by ChrisRackauckas** [comment]
I second changing quantum computing to quantum physics. It was just a mistake. QuantumOptics.jl fits in with the theme of the other packages there which are about mathematical modeling and simulation, and so it works there as a popular package in the scientific computing domain which represents quantum physics work in Julia.

**Comment by Roger-luo** [comment]
Okay, if you just mention for quantum physics, it will be more accurate. Narrowly speaking, packages like ProjectQ, openqasm,etc. is for quantum computing, and packages like QuTiP (which should be QuantumOptics.jl in Julia) is for quantum information or quantum science. 

Although quantum computing is partly related to quantum physics, but it also related to computer science too. Saying QuantumOptics.jl is about quantum computing is not 100% wrong, but just quantum physics will be better.
