### ISSUE TITLE
Links in the diversity section goes to empty pages or nowhere

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/www.julialang.org#1070]
The links here https://julialang.org/diversity/current/ leads to empty pages.

In https://julialang.org/diversity/ideas/, the link to ASL interpretation goes nowhere.

Perhaps they should just be listed and not have links until there is any content for them.

**Comment by logankilpatrick** [comment]
Was hoping folks would have had the chance to update the details for their projects by now but if these don't get updated soon, we can revert to just a list.

**Comment by ViralBShah** [comment]
We should not set up empty links with the hope that someone will populate them. Since people get busy and such, it is usually better to get the content ready and up first, and then set up a link.

**Comment by logankilpatrick** [comment]
That's fair, will update them to a normal list this weekend.
