### ISSUE TITLE
Legal page

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/www.julialang.org#1073]
[This page](https://julialang.org/legal/) should probably have some kind of legal statement. Otherwise the page should be deleted and removed from the footer table.

**Comment by ViralBShah** [comment]
It should be deleted from the footer.

**Comment by logankilpatrick** [comment]
Aren't we required to have some sort of privacy policy list here? We are using Google Analytics which collects cookies I assume

**Comment by ViralBShah** [comment]
Sure. Somebody needs to get a draft going. Maybe the quickest thing is to check with NF if they have something we can use to start from? But let's not link a 404 legal page until we have the privacy policy up.

**Comment by logankilpatrick** [comment]
@StefanKarpinski @ViralBShah we have this: https://github.com/JuliaLang/www.julialang.org/blob/main/privacy.md can we delete the legal page?

**Comment by ViralBShah** [comment]
Yes, let's do that.

**Comment by StefanKarpinski** [comment]
Sure.
