### ISSUE TITLE
Try Julia repl does not load reliably

### ISSUE THREAD

**Issue by DhairyaLGandhi** [JuliaLang/www.julialang.org#1086]
https://julialang.org/learning/tryjulia/ has a fairly old (at this time!) version of Julia (1.3.1). Can that be updated?

**Comment by logankilpatrick** [comment]
I had had a PR open for this for months. https://Repl.it went into performance/stability mode and stopped merging PR's for things like language updates for the time being.

**Comment by logankilpatrick** [comment]
See here: https://github.com/replit/polygott/pull/89

**Comment by logankilpatrick** [comment]
New PR: https://github.com/replit/polygott/pull/222

Julia 1.4.3 should be available soon and 1.5.3 shortly thereafter.

**Comment by ViralBShah** [comment]
Should we remove reply.it?

**Comment by DhairyaLGandhi** [comment]
I would think so. Or at least link to places like a live Pluto app on juliahub or perhaps nextjournal?

**Comment by DilumAluthge** [comment]
I would prefer that instead of removing repl.it, we get https://github.com/replit/polygott/pull/222 merged, and then upgrade to 1.6.2.

**Comment by logankilpatrick** [comment]
> Regarding updating Julia, we are trying to converge with Nix's channel system. They have a stable Nix release every 6 months which can still be updated but all new updates must be backwards compatible. So if Julia has a new version that is backwards compatible, it can be updated in the latest stable Nix channel (If I understand correctly). Our Nix cache currently supports Nix stable 21.11 and unstable and those caches will be updated periodically (ideally weekly). The best way to get Julia updated is to get it backported on the latest stable release of Nix (assuming backwards compatibility).

> If there are backwards incompatible changes made to Julia, it can be updated in the unstable Nix branch, but ideally our base templates always use a stable Nix channel to mitigate repls breaking. We will support all future Nix stable channels, which means you may have to wait up to 6 months to update the base Julia template if there are breaking changes.

@DilumAluthge from the folks at Replit

**Comment by DilumAluthge** [comment]
I know very little about Nix, so we may need to bring in some other people to help with this.

Are they saying that they will only use Julia if there is a Nix package for Julia?

How does Nix currently distribute Julia? Do they distribute the official binaries from the Julia website? Or do they build it themselves? If Nix builds Julia themselves, and if Repl.it only uses the Nix Julia, I'd be reluctant to keep Repl.it on the Julia website.

**Comment by logankilpatrick** [comment]
I just pinged in the nix channel on Slack to see if we can get some more nix experts.

**Comment by ViralBShah** [comment]
Can't we just provide a shell script to users to download and install Julia on login? Maybe just juliaup. Seems like a much easier solution. 

Building something special here means either is committing to do it forever or for having older versions when we can't keep up.

Maybe replit staff can package Julia as part of their distribution?

**Comment by rikhuijzer** [comment]
> How does Nix currently distribute Julia? Do they distribute the official binaries from the Julia website? Or do they build it themselves?

See https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/julia: 1.6 and 1.7 are based on the official binaries. Note that only 1.6 is on the stable channel (https://github.com/NixOS/nixpkgs/tree/21.11/pkgs/development/compilers/julia).

> Maybe replit staff can package Julia as part of their distribution?

They say that they don't want that, right? They use Nix because "This should make getting the latest version of Julia much, much easier." (https://github.com/replit/polygott/pull/222#issuecomment-848818738). In theory, I agree. But since they stick to "We will support all future Nix stable channels, which means you may have to wait up to 6 months to update the base Julia template if there are breaking changes." they contradict themselves. The system is so "easy" that it is always about 6 months behind.

**Comment by ninjin** [comment]
I authored and maintain the non-source Nix packages: `julia-lts-bin` and `julia-stable-bin` (currently pointing to `julia_17-bin` and `julia_16-bin`) on Nixpkgs `master` (which then feeds into the `unstable` channel). If Repl.it wants to follow `stable` for *everything*, they are more than welcome to backport non-breaking changes to `stable`. It is not hard work, but takes cherry picking commits, submitting a PR, and ensuring that someone with commit rights is convinced that you are indeed not breaking `stable` and that the update is warranted. Alternatively, it is not like it is difficult to mix channels with Nix/NixOS (I have my base system on `stable`, but lift in specific packages like Julia from `unstable` and of course have a handful of packages that I maintain privately as I do not want to commit to maintaining everything I use upstream). This is where Nix absolutely shines, so I am not sure why Repl.it would not go down this route for a language that moves significantly faster than say Python.

It literally is as simple as adding this to your configuration:

    config.packageOverrides = pkgs: {
        # Run when installing a new system:
        #
        #   nix-channel --add https://nixos.org/channels/nixos-unstable nixos-unstable
        #   nix-channel --update
        unstable = import <nixos-unstable> { config = config.nixpkgs.config; };
    }

Then you can just replace `julia-bin-stable` with `unstable.julia-bin-stable` wherever you mention it and you will follow `unstable` for that package *only* and the rest of your system will still be on `stable`. I think this only applies for your global configuration though, if you want it to seep all the way down into your `shell.nix` files and the likes you probably need to refer to the manual (do tell me if do as I would me curious exactly how this interoperates).

**Comment by adkabo** [comment]
@logankilpatrick 
>> So if Julia has a new version that is backwards compatible, it can be updated in the latest stable Nix channel (If I understand correctly).

On Nix stable channels, normally [only package bugfixes and security fixes](https://discourse.nixos.org/t/what-is-the-package-version-update-policy-for-stable-channels/11260/3) are applied between semiannual major releases -- upgrading from 1.6 to 1.7 would likely be too much. If Replit also provides an option to access Nixpkgs unstable, new versions would be available on a rolling basis.

**Comment by ViralBShah** [comment]
When I go here, nothing loads: https://julialang.org/learning/tryjulia/

@logankilpatrick is this supposed to give us a working Julia repl?

**Comment by logankilpatrick** [comment]
If you use chrome incognito, then it stops working, else, it works as expected with Julia 1.6.3 right now.

**Comment by ViralBShah** [comment]
Not working for me - incognito or otherwise. I do have an adblocker.

**Comment by ViralBShah** [comment]
Closing since it is indeed the latest LTS now.

**Comment by DilumAluthge** [comment]
It would be unfortunate if people had to disable their adblocker. And I'm not too keen on having a message that says "please disable your adblocker".

Instead, how about a link that opens the repl.it website in a new tab? And then we can have a message that says "if you see a blank page, please click here to open the REPL in a new tab"?

**Comment by DilumAluthge** [comment]
Reopening to discuss the issue of a graceful message for users with adblocker.

**Comment by ViralBShah** [comment]
Disabling my adblocker also didn't help.

**Comment by DilumAluthge** [comment]
I guess the question is: is the issue with repl.it itself, or is there a problem with the way that we embed repl.it into the Julia website?

What happens if you open a new tab and go directly to: https://replit.com/@logankilpatrick/TryJuliaToday

**Comment by DilumAluthge** [comment]
@logankilpatrick On a separate note, the repl.it is giving me 1.6.3. Can we upgrade to 1.6.5?

**Comment by rikhuijzer** [comment]
> @logankilpatrick On a separate note, the repl.it is giving me 1.6.3. Can we upgrade to 1.6.5?

They said they use the Nix stable channel which only updated every 6 months. It is currently at Julia 1.6.3 (https://github.com/NixOS/nixpkgs/blob/21.11/pkgs/development/compilers/julia/1.6-bin.nix). If they would use the unstable channel, then they could have been running 1.7.2 since 2 days after the release (https://github.com/NixOS/nixpkgs/pull/158553).

**Comment by ViralBShah** [comment]
> What happens if you open a new tab and go directly to: https://replit.com/@logankilpatrick/TryJuliaToday

This works for me.

**Comment by DilumAluthge** [comment]
How does this look? https://github.com/JuliaLang/www.julialang.org/pull/1587
