### ISSUE TITLE
Google search console feedback

### ISSUE THREAD

**Issue by tlienart** [JuliaLang/www.julialang.org#1107]
Posting here the content of an email from Google search console (I didn't investigate further)

cc @ViralBShah @logankilpatrick 

```
Coverage issues detected on https://julialang.org/

To the owner of https://julialang.org/:

Search Console has identified that your site is affected by 1 Coverage issues:

Top Errors

Errors can prevent your page or feature from appearing in Search results.
The following errors were found on your site:

Submitted URL not found (404)

We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.
```

also another email came with this which seems quite nice:

<img width="460" alt="Screen Shot 2020-12-08 at 15 05 59" src="https://user-images.githubusercontent.com/10897531/101500938-08623280-3967-11eb-9c2c-9cffd087348f.png">

**Comment by tlienart** [comment]
from a quick look it seems that the  sitemap contains at least one link to a page that doesn't exist anymore, it would be  nice to figure out which link fails and then I can try seeing why Franklin included  it in there.

**Comment by ViralBShah** [comment]
That's great!

The search console shows these as errors, which all are 404s:

https://julialang.org/soc/index/
Dec 1, 2020
https://julialang.org/index/
Nov 28, 2020
https://julialang.org/blog/2017/12/ml%26pl-zh_tw/
Nov 28, 2020

**Comment by tlienart** [comment]
Nice thanks for looking this up! I'll investigate and fix this in Franklin

**Comment by ViralBShah** [comment]
I think they are redirects, but not happening in a way that google likes? Or perhaps they should not be in the sitemap?
