### ISSUE TITLE
FYI: site is down with "service unavailable" status code

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/www.julialang.org#1118]
> Error 503 No healthy IP available for the backend
> 
> No healthy IP available for the backend
> Guru Mediation:
> 
> Details: cache-lon4265-LON 1610465981 2324510307
> 
> Varnish cache server

a) Most important to fix.

b) I know what Varnish, cache etc. is, but also consider more user friendly error pages, as some might find the message "healthy IP" odd.

**Comment by logankilpatrick** [comment]
Should be back up, I think this was an issue with our hosting provider.
