### ISSUE TITLE
Status page loads too slowly

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1123]
This link: https://status.julialang.org/ loads extremely slow. Anything we can do to improve the performance? More money I assume?

**Comment by DilumAluthge** [comment]
@staticfloat @fredrikekre

**Comment by fredrikekre** [comment]
Replaced statping with https://github.com/fredrikekre/StatusPage.jl

**Comment by logankilpatrick** [comment]
Works like a charm now, thank you @fredrikekre !
