### ISSUE TITLE
Update Turing JSoC Projects

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1138]
Hey @yebai @cpfiffer @trappmartin @willtebbutt @mohamed82008 @xukai92 we need to get the Turing projects here: 
https://julialang.org/jsoc/gsoc/turing/ updated for GSoC 2021 asap. 

There are new requirements for the projects found here: https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list including adding an (easy, medium, hard) rating for each project. Please read through that link and updated the projects as needed.

**Comment by cpfiffer** [comment]
Can do, we're drafting up a list internally. Will update here when it's good.

**Comment by logankilpatrick** [comment]
Thank you!
