### ISSUE TITLE
Update ML GSoC Projects 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1139]
Hey @maleadt @MikeInnes @DhairyaLGandhi @avik-pal @aviks @findmyway @staticfloat @ChrisRackauckas we need to get the ML projects here:
https://julialang.org/jsoc/gsoc/flux/ updated for GSoC 2021 asap.

There are new requirements for the projects found here: https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list including adding an (easy, medium, hard) rating for each project. Please read through that link and updated the projects as needed.

If you are no long able to mentor the project or the project has been completed, please open a PR to remove it. Thanks all!

**Comment by aviks** [comment]
@DhairyaLGandhi maybe we should remove the model-zoo examples project?

**Comment by avik-pal** [comment]
For the 3D Deep Learning Project: I think we can remove it as a single project. Most of the work was completed by Nirmal during the last GSoC. Some of them are left but would be better if integrated with some of / broken off into the other projects:

1. Differentiable Rendering **[HARD]**: We kind of decided that it is best not to integrate it in Flux3D. Rather any of the differentiable renderers developed can use the primitives provided by Flux3D.
    * **Expected Outcome:** SoftRasterizer/DiB-R based works. We already have RayTracer.jl which is motivated by OpenDR. (Of course, if someone wants to implement NERF - like models they are most welcome to submit a proposal). We would ideally target at least 2 of these models.
    * **Skills:** GPU Programming, Deep Learning, (deep) familiarity with the literature, familiarity with defining (a lot of) Custom Adjoints

2. Core Development **[MEDIUM]**:
    * **Expected Outcome:**
         * Some of the functions require custom adjoints for speedup
         * Functions require GPU kernels. Some of these are of common interest to the community like -- knn, etc.
         * Move DataLoaders and similar functions out of Flux3D and use DataLoaders.jl and similar utilities for these functions
         * Benchmarking with Tensorflow Graphics and Pytorch3D. We already have the scripts for kaolin, need to extend that.
         * Most of these problems are listed as issues in the main repo.
    * **Skills:** GPU Programming, Deep Learning, familiarity with defining (a lot of) Custom Adjoints

3. Usable Models **[EASY]**: Examples and Pretrained Models following the likes of the refactor of Metalhead.jl. Some examples -- PointFlow, 3D Object Detection Models, 3D Reconstruction Models, etc. This a pretty open-ended project so proposals involving other standard 3D vision models would be considered.

**NOTE**: I might be unavailable for some of the months in summer 2021. So we should go forward with these only if Nirmal/Dhairya are able to mentor.

cc @DhairyaLGandhi, @nirmal-suthar

P.S. I will open a PR if everyone is fine with these points

**Comment by DhairyaLGandhi** [comment]
@aviks, I'd removed a couple of model zoo related ones from the flux website just today

**Comment by DhairyaLGandhi** [comment]
I think that's a good idea. I was also hoping to propose writing benchmarks for Flux in deep learning and dP cases, developing a kornia equivalent which would need to interface adjoints with the Images API, and also push work on FastAI.jl as well.

**Comment by DhairyaLGandhi** [comment]
cc @darsnack

**Comment by darsnack** [comment]
Thanks will try to get a description like @avik-pal up this weekend for FastAI.jl that we can fine-tune.

**Comment by logankilpatrick** [comment]
@avik-pal not sure if your proposed projects made it in but feel free to do a PR.
