### ISSUE TITLE
Updated Scientific GSoC Projects

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1146]
Hey @schillic we need to get the compiler projects here: https://julialang.org/jsoc/gsoc/science/ updated for GSoC 2021 asap.

There are new requirements for the projects found here: https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list including adding an (easy, medium, hard) rating for each project. Please read through that link and updated the projects as needed.

If you are no long able to mentor the project or the project has been completed, please open a PR to remove it. Thank you!

**Comment by schillic** [comment]
CC @mforets
