### ISSUE TITLE
Update Tooling GSoC Projects

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1147]
Hey @pfitzseb @Keno @davidanthoff @shashi @JobJob @barche we need to get the tooling projects here: https://julialang.org/jsoc/gsoc/tooling/#tooling_projects_summer_of_code updated for GSoC 2021 asap.

There are new requirements for the projects found here: https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list including adding an (easy, medium, hard) rating for each project. Please read through that link and updated the projects as needed.

If you are no long able to mentor the project or the project has been completed, please open a PR to remove it. Thanks all!

**Comment by aviks** [comment]
We should probably remove all the Juno projects, at the very least
