### ISSUE TITLE
Updated Graphic GSoC Projects

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1151]
Hey @SimonDanisch @barche @davidanthoff  we need to get the graphics projects here: https://julialang.org/jsoc/gsoc/graphics/ updated for GSoC 2021 asap.

There are new requirements for the projects found here: https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list including adding an (easy, medium, hard) rating for each project. Please read through that link and updated the projects as needed.

If you are no long able to mentor the project or the project has been completed, please open a PR to remove it. Thanks all!

**Comment by logankilpatrick** [comment]
@SimonDanisch @barche @davidanthoff commenting out the projects for now, if they are still of interest, please open a PR to update them.

**Comment by SimonDanisch** [comment]
Thanks! Sorry, I wanted to crowd source this but didn't get anyone to help and then forgot about it ;)

**Comment by logankilpatrick** [comment]
Feel free to re-add the projects if you get a chance and have bandwidth
