### ISSUE TITLE
Update Tabular Data GSoC Projects

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1153]
Hey @shashi @tanmaykm @MikeInnes @davidanthoff we need to get the Tabular Data projects here: https://julialang.org/jsoc/gsoc/tables/ updated for GSoC 2021 asap.

There are new requirements for the projects found here: https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list including adding an (easy, medium, hard) rating for each project. Please read through that link and updated the projects as needed.

If you are no long able to mentor the project or the project has been completed, please open a PR to remove it. Thanks all!

**Comment by aviks** [comment]
@shashi @tanmaykm shall we remove the JuliaDB projects?

**Comment by tanmaykm** [comment]
I was thinking it may be good to retain the Parquet.jl entry but re-word it, maybe focussing on tables/arrow integration for large/out-of-core data, performance, supporting missing encodings...
Would that be useful?

**Comment by aviks** [comment]
Yeah, sounds good. Can you do a PR ?

**Comment by tanmaykm** [comment]
Sure, done in #1168

**Comment by logankilpatrick** [comment]
Thanks all!
