### ISSUE TITLE
Updated DeepChem.jl GSoC Project

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1155]
Hey @rkurchin we need to get the DeepChem project here: https://julialang.org/jsoc/gsoc/deepchem/ updated for GSoC 2021 asap.

There are new requirements for the projects found here: https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list including adding an (easy, medium, hard) rating for each project. Please read through that link and updated the projects as needed.

If you are no long able to mentor the project or the project has been completed, please open a PR to remove it. Thank you!

**Comment by rkurchin** [comment]
Happy to update things if needed, though @aviks is right that I only posted this a couple months ago. Are there any guidelines for what constitutes easy/medium/hard?

**Comment by logankilpatrick** [comment]
Hey @rkurchin, just adding a project difficulty would be ideal (easy, medium, hard).

**Comment by logankilpatrick** [comment]
Closing this for now though, thanks again for helping out!
