### ISSUE TITLE
New classroom with Julia at Polytech Nice Sophia

### ISSUE THREAD

**Issue by jbcaillau** [JuliaLang/www.julialang.org#1179]
Can you please add the following entry to the list of classes using Julia?
—

[Polytech Nice Sophia](http://polytech-nice-sophia.fr)
- [Mathematics for the engineer](https://gitlab.polytech.unice.fr/MAM/mi2) (Prof. J.-B. Caillau), spring 2020

**Comment by logankilpatrick** [comment]
Hey! Feel free to add a PR with the details.

**Comment by jbcaillau** [comment]
Done, just need a few minutes to write it down :-)

**Comment by logankilpatrick** [comment]
Awesome, added it in. Thanks for opening this issue!

**Comment by jbcaillau** [comment]
Thanks for the great job: Julia rocks.
