### ISSUE TITLE
Add mentor slack channel and jsoc admins

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1194]
Add to the jsoc section.

**Comment by Bhavik-Ardeshna** [comment]
Hey! @logankilpatrick  I want to work on this issue
Plz assign to me

**Comment by logankilpatrick** [comment]
This was a reminder for myself, thank you for the offer to help!

**Comment by Bhavik-Ardeshna** [comment]
@logankilpatrick Hey I want to contribute to Julia can u suggest which project should i start

**Comment by logankilpatrick** [comment]
@Bhavik-Ardeshna please [ping me on Slack](https://julialang.org/slack/) if you want help getting started, happy to provide suggestions.
