### ISSUE TITLE
JuliaCon 2020 section on the landing page does not actually load a random video

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#1221]
It just shows the first video from the playlist every time. Perhaps youtube changed something?

@logankilpatrick

**Comment by ViralBShah** [comment]
It could also helped improve Pluto's popularity. :-)

**Comment by logankilpatrick** [comment]
It seems something on the backend changed for YouTube since that code was not touched. My initial searches/test yielded no results. Will follow up on this.

**Comment by ViralBShah** [comment]
Yeah when we did it, I had checked that it did work.

**Comment by ViralBShah** [comment]
@logankilpatrick or perhaps someone else - can we get this fixed?

**Comment by abhishalya** [comment]
I'll have a look at this once.
