### ISSUE TITLE
Add images on the JSoC Section

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1233]
TODO: Add images to the JSoC section for each program. Will help the eyes when viewing a wall of text.

**Comment by logankilpatrick** [comment]
Done but need to figure out how to make them the same size (might just need to edit the raw images).

**Comment by StarTrooper08** [comment]
Hello , can I assist you in this @logankilpatrick .

**Comment by StarTrooper08** [comment]
Can we optimize the images??
 So that it would load quick??
