### ISSUE TITLE
What does it mean to be a contributor and how many does the Julia ecosystem have

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1253]
One important metric we should be tracking and sharing is contributors to the language and ecosystem. This is really really hard to do. We can obviously go for the low hanging fruit via GitHub and look at who committed to a repo but that often time isn't enough. 

A few possible metrics that would be cool to track: 
- The number of people who contributed to all of the registered Julia packages per month (including issues and PR's)
    - The number of new folks who contributed to those packages 
- See way of tracking non code contributions

On the question of what it means to be a contributor, this will hopefully be taken care of by our 2021 GSoD proposal. This whole discussion was inspired by the NumFocus project survey where I had to say how many "contributors" Julia had which was quite a difficult question to answer. 

This could be a cool JuliaHub feature too I suppose @ViralBShah @aviks

**Comment by giordano** [comment]
I have the answers for these questions, wait for JuliaCon 🙂

**Comment by ViralBShah** [comment]
So long as the contribution goes to a repo (julia or package), it can be automatically counted.
