### ISSUE TITLE
repl.it refuse to connect

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/www.julialang.org#1257]
after I login using Google, I got this somehow

![image](https://user-images.githubusercontent.com/8445510/113542640-b2b73300-95b2-11eb-8c49-82b36cd0af56.png)

**Comment by logankilpatrick** [comment]
Are you allowing JS in your browser?

**Comment by Roger-luo** [comment]
I think so. I can use replit directly

**Comment by logankilpatrick** [comment]
If others continue to have this issue, we can re-open and talk with the repl.it folks.
