### ISSUE TITLE
Julia for Teaching: A World Map

### ISSUE THREAD

**Issue by crstnbr** [JuliaLang/www.julialang.org#128]
This is to revive this issue https://github.com/JuliaLang/www_old.julialang.org/issues/764. I think it would be cool to have the map on the new website. I will try to get a PR ready during Hackathon today.

https://github.com/crstnbr/juliamap

**Comment by ViralBShah** [comment]
Do submit if you have something we can publish. Even if just a static image.

**Comment by ViralBShah** [comment]
Done in #2468
