### ISSUE TITLE
Document the use of `juliaup` to have multiple Julia versions and keep Julia updated

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1293]
If someone wants `Julia` to point to a specific version but perhaps `julia2` to point to some other version, we should maybe give those steps? It might not be as relevant now but with forthcoming releases it may be important.

**Comment by ViralBShah** [comment]
`juliaup` will provide a standard way to do all this. Once it is announced at JuliaCon, we should include a mention on the downloads page. 

https://github.com/JuliaLang/juliaup
