### ISSUE TITLE
Adding classes to https://julialang.org/learning/classes/

### ISSUE THREAD

**Issue by sevaux** [JuliaLang/www.julialang.org#1299]
Hi all,

I would like to add the following classes where julia is heavily used at Université Bretagne Sud. I hope this is the right place to ask.

* Université Bretagne Sud
    * ANR2201 - Result Analysis (Prof. Marc Sevaux), since 2018
    * INOE301 - Scheduling (Dr. Alexandru Olteanu), since 2018
    * MAOE501 - Advanced Scheduling (Dr. Alexandru Olteanu), since 2018
    * MTH2151 - Graphs (Prof. Marc Sevaux), since 2019
    * MTH2153 - Numerical methods 1 (Dr. Bertrand Banos), since 2018
    * MTH2251 - Mathematical Programming (Prof. Marc Sevaux), since 2018
    * MTH2254 - Multi-objective optimization (Prof. Xavier Gandibleux), since 2018
    * MTH2352 - Heuristics and metaheuristics (Prof. Marc Sevaux), since 2019
    * OADE301 - Decision aiding tools (Dr. Alexandru Olteanu), since 2018
    * OPCE501 - Combinatorial Optimization (Prof. Marc Sevaux), since 2019
    * OPE401 - Operations Research (Dr. Alexandru Olteanu), since 2018
    * ROP2301 - Optimization (Prof. Marc Sevaux), since 2018
    * UVOE501 - Virtual factory and optimization (Dr. Alexandru Olteanu), since 2018
    * UNOE401 - Digital factory  and optimization (Dr. Alexandru Olteanu), since 2018

**Comment by azev77** [comment]
Do you have links to the course material: lecture notes & code?

**Comment by sevaux** [comment]
Unfortunately, not yet. Is it compulsory? If yes, we may take some time to setup some web pages.

**Comment by azev77** [comment]
It’s not required.
But in my view, those are most useful

**Comment by sevaux** [comment]
OK, we will prepare that during summer time. Thanks.

**Comment by ViralBShah** [comment]
I'm adding these without links for now.
