### ISSUE TITLE
Add micro-benchmark?

### ISSUE THREAD

**Issue by adivzev** [JuliaLang/www.julialang.org#1304]
Could you add a micro-benchmark for the language D? I expect a responsible implementation in D to give Julia a serious run for its money. 

See [Why Program in D](https://wiki.dlang.org/Why_program_in_D) for this quote from one of the language creators:
"[D] optimizes it down to code that is virtually indistinguishable from what a C programmer would write for maximum efficiency."
Also, scroll down on the same page to the brief section called "Numerical programmers".  See [https://wiki.dlang.org/Scientific_Programming_in_D](https://wiki.dlang.org/Scientific_Programming_in_D), also very short, as well (and disregard the comment about libraries, since it's from 2015).

**Comment by StefanKarpinski** [comment]
It doesn't seem like there's any reason to expect the performance of D to differ much from C/C++. Every additional language adds a significant burden when the benchmarks need to be run or updated. If you want to add benchmarks for a new language, if you can setup a single system where all of the benchmarks can be run and make sure they still work, then 👍🏻. Unfortunately, this is quite hard to do.
