### ISSUE TITLE
Bridge the gap, please! (from Matlab to Julia)

### ISSUE THREAD

**Issue by bardo84** [JuliaLang/www.julialang.org#1305]
Coming from Matlab, an experience with Julia

The first phase - getting the Julia syntax right - was easy - as long as everything is kept in a single file.
Then one (me) hits a wall - How to do the stuff below? 

Want to use functions in several files? 
In Matlab:
- add path to path.txt
- save function or class in a file with the same name, easy
In Julia: learn about include, import, module - steeper but feasible.

Want to write "functions with own memory" aka Data Structures? 
In Matlab, use one of:
- persistent variables
- local variables with nested functions
- a class with local variables ("properties")
In Julia: 
Text books and tutorials appear too basic and do not show fully developed functions.
Looking at DataStructures.jl is not helping either, since it is already 2 steps ahead.
(Another problem is that it uses a dict as base structure with its own limitations.)

So there remains a gap to be closed.

How to improve?
- if there are good sources for someone with a Matlab background, please let me know.
- if someone is interested in adding a chapter "from Matlab to Julia", I would be happy to help with examples.

**Comment by StefanKarpinski** [comment]
Please use https://discourse.julialang.org/ for this kind of feedback.

**Comment by bardo84** [comment]
ok
