### ISSUE TITLE
Rework Research section

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1306]
We should still prominently link the research but right now, it is just a list of papers and awards which is helpful but less valuable than some of the other areas.

**Comment by ViralBShah** [comment]
The awards and prizes are valuable and should not be buried. The publications could be spun out into a separate page since they are simply not easy to maintain any more. Some refactoring is probably required.

**Comment by ViralBShah** [comment]
Contribute could be a new section, or even be a major theme of the Community page. This is discussed in #1328. I would actually like to improve the Research page, not drop it.

**Comment by ChrisRackauckas** [comment]
Publications should just be generated from Google Scholar, and it should say that if you want to be featured on the page you should cite the Julia paper.

**Comment by ViralBShah** [comment]
How do you generate from Google Scholar? We can just link to it - but it would be nice if we can generate a list for our own page.

**Comment by timholy** [comment]
> if you want to be featured on the page you should cite the Julia paper.

Good for going forward but perhaps not retrospectively.

**Comment by ChrisRackauckas** [comment]
https://serpapi.com/google-scholar-api can scrape it. I think we need to go to scraping because it's thousands at this point, or just link to Google Scholar.

**Comment by ViralBShah** [comment]
I think we can stop accepting new papers. In fact people have stopped submitting anyways. So we can archive, not accept new submissions, and just link to the google scholar (which we already do).

**Comment by ViralBShah** [comment]
I got the scraper written, but hit maximum requests

```
using HTTP, JSON, ProgressMeter, JLD

const article = "SS8DU0MzuasJ"
const api_key = "" 
const num_pages = 180

function get_citations()
    cites = []
    @showprogress 1 "Fetching... " for i in 1:180
        q = HTTP.get("https://serpapi.com/search.json?engine=google_scholar&cites=$article&api_key=$api_key&start=$i&num=20")
        push!(cites, JSON.parse(IOBuffer(HTTP.payload(q))))
    end
    return cites
end
```

**Comment by ViralBShah** [comment]
The simplest thing is to just link to google scholar rather than trying to put all the citations here (even though that would be kind of nice to have all of them listed on 1 page).
