### ISSUE TITLE
"Code Examples" page is broken

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/www.julialang.org#1308]
This is the first result on google for "Julia code example":

https://julialang.org/learning/code-examples/

but the repl.it session does not load:

<img width="1235" alt="Schermafbeelding 2021-06-29 om 16 07 50" src="https://user-images.githubusercontent.com/6933510/123812177-2936a900-d8f4-11eb-8dcf-de0a8c2a6109.png">

**Comment by logankilpatrick** [comment]
Hey @fonsp is this still the case? It is working for me
