### ISSUE TITLE
Micro-benchmarks plot shows overlapping labels on Firefox

### ISSUE THREAD

**Issue by melissawm** [JuliaLang/www.julialang.org#1327]
The plot showing [Micro-benchmark results](https://julialang.org/benchmarks/) is currently showing unreadable, overlapping labels on Firefox:

![Screenshot_20210722_154740](https://user-images.githubusercontent.com/3949932/126694188-875f546a-1e33-4b6d-b980-67aa76fd2307.png)

I'm using Manjaro Linux and Firefox 90.0.1

**Comment by giordano** [comment]
How does [this image](https://raw.githubusercontent.com/JuliaLang/www.julialang.org/d2e2bdec330f830ca7147194c7ad1780ffbd657c/_assets/images/benchmarks.svg) appear in your browser?

**Comment by melissawm** [comment]
No better, unfortunately: 

![Screenshot_20210723_192106](https://user-images.githubusercontent.com/3949932/126846883-ef2da338-199c-4963-b292-9e800b063804.png)

It does show just fine on Chrome, so it appears to be a Firefox-specific thing.

**Comment by giordano** [comment]
This is how the image appears to me on Firefox 90 on ArchLinux (which isn't much different from your setup):
![image](https://user-images.githubusercontent.com/765740/126848302-4481508f-aebf-425c-a042-83b883d9f44a.png)
Note that the image is an SVG, so the rendering of the text is done by the browser (and I guess something is failing in your browser).  A raster image would solve the issue for you, but that would come at the cost of worse resolution and larger file.  The script used to generate the image is at [`_assets/benchmarks/benchmarks.jl`](https://github.com/JuliaLang/www.julialang.org/blob/d2e2bdec330f830ca7147194c7ad1780ffbd657c/_assets/benchmarks/benchmarks.jl)

**Comment by hug0b** [comment]
The image renders fine for me in Firefox 102 on Windows 10, Fedora 36 and Android 12.
