### ISSUE TITLE
Julia documentation translation

### ISSUE THREAD

**Issue by amir-ni** [JuliaLang/www.julialang.org#1337]
Since Julia was the programming language used in our [Applied Linear Algebra course](http://sharif.edu/~mtefagh/ala/home.html), some of my classmates and I started translating Julia's documentation to Persian last semester to help other students.

Almost a third of the manual has been translated or is being translated. We hope more people will be able to find out about us by introducing ourselves in the localization section of Julia's website. Also, more people might be encouraged to help us.

Our Github repository is [here](https://github.com/AppliedLinearAlgebra-Sharif/julia-docs), and the translated documentation is published using RTD and is available [here](https://julia-docs.readthedocs.io/fa/v1.6.0/).

**Comment by ViralBShah** [comment]
This is great! @logankilpatrick Do we have a section on our website where we add translations? Perhaps we can carry these in the Community section.

**Comment by logankilpatrick** [comment]
Yes, this is the proper section: https://julialang.org/community/#localization

**Comment by ViralBShah** [comment]
Added in 89c13b46d8844ebac362703a64b1f2e0b441e6c2
