### ISSUE TITLE
New Classroom with Julia at University of Florida

### ISSUE THREAD

**Issue by 01-vyom** [JuliaLang/www.julialang.org#1374]
We have started using Julia for the following course: 

University of Florida
COT 5615, Math for Intelligent Systems: Fall 2021, Prof. Kejun Huang

**Comment by Mahdi00211** [comment]
How can i access to this julia course

**Comment by 01-vyom** [comment]
The course is based on this [book](http://vmls-book.stanford.edu/vmls.pdf). Our course syllabus for this semester is not public.

**Comment by Mahdi00211** [comment]
Hi
What is closed??

در تاریخ چهارشنبه ۲۰ اکتبر ۲۰۲۱،‏ ۵:۵۰ Viral B. Shah <
***@***.***> نوشت:
