### ISSUE TITLE
Remove version number from "download button" on main page

### ISSUE THREAD

**Issue by sverek** [JuliaLang/www.julialang.org#1382]
For more clarity:

Change "Download Julia 1.6.3" to "Download Julia" on the main page.

Since new users may be looking for downloading LTS, nightly, 1.7, or other versions.

**Comment by DilumAluthge** [comment]
Right now, we have two buttons:
1. Download v1.6.3
2. Documentation

What if we instead have three buttons:
1. Download v1.6.3
2. Download other versions
3. Documentation

**Comment by StefanKarpinski** [comment]
Maybe `Download latest (v1.6.3)`, `All downloads`, `Documentation`?

**Comment by KristofferC** [comment]
I don't think we have the ability right now to do OS detection which would allow for a direct download button. So in the meantime I think it makes sense to remove the explicit version because it makes you indeed think you will get such a direct download.

**Comment by StefanKarpinski** [comment]
Isn't detecting the OS straightforward? (For someone who has any web skillz, of course.)

**Comment by logankilpatrick** [comment]
I started the PR, it works, but there's edge cases for the Linux folks so we didn't push forward with it

**Comment by StefanKarpinski** [comment]
If the users OS is Linux, could we just not show that button?
