### ISSUE TITLE
Add Governance page which we can update

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1393]
Right now, the governance page points to a blog post from 2019. While it is more or less up to date, we should likely make a page which we can update directly without changing history. 

https://julialang.org/blog/2019/02/julia-entities/

**Comment by ViralBShah** [comment]
Actually - I agree with the original proposal of having a governance page on julialang.org. The entities blog post has the right content, but needs updating just because it is a couple of years old. 

It would be best to start with an updated version of that as the Governance page.

**Comment by DilumAluthge** [comment]
I think the vast majority of the original blog post is accurate.

We should update the number of active committers and dormant committers. We should also update the part about Julia community members on the NumFOCUS board, e.g. Logan is on the board currently.

@StefanKarpinski @ViralBShah Anything else stand out to you as needing an update?

**Comment by ViralBShah** [comment]
There are lots of small things that need changing all over.

# of contributors with commit access
NF signatories
NF board member
More Julia NF projects 
Some people have changed jobs
Some Julia Computing updates

While we do these updates, we may think of other things.

**Comment by ViralBShah** [comment]
I am updating that blog post for URLs, but I don't think we should edit any content there, and it is best to create a page on the website that can be kept updated.
