### ISSUE TITLE
Splash image (really unimportant!)

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/www.julialang.org#14]
There's a tiny glitch in the splash image (https://github.com/JuliaLang/staging.julialang.org/blob/master/v2/img/splash-img.png) which keeps catching my eye.

<img width="186" alt="screen shot 2018-08-02 at 12 24 42" src="https://user-images.githubusercontent.com/52289/43581022-4c068512-964f-11e8-89cf-d8551523f24a.png">

I decided to see if I could improve the image while keeping everything more or less the same.

![splash-img](https://user-images.githubusercontent.com/52289/43581049-701f0938-964f-11e8-94b4-7c24e70d546c.png)

The markers are now evenly spaced, which is less obtrusive...

The code for making this is [here](https://gist.github.com/cormullion/c2bd822b4ce5ac22bb5e12fbc4fee140)... :)

**Comment by ViralBShah** [comment]
PR?
