### ISSUE TITLE
Allow CORS on `julialang-s3.julialang.org`

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/www.julialang.org#1439]
I was trying to make a cool website that automatically shows the latest stable Julia version in example snippets using JS:
```js
// (this is JS)
versions = await (await fetch(`https://julialang-s3.julialang.org/bin/versions.json`)).json()
```

but it failed because the server (`julialang-s3.julialang.org`) is not configured to allow CORS, i.e. allow requests from JS inside pages on domains other than `julialang.org`. Unless this is intentional, it would be great if we could configure the S3 to allow CORS on `GET` requests: https://docs.aws.amazon.com/AmazonS3/latest/userguide/enabling-cors-examples.html 💕

**Comment by StefanKarpinski** [comment]
cc @staticfloat who largely controls our S3 buckets

**Comment by staticfloat** [comment]
Try again now?

**Comment by fonsp** [comment]
It works, yayy! 💕

**Comment by fonsp** [comment]
It looks like this isn't working anymore:

![Scherm­afbeelding 2022-11-01 om 21 24 21](https://user-images.githubusercontent.com/6933510/199333817-fa3e8f05-3284-4ce8-84b3-14a963ac900e.png)

There should be the response header:
```
Access-Control-Allow-Origin: *
```

**Comment by fonsp** [comment]
It was working last week, but now not working again:

![image](https://user-images.githubusercontent.com/6933510/212102523-82cb571a-f2a9-4fa9-b2ed-456b575ce46d.png)

@staticfloat Any idea why the headers change this frequently?

**Comment by staticfloat** [comment]
It looks like Fastly started denying the CORS request; I've fixed that too now, please check to see if that works for you now.

**Comment by fonsp** [comment]
Thanks! Works now!

I am building some web applications that depend on this, perhaps it is wise to set up my own proxy to this file on plutojl.org to ensure that the CORS settings don't change?
