### ISSUE TITLE
Button hover consistency

### ISSUE THREAD

**Issue by djsegal** [JuliaLang/www.julialang.org#144]
It seems like: 
+ when you hover over a blue button it gets brighter
+ but when you hover over a green one it gets darker?

Was this a custom css decision?

-----

default vs hover blue

<img width="566" alt="screen shot 2018-08-15 at 4 52 56 pm" src="https://user-images.githubusercontent.com/3156114/44172620-c1701500-a0ab-11e8-885a-739bfab12434.png">

<img width="562" alt="screen shot 2018-08-15 at 4 53 22 pm" src="https://user-images.githubusercontent.com/3156114/44172640-cfbe3100-a0ab-11e8-9747-9c09b0cc013e.png">

default vs hover green

<img width="566" alt="screen shot 2018-08-15 at 4 52 56 pm" src="https://user-images.githubusercontent.com/3156114/44172620-c1701500-a0ab-11e8-885a-739bfab12434.png">

<img width="561" alt="screen shot 2018-08-15 at 4 53 07 pm" src="https://user-images.githubusercontent.com/3156114/44172635-ca60e680-a0ab-11e8-94fe-f219176f1f8c.png">

**Comment by djsegal** [comment]
Don't know where the color scheme came from?

Looks like you could probably just steal Chase's:

+ chase.com

**Comment by ViralBShah** [comment]
I think this is fine.
