### ISSUE TITLE
Images overflowing on mobile

### ISSUE THREAD

**Issue by djsegal** [JuliaLang/www.julialang.org#145]
<img width="381" alt="screen shot 2018-08-15 at 5 56 07 pm" src="https://user-images.githubusercontent.com/3156114/44175538-84f4e700-a0b4-11e8-93dc-d57adabcf73d.png">

Thought this got fixed. But it seems like a `.gitignored` file has it commented out?

+ https://github.com/JuliaLang/www.julialang.org/blame/bc3b7fc1b951870370c33770ed8210e884a0077b/v2/css/app.css#L406

**Comment by djsegal** [comment]
Similar to this,

`Programming` seems to be too long a word on mobile?

<img width="385" alt="screen shot 2018-08-15 at 5 58 54 pm" src="https://user-images.githubusercontent.com/3156114/44175668-e6b55100-a0b4-11e8-8371-6398fb4b271f.png">

**Comment by ViralBShah** [comment]
These seem to have got fixed. Look fine on my mobile and resized browser window.
