### ISSUE TITLE
Required enhancement in juliaacademy's button UI

### ISSUE THREAD

**Issue by aditkumar72** [JuliaLang/www.julialang.org#1450]
The `Complete and  Continue` button in lecture pages are not visible unless hovered.

![image](https://user-images.githubusercontent.com/40900556/144181570-865f7e78-ada2-4dcf-a20a-e958cedc5bf2.png)
[demo](https://juliaacademy.com/courses/375479/lectures/16882463)

**Comment by aditkumar72** [comment]
I like to work on this. My idea is to make the `Complete and Continue` button UI same as `Previous Lecture`

**Comment by ViralBShah** [comment]
It's hosted on teachable.com. I don't know how configurable it is.

**Comment by logankilpatrick** [comment]
I can't reproduce this issue locally. Please let me know if it persists!
