### ISSUE TITLE
Some images getting stretched

### ISSUE THREAD

**Issue by zmoon** [JuliaLang/www.julialang.org#1453]
For example
![image](https://user-images.githubusercontent.com/15079414/144288055-440b20d8-18f0-4858-a3b0-3a83d61dd79e.png)

**Comment by ViralBShah** [comment]
We should probably have a different example here that works out of the box today.

**Comment by logankilpatrick** [comment]
What do you mean by works out of the box? Perhaps we could use: https://github.com/JuliaGaming/Tetris ?

**Comment by ViralBShah** [comment]
Something you can clone the repo and run. That minesweeper code is years old.

**Comment by ViralBShah** [comment]
I suppose Tetris could be good, but I don't see a Manifest or a Project.toml. Whichever one we pick, we have a bit of a commitment towards ensuring it reliably works and is maintained.

**Comment by zmoon** [comment]
While that sounds good, just to be clear, in this issue I was pointing to the stretching resulting from the CSS, and it isn't just the Ecosystem examples.

![image](https://user-images.githubusercontent.com/15079414/144872660-80c83068-f0b5-47e8-8b63-7638ec4f06da.png)
