### ISSUE TITLE
Broaden the scope of the ecosystem section of the home page

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1467]
Right now, it just includes: "Visualization, General Purpose, Data Science, Machine Learning, Scientific Domains, Parallel Computing"

Other ideas: 
Chemistry
Biology
WebDev
Gaming 

(just spitballing some ideas)

Maybe the existing sections are as good as we can get but wanted to open this up to brainstorm.

**Comment by ViralBShah** [comment]
The main issue is design - what all to present and how.
