### ISSUE TITLE
New Julia Book

### ISSUE THREAD

**Issue by mz2357** [JuliaLang/www.julialang.org#1473]
Noel Kalicharan wrote a new book on Julia: "Julia - Bit by Bit", which has recently been published by Springer (ISBN: 978-3-030-73935-5) and is not yet listed in the list of books.

**Comment by sayantan1410** [comment]
Hey I would like to work on this issue, Do I have to add the link of the book to this md file "https://github.com/JuliaLang/www.julialang.org/blob/main/learning/books.md" ? 
Thank you.

**Comment by logankilpatrick** [comment]
yes, that would be great!

**Comment by mz2357** [comment]
Thanks for taking care of this! The link is correct, but as this is one of the most recent books it should probably appear at the top of the list due to the anti-chronological order.

**Comment by sayantan1410** [comment]
Okay making another commit to the PR after changing it. @mz2357

**Comment by sayantan1410** [comment]
hey @mz2357 , I have updated the PR can you please check and drop a comment if everything is alright. Thank you.

**Comment by mz2357** [comment]
Hey Sayantan, I checked it, and it looks perfect to me. Thanks!

**Comment by sayantan1410** [comment]
Thank you @mz2357 
can it be merged now ? @logankilpatrick
