### ISSUE TITLE
Create editable template for the schools where Julia is taught

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1478]
@ViralBShah Do you have a WIP file that you used to generate the exiting image here: https://julialang.org/learning/ under the "In the classroom" heading? CC @jpfairbanks

**Comment by ViralBShah** [comment]
I believe there's a google slide on that. @StefanKarpinski created that slide, but it should be fairly easy to edit that slide. It is not programmatically generated.

**Comment by logankilpatrick** [comment]
Here is the private link. If someone wants to add an image, we can give them access too: https://docs.google.com/presentation/d/1t94qHV-Al8gr-AVGEB4RG1KPYMZEN0CUdlfV2oPsAgU/edit?usp=sharing
