### ISSUE TITLE
Graduate computational fluid dynamics course featuring Julia language at Technion

### ISSUE THREAD

**Issue by frankelsh** [JuliaLang/www.julialang.org#1485]

**Comment by logankilpatrick** [comment]
Hey! It would be great if you could make a PR and add the course

**Comment by frankelsh** [comment]
Thanks. How?

-Steven

--

**Comment by ViralBShah** [comment]
Please submit a PR by editing this: https://github.com/JuliaLang/www.julialang.org/edit/main/learning/classes.md
