### ISSUE TITLE
LTS links

### ISSUE THREAD

**Issue by mloubout** [JuliaLang/www.julialang.org#1492]
I am not sure what's the best way to "fix" it, but currently, the [help] links to download LTS version of julia point to `1.7.1` download instructions instead of `1.6.5`, so copy-pasting the instructions doesn't install the correct version.

The direct download link work fine but I'm not sure if the [help] page should have the code blocks (wget, ...) for the LTS julia version.

**Comment by ViralBShah** [comment]
The `[help]` stuff is unfortunately not versioned. I doubt there's a good solution, beyond noting in there that people should substitute the correct version.

**Comment by mloubout** [comment]
My apologies for not responding. I understand this is how it's setup and the complications. I however still think version instructions would be good (for example pytorch has a nice table for different OS and version). But this is probably not a priority.
