### ISSUE TITLE
Release dates on download page

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/www.julialang.org#150]
It would probably be a good idea to put the release dates on the downloads page, so that people know how old those versions are. This seems pretty standard for most software downloads.

**Comment by annainfo** [comment]
And have them in ISO 8601 date format YYYY-MM-DD. Time in UTC.

**Comment by ararslan** [comment]
Having the time seems excessive but formatting the date as YYYY-MM-DD seems appropriate.

**Comment by annainfo** [comment]
> Having the time seems excessive
Without a defined time YYYY-MM-DD is not defined.

**Comment by simonbyrne** [comment]
Dates are approximate in any case, since builds may take a day or so to complete after release.

**Comment by annainfo** [comment]
> Dates are approximate in any case, since builds
> may take a day or so to complete after release.
Why would something that happens "after release" be relevant for the determination of the "release date"? And why would it make the date "approximate"?

**Comment by simonbyrne** [comment]
> Why would something that happens "after release" be relevant for the determination of the "release date"?

Because they're the links for the downloads of the builds.

> And why would it make the date "approximate"?

Approximate was a poor choice of word. Basically, my argument is that a 48 hours is sufficient precision for reporting the release date.

As was mentioned on discourse, your overall tone is very combative and not at all conductive to the collaborative nature of this project. Please do consider how your tone might be read by others.

**Comment by annainfo** [comment]
> Because they're the links for the downloads of the builds.

What ("they") are the links? How do links come into the process of determination of the "release date"?

> Basically, my argument is that a 48 hours is sufficient
> precision for reporting the release date.

Never seen this anywhere else. Might cause confusion if there are two release within less than 48h, and the later release has lower date.

Github even provides minute precision (verify at https://github.com/JuliaLang/julia/tags) - easy to derive a precise YYYY-MM-DD.

>As was mentioned on discourse, your overall tone
> is very combative and not at all conductive to the
> collaborative nature of this project.

You might be violating https://julialang.org/community/standards/ .

**Comment by ViralBShah** [comment]
We are not going to have timestamps along with the dates on downloads. If that is not ISO compliant, that is ok.

**Comment by annainfo** [comment]
> We are not going to have timestamps along with
> the dates on downloads. If that is not ISO compliant, that is ok.

Did anyone propose to have "timestamps along with the dates"?

**Comment by ViralBShah** [comment]
Yes, I thought that is what you were proposing in the second comment above.

**Comment by annainfo** [comment]
No, I proposed to have YYYY-MM-DD. No time.

**Comment by ararslan** [comment]
Thank you for clarifying your proposal. That indeed makes sense.

**Comment by ViralBShah** [comment]
@ararslan I think the simplest thing that is useful is to add a download date to the release table or in the release version subtitle.

**Comment by ararslan** [comment]
That seems reasonable.

**Comment by ViralBShah** [comment]
@ararslan Bumping to see if you think we can start doing this.
