### ISSUE TITLE
Broken link detector

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#156]
Should run a tool to report broken links and fix as many as meaningful.

**Comment by annainfo** [comment]
What kind of links? External, internal? A good start would be to have a link policy.

**Comment by ViralBShah** [comment]
I think various internal ones are broken.

**Comment by ViralBShah** [comment]
Not sure what a link policy entails. Open to ideas.

**Comment by annainfo** [comment]
Probably it would be good to have a lossless conversion between file names and URLs. Excluding the days as is currently done could lead to problems in case two posts having otherwise identical file names are created.

**Comment by inkydragon** [comment]
Maybe [wummel/linkchecker: check links in web documents or full websites](https://github.com/wummel/linkchecker)

or we could re-write it in julia first.
