### ISSUE TITLE
Internationalisation (i18n): switch fonts to Noto

### ISSUE THREAD

**Issue by annainfo** [JuliaLang/www.julialang.org#163]
Noto fonts are created to 
- cover all of Unicode (Julia 1.0 is published with the claim to support Unicode 11, Noto does not cover all of that)
- allow mixing of different scripts (e.g. Han, Korean, Arabic, Latin) while text will still look consistent (height, width of characters; thickness of lines). 

For Latin there are Sans, Serif, Mono. In Noto Sans there is difference between I and l (former is uppercase i, latter lowercase L), not so in Roboto.

More about Noto:
- https://www.google.com/get/noto/
- https://github.com/googlei18n/noto-fonts

Affected files, list not exhaustive:
- https://github.com/JuliaLang/www.julialang.org/blob/master/_includes/head.html (contains : `<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i" rel="stylesheet">`)
- https://github.com/JuliaLang/www.julialang.org/blob/master/v2/css/fonts.css

**Comment by ViralBShah** [comment]
Unclear what we need to do here - the website is ok for now.
