### ISSUE TITLE
Ecosystem tab content layout

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/www.julialang.org#164]
With the increased descriptive text (+) where the text goes depends on the way browser fonts are set and that can create weird layouts (-). See below. Either use two columns or two+ paragraphs where the second paragraph(s) is entirely under the graphic or make the image live in a container that has its height set to the height of the enclosing container or <your solution here>.

![image](https://user-images.githubusercontent.com/1682118/44433321-cfbea500-a573-11e8-88a4-18348bbf6fe4.png)

![image](https://user-images.githubusercontent.com/1682118/44433356-efee6400-a573-11e8-9d06-92e5350849df.png)

![image](https://user-images.githubusercontent.com/1682118/44433410-16140400-a574-11e8-98b9-ca51e9c4e29a.png)

**Comment by ViralBShah** [comment]
dup of #55
