### ISSUE TITLE
New Book on Julia

### ISSUE THREAD

**Issue by MarineVishal** [JuliaLang/www.julialang.org#1640]
Hey Team 🤗 I have recently Published a Book on Julia...
**_**"Programming With Julia: The Beginning"**_**

I have published it on Amazon and it's available for all marketplace.
US ~ https://www.amazon.com/dp/B09TJ65N4M
UK ~ https://www.amazon.co.uk/dp/B09TJ65N4M
Germany ~ https://www.amazon.de/dp/B09TJ65N4M
France ~ https://www.amazon.fr/dp/B09TJ65N4M
Spain ~ https://www.amazon.es/dp/B09TJ65N4M
Italy ~ https://www.amazon.it/dp/B09TJ65N4M
Netherlands ~ https://www.amazon.nl/dp/B09TJ65N4M
Japan ~ https://www.amazon.co.jp/dp/B09TJ65N4M
Brazil ~ https://www.amazon.com.br/dp/B09TJ65N4M
Canada ~ https://www.amazon.ca/dp/B09TJ65N4M
México ~ https://www.amazon.com.mx/dp/B09TJ65N4M
Australia ~ https://www.amazon.com.au/dp/B09TJ65N4M
India ~ https://www.amazon.in/dp/B09TJ65N4M

**Comment by ViralBShah** [comment]
Please submit a PR to: https://github.com/JuliaLang/www.julialang.org/blob/main/learning/books.md
