### ISSUE TITLE
Automated test - Mozilla Observatory : D- , Score 25/100

### ISSUE THREAD

**Issue by annainfo** [JuliaLang/www.julialang.org#165]
https://observatory.mozilla.org/analyze.html?host=julialang.org

Score: | 25/100
-- | --
Tests Passed: | 5/11

Test | Pass | Score | Explanation |  
-- | -- | -- | -- | --
Content Security Policy |   | -25 | Content Security Policy (CSP) header not implemented |  
Cookies |   | 0 | No cookies detected |  
Cross-origin Resource Sharing |   | 0 | Public content is visible via cross-origin resource sharing (CORS) Access-Control-Allow-Originheader |  
HTTP Public Key Pinning |   | 0 | HTTP Public Key Pinning (HPKP) header not implemented (optional) |  
HTTP Strict Transport Security |   | -10 | HTTP Strict Transport Security (HSTS) header set to less than six months (15768000) |  
Redirection |   | 0 | Initial redirection is to HTTPS on same host, final destination is HTTPS |  
Referrer Policy |   | 0 | Referrer-Policy header not implemented (optional) |  
Subresource Integrity |   | -5 | Subresource Integrity (SRI) not implemented, but all external scripts are loaded over HTTPS |  
X-Content-Type-Options |   | -5 | X-Content-Type-Options header not implemented |  
X-Frame-Options |   | -20 | X-Frame-Options (XFO) header not implemented |  
X-XSS-Protection |   | -10 | X-XSS-Protection header not implemented

**Comment by ViralBShah** [comment]
Not sure what to do here.
