### ISSUE TITLE
Please add release notes link to download page and home page

### ISSUE THREAD

**Issue by ghost** [JuliaLang/www.julialang.org#1657]
Please add release notes url link to julia official website home page and download page.

The release notes link : https://docs.julialang.org/en/v1/NEWS/

The home page:  https://julialang.org/
The Download page: https://julialang.org/downloads/

**Comment by shravanngoswamii** [comment]
The link to release notes on the home page and download page is still not there, should I open a PR if it's required and help in closing this 2 year old issue?
