### ISSUE TITLE
Improving JuliaStats GSoC

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaLang/www.julialang.org#1668]
Creating an issue for tracking the JuliaStats GSOC project. I think there's some improvements we could make.
- [ ] Rewrite the CRRao.jl entry, which is currently quite barebones (@ajaynshah)
- [ ] Potentially break up the "Help with JuliaStats packages" if any mentors have more specific interests they'd like to add.

@nosferican mentioned @colintbowers , @matthieugomez , @gragusa , and @lbittarello might be interested in mentoring students working on these projects, esp the ones on panel data. Also @andreasnoack, @kleinschmidt, and @nalimilan more generally.

**Comment by gragusa** [comment]
I can help somehow. I have limited bandwidth these days, but I could make space to mentor a student to topics are related to my research and interests. 

I have not followed closely  GSOC this year. What’s the status? How many students are applying on the JuliaStats side?

**Comment by ViralBShah** [comment]
Done in https://github.com/JuliaLang/www.julialang.org/pull/1666
