### ISSUE TITLE
The "Documentation" button on the home page should link to the "Learn" tab

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaLang/www.julialang.org#1675]
New users are getting sent straight to the manual instead of being directed towards tutorials. I propose that the big blue "Documentation" button link to the "Learn" tab of the page. Or alternatively, we could add a second button, labeled "Learn" or "Tutorials", between the "Download" and "Documentation" buttons to more prominently highlight the alternative learning resources.

xref:
https://discourse.julialang.org/t/blog-post-about-my-experiences-with-julia/79976/168?u=cameronbieganek

**Comment by ViralBShah** [comment]
Learn can be after immediately after Documentation, but shouldn't be before. Please submit a PR for that if you like that.

**Comment by ViralBShah** [comment]
> Learn can be after immediately after Documentation, but shouldn't be before. Please submit a PR for that if you like that.

Done in #1705

**Comment by CameronBieganek** [comment]
@ViralBShah  Please reopen. I think there was a misunderstanding about the intent of this issue. Re-reading my original post, I guess it's not super clear, but what I would like to do is add a third button that says "Learn", which would be located to the right of the blue "Documentation" button in the following screenshot:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/8310743/179429113-abafd248-c36b-4d8d-b36d-5f9bf47384c0.png">

I don't know anything about web programming, so I can't really submit a PR.

**Comment by ViralBShah** [comment]
@CameronBieganek I disagree that we should have a Learn button there. I made it closer in the navbar to make it slightly more prominent.

However, happy to leave this open for people to chime in.

**Comment by sylvaticus** [comment]
Yep, I obviously agree with the op... 😁
I believe "documentation" is too much confusing for casual, first time explorer users... not to consider it sends to a totally different website...
I have made a pr to _replace_ documentation with learn.
In my opinion experienced users would still know how to reach the documentstion from the link bar at the top.

**Comment by logankilpatrick** [comment]
Closing this for now, I think having the documentation link as is should be the right thing to do. I will open a PR in the main Julia docs to add a link back to the learning section on the site.
