### ISSUE TITLE
Invalid Link for Course Details : 15.053x

### ISSUE THREAD

**Issue by mravariya** [JuliaLang/www.julialang.org#1679]
Issue: Invalid link updated on [few MOOC's](https://julialang.org/learning/mooc/) for  [15.053x](https://www.edx.org/course/optimization-methods-business-analytics-mitx-15-053x)

I searched on edX.org for the course using course name, course code, and instructor name but no luck. Looks like either the course name is changed or the course is discontinued from edX.org.

**Comment by ViralBShah** [comment]
Generally, links are provided when classes happen, and then they get taken down. If you find a class with a broken URL - it would be great to have a PR that removes that link (but keeps the class as a historical record).
