### ISSUE TITLE
New Books in Julia

### ISSUE THREAD

**Issue by markmendlovitz** [JuliaLang/www.julialang.org#1684]
T. A Driscoll and R. J. Braun, Fundamentals of Numerical Computation: Julia Edition. SIAM: Philadelphia, PA. 2022.
Y. Nazarathy and H. Klok, Statistics with Julia: Fundamentals for Data Science, Machine Learning and Artificial Intelligence. Springer, 2021.

**Comment by ViralBShah** [comment]
Would be great if you can submit a PR.

**Comment by curio-sitas** [comment]
One could add : 

- S. Nagar,  Beginning Julia Programming For Engineers and Scientists. Apress, 2017
- G. Datseris, U. Parlitz, Nonlinear Dynamics: A Concise Introduction Interlaced with Code. Springer, 2022

I submit a PR

**Comment by curio-sitas** [comment]
The two books @markmendlovitz proposed are in the list but with different publication dates. Therefore i don't know if this issue may be closed or if these books have new editions wich motivates a date change in the list.
