### ISSUE TITLE
Add disclaimer banner

### ISSUE THREAD

**Issue by aaowens** [JuliaLang/www.julialang.org#169]
Reference from https://discourse.julialang.org/t/list-of-working-packages-on-v-1-0/13779/62?u=aaowens

Several people have suggested some kind of disclaimer banner for the 1.0 release, advertising that many packages do not work yet. This would be very helpful for people who don't understand the distinction between the Julia language (released 1.0) and the Julia ecosystem (not quite adjusted to 1.0)

Also, the top of the downloads page encourages people to use either the command line, JuliaBox, or JuliaPro. However, neither JuliaBox or JuliaPro work on 1.0 yet, so people who try it will unexpectedly be using the old version.

**Comment by PetrKryslUCSD** [comment]
I support this idea wholeheartedly. Julia 1.0 is great as a language, but the front page currently generates inflated expectations. I for one could get no plotting to work except for PGFPlotsX... If I was new to the language I would have given up at the third plotting package that failed to install/work.

**Comment by KristofferC** [comment]
For reference we are also working on capping the julia version on packages that are very likely to not work (https://github.com/JuliaLang/Pkg.jl/pull/685)

**Comment by ckoe-bccms** [comment]
Eventually remove the apparently outdated/unmaintained "Ecosystem Pulse" from the front page then, too ? At least for the time being ?

**Comment by ViralBShah** [comment]
Maybe we should have a message and explanation on the downloads page, that many packages are still being updated for 1.0. Thoughts?

**Comment by aaowens** [comment]
I think that would be good, especially if it is at the top of the downloads page. I also think the paragraph beginning, "You may be interested, especially as an existing package author or maintainer, in downloading Julia v0.7.0..." should be moved to the top. I just had a colleague come to me yesterday asking for help updating his old Julia code. He was using 1.0 and didn't know that 0.7 would help with the upgrade. Judging by posts on Discourse, this appears to be common.
