### ISSUE TITLE
"Older Releases" page seems pretty out of date

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/www.julialang.org#1702]
Page: https://julialang.org/downloads/oldreleases/

Latest "old" release listed is 1.5.4.

**Comment by DilumAluthge** [comment]
Well, 1.6 is the current LTS, and 1.7 is the current stable release, so it wouldn't make sense to list 1.6 or 1.7 on that page.

**Comment by quinnj** [comment]
I had someone expecting to find the 1.7.1 or 1.7.2 releases there. But maybe we dont' really make those available publicly?

**Comment by DilumAluthge** [comment]
Ah, good point. I guess we don't list old patch releases on that page just to save space?

The "correct" way to get the URL would be to parse the https://julialang-s3.julialang.org/bin/versions.json file. All of the old releases are listed in that file.

But it would be nice to find a way to list them somewhere on the website in a compact/concise way.

**Comment by ViralBShah** [comment]
A simple fix is to just mention that this page does not have all the patch releases, but details for those are available in `versions.json`.

**Comment by ararslan** [comment]
It should be possible to automatically generate some static HTML based on versions.json for inclusion on that page.
