### ISSUE TITLE
Use the new github pages deployment workflow

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#1719]
This should make the website deployment a lot more seamless.

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

**Comment by Saransh-cpp** [comment]
Hi, @ViralBShah!

I recently created a [PR](https://github.com/tlienart/Franklin.jl/pull/982) in Franklin's repository outlining the steps required to deploy PR previews using GH Actions and GH Pages. This means that this repository can get rid of the Netlify part of the infrastructure and shift everything to GitHub. Keeping all the infrastructure in a single place and getting rid of the redundant ones does sound good to me.

But.

This won't be possible with the new GH Pages, as they now don't require maintaining a `gh-pages` branch for the deployment. But, we can still maintain a `gh-preview` branch (like right now) to deploy previews using Netlify (like right now) and deploy the main website using the new GH Pages workflow.

So, we could -
- Shift the Netlify infrastructure to GH Actions/Pages and keep the old GH Pages workflow.
- Keep the Netlify infrastructure as it is and migrate to the new GH Pages infrastructure.

I don't have a very strong preference here. I can take this up, but which path should I go ahead with?
