### ISSUE TITLE
New icon for discourse.julialang.org?

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/www.julialang.org#1746]
In this screenshot I have one tab with `docs.julialang.org`, and one with `discourse.julialang.org`. They both have the same icon, so I don't know which is which!

![image](https://user-images.githubusercontent.com/6933510/188612793-dd9abd68-a96a-4582-9c35-5775eadce9d4.png)

It would be nice to use a different icon for the Julia discourse!

One idea I had was something like this:

![julia-discourse](https://user-images.githubusercontent.com/6933510/188615209-c7d9908c-02a8-4830-88ff-c8b94846d074.png)

which is inspired by the discourse logo:

![](https://upload.wikimedia.org/wikipedia/commons/c/cf/Discourse_logo.svg)

I think the colours still need some tweaking, but let me know if you like the idea!

**Comment by logankilpatrick** [comment]
I think this sounds okay to me, I just pinged the Discourse Admins for feedback.

**Comment by ararslan** [comment]
The favicon for Discourse's own website, discourse.org, is D part of the logo as shown above. To make the connection to Discourse more obvious, we could potentially just put the regular Julia dots inside the black Discourse D. The Venn diagram is nice but doesn't really imply a connection to Discourse to me.

**Comment by fonsp** [comment]
Here is the same with bigger circles, and the union is the same color as the discourse logo 🍭


https://user-images.githubusercontent.com/6933510/188837108-1713fd0e-1943-4900-836a-dc6709a0b999.mov

**Comment by mbauman** [comment]
I'm on board with a change. What about something like:

![68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f632f63662f446973636f757273655f6c6f676f2e737667](https://user-images.githubusercontent.com/154641/188902230-6e853246-8c3b-409f-a1f2-358954c9c57d.png)

**Comment by fonsp** [comment]
cc @cormullion

**Comment by cormullion** [comment]
reminds me of the Colors.jl logo 
![image](https://user-images.githubusercontent.com/52289/188921480-73e04627-b65e-4b8d-9f2a-d68e26b58643.png)
 (made with Julia of course 😂)

At the required size, though, I’d suggest a shape difference, not just a few differently coloured pixels. I’ll volunteer some more options tomorrow if you like…

**Comment by StefanKarpinski** [comment]
I like @fonsp's last colors with @mbauman's design.

**Comment by cormullion** [comment]
Sorry Matt, I failed to notice the dark shape you'd used; my dark-mode browser didn't show it. Still, it reminded me to check these against both Light and Dark backgrounds.

<img width="667" alt="Screenshot 2022-09-07 at 19 55 20" src="https://user-images.githubusercontent.com/52289/188987080-2234fdf4-0cd7-4c89-ac65-1182c847f0dd.png">

They might work when sized to 32x32 pixels, not sure yet...

**Comment by fonsp** [comment]
This looks great! What are the next steps @logankilpatrick ?

**Comment by StefanKarpinski** [comment]
I like the middle one.

**Comment by logankilpatrick** [comment]
@cormullion can you add these as icons into the graphics repo?

**Comment by cormullion** [comment]
Sure thing  - 64x64 PNGs [here](https://github.com/cormullion/graphics/tree/master/discourse-icons-64x64)

**Comment by StefanKarpinski** [comment]
I hate to do this, but I didn't notice the yellow background on the middle one before, and I actually think the second one is the nicest (not sure why I've apparently changed my mind). Can we go with that icon instead?

**Comment by cormullion** [comment]
No problem, updated.

**Comment by logankilpatrick** [comment]
Updated, thank you @cormullion !!

**Comment by cormullion** [comment]
For posterity, here's the code to generate it:

```julia
using Luxor

function main(fname, S = 64;
        linewidth = 4)
    Drawing(S, S, fname)
    origin()
    setline(linewidth)
    k = 0.85S
    sethue(Luxor.julia_blue)
    box(O, k, k, [0, 0.5k, 0.5k, 0.5k], :stroke)
    translate(-S / 40, S / 25)
    juliacircles(S / 5)
    finish()
    preview()
end

# main("/tmp/julia-discourse-32.png", 32, linewidth=2)
main("/tmp/julia-discourse-64.png", 64, linewidth = 5)
```
