### ISSUE TITLE
Julia book 

### ISSUE THREAD

**Issue by azev77** [JuliaLang/www.julialang.org#1753]
https://press.princeton.edu/books/hardcover/9780691176819/the-economics-of-sovereign-debt-and-default

Julia code:
https://github.com/markaguiar/TheEconomicsofSovereignDebt

**Comment by ViralBShah** [comment]
This one makes me think that we may want to distinguish between Books teaching Julia vs. Books using Julia in different domains.

**Comment by logankilpatrick** [comment]
Closing for now, please open a PR if you want this added.
