### ISSUE TITLE
Document Upgrade Procedure

### ISSUE THREAD

**Issue by RossBoylan** [JuliaLang/www.julialang.org#1754]
Please document the appropriate upgrade procedure for a new release of `julia`.  As far as I can tell, this information is not in the current documentation.

1. Do I need to uninstall the old version first?
2. What do I need to do to ensure the my code/projects/environments will continue to work?
3. Do I need to kill existing julia sessions first?

These are pretty basic questions; it would be very helpful to have readily available answers.

I suspect the answer may vary with the type of upgrade (major/minor/patch).  I presume major or minor upgrades will require recreating environments unless the installer is clever.  It may also depend on the OS or installation method.

There are various hints if you search, and the very last entry in the FAQ will help those who find it, and realize it is relevant to question 2 above.

**Comment by RossBoylan** [comment]
Thanks.  I looked for some kind of "report issues with the website to ..." at the bottom of the pages, but didn't see anything.

**Comment by ViralBShah** [comment]
`juliaup` pretty much takes care of this.
