### ISSUE TITLE
[BUG] sign up button disappears

### ISSUE THREAD

**Issue by Shivansh-yadav13** [JuliaLang/www.julialang.org#1762]
**Describe the bug**
Sign up button disappears when scrolling down

**To Reproduce**
1. Go to 'https://discourse.julialang.org/t/plotting-data-on-a-map-in-julia/4655'
2. Scroll down
4. See that sign up button has disappeared from the navbar

**Expected behaviour**
Sign up button should stay up on the navbar even after scrolling down.

**Screenshots**
![Screenshot from 2022-10-13 13-53-01](https://user-images.githubusercontent.com/87603425/195543014-1731ce39-0567-4291-b85d-2ef72e892c89.png)
![Screenshot from 2022-10-13 13-53-18](https://user-images.githubusercontent.com/87603425/195543083-03a060e5-cc57-4ce1-b6f7-8c931987ce67.png)

**Desktop:**
 - OS: Ubuntu 22.04.1 LTS
 - Browser Brave
 - Version 1.44.105

**Comment by fredrikekre** [comment]
Should report it to https://meta.discourse.org/. But it looks very deliberate and I don't think it is a bug. When you scroll down the post title is moved to the top bar, and I am guessing they chose to remove the sign up button to make room for it.
