### ISSUE TITLE
Non defined variable 

### ISSUE THREAD

**Issue by gitboy16** [JuliaLang/www.julialang.org#1763]
Hi, 

In the following blog:
https://julialang.org/blog/2019/07/multithreading/

The variable `m` is not defined in: 
```julia
temp = temps[Threads.threadid()]
length(temp) < m-lo+1 && resize!(temp, m-lo+1)
copyto!(temp, 1, v, lo, m-lo+1)
```
Could you please update this part and provide fully reproductible code for that part?

Thank you
Kind regards.

**Comment by thazhemadam** [comment]
Yeah, this should be `mid` instead.
