### ISSUE TITLE
Add Julia project timeline/milestones

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1787]
It would be really cool to have a page where it visually shows the timeline for the Julia project over the last 10 years and the significant milestones that have taken place. I am thinking this could live on https://julialang.org/project/ (with a link from the home page). 

I will take a stab at this someone soon (unless someone beats me too it) by using [one of these templates](https://freefrontend.com/css-timelines/).

**Comment by Saksham093** [comment]
Hello @logankilpatrick ... Thank you for the project, this helped to contribute something to Julia lang.  
 

I need your guides to compete it, But I have did this  

![](https://user-images.githubusercontent.com/69385787/217420309-af258ca8-470d-4353-8185-3d9a33b82197.png)

let me know, Is this something you wanted ?, I will make this more beautiful and informative but want kind of information do you want?

**Comment by logankilpatrick** [comment]
This is super cool! A few suggestions: 

- let's have this on its own page (timeline.html), we should only include major releases / milestones. 
- please make sure whatever you are mocking up will work with our site (using Franklin.jl)
- I think major releases and JuliaCons would be a good starting point for content (or other things mentioned in the blog posts on the site) 

We can crowd source more ideas to add

**Comment by logankilpatrick** [comment]
Maybe some nice use of the Julia colors would be helpful too :)

**Comment by patilmanas04** [comment]
Hi @logankilpatrick,

I've completed the Julia Project Timeline feature as requested. You can find my forked branch with the implemented changes at the following link: https://github.com/patilmanas04/www.julialang.org/tree/project-timeline.

Here's a screenshot of the output:
![Julia Project Timeline Screenshot](https://github.com/JuliaLang/www.julialang.org/assets/125283629/2760f5fd-8740-4142-ad55-aba4076f2355)

I have integrated the timeline into the `project.md` page. Please review the changes and let me know if there are any further adjustments or enhancements needed.

Thank you for the opportunity to contribute to JuliaLang!

Best regards,  
Manas Patil
