### ISSUE TITLE
Font is too bold

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/www.julialang.org#18]
![too bold](https://user-images.githubusercontent.com/3131001/43597299-51ee1312-9647-11e8-9bc7-bdff88a5b5e7.png)

The bold font weight pushes letters close together and makes them harder to distinguish. Perhaps "Futura LT Medium" would be a better choice than "Futura LT Bold"?

**Comment by ViralBShah** [comment]
PRs appreciated.

**Comment by ViralBShah** [comment]
@essenciary I often felt that all the bold fonts could be made non bold at least to try things out. Thoughts?
