### ISSUE TITLE
Pluto project page not found

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [JuliaLang/www.julialang.org#1834]
**Describe the bug**
Pluto project page not found in projects idea in [Language interoperability – Summer of Code](https://julialang.org/jsoc/gsoc/interop/#language_interoperability_summer_of_code)

**To Reproduce**
1. Go to https://julialang.org/jsoc/gsoc/interop/
2. Click on `hyper.rs project, listed on the "Pluto" page`
3. See error

**Expected behavior**
to get to pluto project page

**Screenshots**
![image](https://user-images.githubusercontent.com/60783742/218276841-979bb0d5-32b9-4636-89cd-c5a0410c90d9.png)

**Comment by Saksham093** [comment]
The link is updated. 

Keep contributing to Julia ... Thank You
