### ISSUE TITLE
Add dates to old Julia releases

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/www.julialang.org#1850]
The web page <https://julialang.org/downloads/oldreleases/> shows old Julia releases. It would be nice if this table also showed the release dates for these versions.

**Comment by Saksham093** [comment]
##### #1850 : Issue Fixed 

Adding dates manually is blow my mind.

So I added a link, where the release date, changelog, and other information are available.

![](https://user-images.githubusercontent.com/69385787/226208241-7c474abb-bca0-4a61-8d14-8558e895f850.png)

In such a way.  
  
Now, U may close this issue.
