### ISSUE TITLE
403 error on accessing https://julialang-s3.julialang.org/bin/versions.json from GCP

### ISSUE THREAD

**Issue by martinskogholt** [JuliaLang/www.julialang.org#1869]
This issue happens when installing Julia on a cluster in Google Dataproc. We have a Python process that calls a Julia module. If Julia is not installed on the cluster, it is installed via the juliacall package. During the installation, the package tries to access this URL: https://julialang-s3.julialang.org/bin/versions.json to install a specific version, 1.6.7 in our case.

The URL returned a 403 forbidden error the last 2 days. The issue has been seen before: [here](https://github.com/JuliaLang/www.julialang.org/issues/1751)

Expected behaviour
The URL should return a 200 response and not throw a 403 error.

Environment:

Google Dataproc cluster
Image version: 2.0

**Comment by martinskogholt** [comment]
Update: the issue has disappeared, but not sure something was actually changed and as such not sure it will now not re-appear?

**Comment by staticfloat** [comment]
Fons reached out to me and I worked around the problem while we wait for our GCP billing issues to subside.

**Comment by logankilpatrick** [comment]
This has been resolved, some weird transient issues with our Julia credit card.
