### ISSUE TITLE
Map of local communities

### ISSUE THREAD

**Issue by theogf** [JuliaLang/www.julialang.org#1871]
**Is your feature request related to a problem? Please describe.**
It can be tough for new people to find out about their local community

**Describe the solution you'd like**

In the [Community page](https://julialang.org/community/), it would be great to have access to a world map with markers for all the local groups in the world, with links connecting to either their channels, website or something else!

**Describe alternatives you've considered**

We could also have a more plain list.

**Comment by lucaferranti** [comment]
that would be indeed very nice to have.

I did something similar for JuliaReach JuliaIntervals Days 3 (https://juliareach.github.io/juliareach-days-3/#participants).

My approach was pretty barebones, have a json file with all the meetups info and the generate the map with [this javascript](https://github.com/JuliaReach/juliareach-days-3/blob/041d356faca95ec213b23b14815b4aca7c1d96b7/page/_libs/map.js)

The plain list below the map was also automatically generated with [this code](https://github.com/JuliaReach/juliareach-days-3/blob/041d356faca95ec213b23b14815b4aca7c1d96b7/page/_libs/participants.js).

If you like it, I can open a PR
