### ISSUE TITLE
Juliaup rollout

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/www.julialang.org#1922]
I'm starting to think through all the necessary changes we need to do to make Juliaup the official way to install Julia, and an important part is the homepage and documentation. 

Roughly, here is what I would suggest:
1. We [add](https://github.com/JuliaLang/julia/pull/50477) two new sections to the Julia manual: "Installation" and "Juliaup". The first one describes in detail all the installation options we have, the second one documents all the ins-and-outs of Juliaup.
2. We add a top level "Get Started" section to the Julia home page, https://julialang.org/get-started/.
3. We model that page after https://www.rust-lang.org/learn/get-started, i.e. the first part is a platform specific install instructions (short and sweet) with a link to the comprehensive installation instructions in the manual. So, this would display differently depending on which platform one opens that page. I think down the road we could also add suggestions about editors etc, but maybe for starters it could really just be "Do X to install" and then "Read the Getting Started section in the manual" with a link.
4. We replace the "Downloads" top level navigation element on the home page with a link to the new "Get Started" page.
5. On the homepage, we also replace the green "Download" link with one to the "Get Started" page.
6. We _keep_ the https://julialang.org/downloads/ page alive, though, essentially in its current form, but we just deemphasize it. I'm not entirely sure from which pages we would link to it, maybe still from the "Getting Started" page? But essentially at the top we would have text along the lines of "This page has an archive of downloads, to install Julia on a system please follow the instructions on the Get Started page".
7. We (well, I) write a blog post that announces this change.

Thoughts? Does that make sense?

If someone wants to help with making these changes it would be great!

**Comment by ExpandingMan** [comment]
We've been having a long conversation about this on slack spurred by a new user who, entirely justifiably, got confused largely over broken and out of date Julia linux distro packages.  I think it would be very beneficial to do something along the lines of what @davidanthoff is suggesting.

In my experience, most of the relatively new programming languages are in the same boat as Julia, having patched dependencies that make the build process less than straightforward for package managers.  Rust, which has already been mentioned, also has [an install page](https://www.rust-lang.org/tools/install) which prominently mentions rustup.  Haskell, in which the recommended install method is `ghcup`, [is similar](https://www.haskell.org/downloads/).

**Comment by hoegge** [comment]
As "the new user", I think it makes a lot of sense. Neither installing Julia from Pop_OS! shop nor the default Windows 64 bit download worked with the VS Code plugin (still have to see if Juliaup also solves it on Windows - did on Linux). 
And I know from, e.g., TypeScript that a version manager just makes life so much easier for users, and would be great to advice user to use Juliaup from the beginning and avoid a complete stall at first install.

**Comment by cpfiffer** [comment]
I actually came here to see if there was an issue already to suggest just this! I am 10000% for this. Juliaup is great and we should have the little 

```
curl -fsSL https://install.julialang.org | sh
```

as accessible as possible (and the separate Windows command right next to it).

**Comment by fingolfin** [comment]
I would also make sure https://julialang.org/downloads/ at the top points out that simple install instructions can be found at SOMELINK and that direct download is for people who have specific needs and essentially know what they are doing.

**Comment by fingolfin** [comment]
Also, don't forget about https://julialang.org/downloads/platform/

**Comment by IanButterworth** [comment]
https://github.com/JuliaLang/www.julialang.org/pull/1969 has been merged so we should move forward on the other tasks above
