### ISSUE TITLE
Reconsider ARMv8 for tier 1, and e.g. possibly drop ARMv7

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/www.julialang.org#1924]
ARMv8 was recently upgraded to tier 1 for MacOS, i.e. Apple silicon. Was it simply an oversight to not upgrade ARMv8 for Linux too?

Apple has the same ARM arch, or actually a superset of it, so all the work done for it should have helped Linux too. Some work is specific to the OS though, so I'm not confident it's an oversight.

I would like ARMv8 promoted (for e.g. Raspberry Pi) if it was simply an oversight.

If it's known buggy/i.e. in Julia 1.6, I would consider dropping it from the download page, for that version. We don't really want to mislead people into thinking it work, or worse has long term support. For those few (or any) that have downloaded LTS ARMv7 dropping it from the download page wouldn't explicitly mean it's no longer supported for them.

I would actually like older Pi also supported but I believe it's ARMv6 not ARMv7, so it has no support tier. Possibly it should be listed with at least tier 2? I know people use it. I'm not sure if people just need to compile it from source, it would be friendly to provide a download link for it, even with no explicit support, or tier 3, and a big caveat about it? [No CI, may need to cross-compile, working directly on it in the REPL may be awful.]

Is it very valuable by now to support ARMv7? Many non-Pi similar systems support it, but most all ARMv8 anyway? Many microcontrolles are limited to ARMv7, but actually to Thumb we do not support (yet?). My only hesitation with dropping ARMv7 from LTS, is that we then have no download link for it for any version, but that could be fixed by providing one for 1.9.

**Comment by giordano** [comment]
> Was it simply an oversight to not upgrade ARMv8 for Linux too?

[No](https://github.com/JuliaCI/julia-buildkite/issues/231)

**Comment by ViralBShah** [comment]
We can't just drop released binaries and architectures from the downloads page, which can be disruptive to those who did use them. We can always discontinue architectures in future releases.
