### ISSUE TITLE
Book proposal: "Julia com Física: Uma introdução" in Portuguese for high school

### ISSUE THREAD

**Issue by adeil83** [JuliaLang/www.julialang.org#1944]
Hi, 

If possible, please consider adding the following free e-book to julialang.org/learning/books/:

Best regards,

Link for download:

https://www.seduc.ce.gov.br/wp-content/uploads/sites/37/2023/09/Ebook-02-Julia-com-Fisica.pdf

Adeil Araújo and Meirivâni Oliveira, ["Julia with Physics: An Introduction" in Portuguese](https://www.seduc.ce.gov.br/wp-content/uploads/sites/37/2023/09/Ebook-02-Julia-com-Fisica.pdf), Seduc - CE, September 2023.

**Comment by LilithHafner** [comment]
I believe this entry is present

<img width="1094" alt="Screenshot 2023-12-09 at 12 28 25 PM" src="https://github.com/JuliaLang/www.julialang.org/assets/60898866/65f46e93-e5fa-4c4d-b92e-bbd788c73d63">
