### ISSUE TITLE
Book proposal (Romeo and Julia)

### ISSUE THREAD

**Issue by b-lukaszuk** [JuliaLang/www.julialang.org#1995]
Please add a book (https://b-lukaszuk.github.io/RJ_BS_eng/) entitled: "Romeo and Julia, where Romeo is Basic Statistics" to list of books at: https://julialang.org/learning/books/

**Comment by ViralBShah** [comment]
Please submit a PR.

**Comment by b-lukaszuk** [comment]
Thanks for your suggestion. I did this (hopefully correctly) in [PR #2032](https://github.com/JuliaLang/www.julialang.org/pull/2032)

**Comment by b-lukaszuk** [comment]
[PR #2032](https://github.com/JuliaLang/www.julialang.org/pull/2032) was successfully merged by @ViralBShah (thanks) so I close the issue.
