### ISSUE TITLE
Inconsistency about `--gcthreads` arguments

### ISSUE THREAD

**Issue by prbzrg** [JuliaLang/www.julialang.org#1997]
mention of `--gcthreads=M,1` (second number) in the v1.10 blog post doesn't exist in either [command-line page of docs](https://docs.julialang.org/en/v1/manual/command-line-interface/) or [manpage of julia](https://github.com/JuliaLang/julia/blob/v1.10.0/doc/man/julia.1).

**Comment by KristofferC** [comment]
cc @d-netto
