### ISSUE TITLE
Quick-moving Visualization image distracts from the rest of the page

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/www.julialang.org#20]
When I navigate to the page my eyes immediately skip all the content to look at the moving visualization. Perhaps it shouldn't be the default tab? Or it could be further down the page?

**Comment by ViralBShah** [comment]
That is the idea! Just joking.

**Comment by iamed2** [comment]
1440p, which lies between 1080p and 2160p. Since it only happens at that size/resolution maybe it's fine to leave as is :)
