### ISSUE TITLE
Docs Version Switcher

### ISSUE THREAD

**Issue by arnavs** [JuliaLang/www.julialang.org#204]
Per Slack. If I'm on a particular docs page, it would be great if the version switcher under the Julia icon would take me to that version's instance of the page I'm on, as opposed to sending me back to home. For ex., if I googled "Julia filesystem" and it took me to the 0.6 page, I could use that button to quickly flip to the 1.0 one.

**Comment by fredrikekre** [comment]
This issue is perhaps more suited for Documenter.jl. Im general this is not possible since we don't know that the same page exists for the other versions, but maybe one can guess and fallback to the homepage.

**Comment by arnavs** [comment]
Right, that's the kind of behavior I had in mind. Sure, we can have an issue there and link it to this one (this specific use case is worth tracking, IMO).

**Comment by KristofferC** [comment]
Closing since this is a Documenter.jl issje.
