### ISSUE TITLE
Adding a Julia tutorial for Python users

### ISSUE THREAD

**Issue by EssamWisam** [JuliaLang/www.julialang.org#2059]
**Is your feature request related to a problem? Please describe.**
Many Python users would wish to learn Julia but are faced with many tutorials that teach the language as if they haven't programmed before or that don't make use of the fact that they already know Python.

**Describe the solution you'd like**
I wrote two articles some time ago to solve this. The [first one](https://towardsdatascience.com/embracing-julia-an-invitation-letter-332f5709378e) is motivation for to learn Julia and the [second](https://python.plainenglish.io/from-python-to-julia-an-ultimate-guide-244fd3dc35c6) is an actual migration guide from Python to Julia with some emphasis on data science.

**Additional context**
I am interested in having the migration guide or both articles to show up in the [Julia tutorials page](https://julialang.org/learning/tutorials/). Any feedback is welcome as well.

**Comment by ViralBShah** [comment]
This is a bit open ended - while it would be nice to have these tutorials, this issue is not the place for it. Perhaps a good conversation for discourse.
