### ISSUE TITLE
Link to another site should open in new tab

### ISSUE THREAD

**Issue by shravanngoswamii** [JuliaLang/www.julialang.org#2088]
Any link that takes the user to a site other than [julialang.org](https://julialang.org) should open in a new tab!! Just a suggestion, if you find it good then we can start working on it!!

**Comment by StefanKarpinski** [comment]
I was under the impression that this is an antipattern in website design. But I'm not a web designer.

**Comment by shravanngoswamii** [comment]
Well, I read some articles just now about this and this thing is a debate on the Internet!! What I think is any link that keeps the user on the same site should open in the same tab and if the link takes the user to another site then it should open in a new tab, just to avoid distractions!!

**Comment by StefanKarpinski** [comment]
Thanks for raising the question!
