### ISSUE TITLE
Update minimum OS Versions

### ISSUE THREAD

**Issue by Zentrik** [JuliaLang/www.julialang.org#2092]
I assume the min glibc version needs to be updated, no idea to what though.
Cuda.jl readme says they support cuda 11+ so that's need updating.
Not sure about freebsd.

Edit: I got confused and assumed the minimum OS requirement referred to glibc and not the kernel version.
Also, looks like binarybuilder uses 13.2 so that's probs fine.

**Comment by giordano** [comment]
The minimum glibc version we target is architecture-dependent, the overall minimum number is 2.17: https://github.com/JuliaPackaging/Yggdrasil/blob/fb09bc7f78ee002fcb08b6313f2f451499111e7c/RootFS.md#glibc-versions
