### ISSUE TITLE
New "Julia in the classroom" course

### ISSUE THREAD

**Issue by fsancho** [JuliaLang/www.julialang.org#2101]
Universidad de Sevilla (Spain), E.T.S.Ingeniería Informática:

[IAIC-2023](https://www.cs.us.es/cursos/iaic-2023/), Inteligencia Artificial (Prof. Fernando Sancho Caparrini) Fall-2023

**Comment by LilithHafner** [comment]
I'd be happy to merge a PR adding that course (provided Julia is used in it)

**Comment by fsancho** [comment]
> I'd be happy to merge a PR adding that course (provided Julia is used in it)

The course content is fully available at the URL provided, and all labs and examples are programmed in Julia (directly, or using official packages).
I do not know if any additional verification of the use of Julia is needed. Please, let me know.

**Comment by LilithHafner** [comment]
Great! Yes, that's more than enough verification that Julia is used. Feel free to make a PR to the website. There's an edit button on the bottom right

![Screenshot from 2024-05-26 11-33-01](https://github.com/JuliaLang/www.julialang.org/assets/60898866/06f5eec1-9fb0-477b-a099-f60bcf3c4e89)

**Comment by fsancho** [comment]
Thanks for all the great work!!!

**Comment by LilithHafner** [comment]
I didn't add the course; someone (e.g. you, or anyone else reading this) still has to do that for the website to update.

I'm happy to merge a PR, but don't have the capacity/enthusiasm as a volunteer to make the PR myself.

**Comment by cakiki** [comment]
@LilithHafner I've gone ahead and created the PR
