### ISSUE TITLE
Site didn't publish even though CI passing

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/www.julialang.org#2125]
Before https://github.com/JuliaLang/www.julialang.org/pull/2123 since the PR that introduced the formatting error the site wasn't publishing even though CI was green.

**Comment by giordano** [comment]
I see deployment being successful at https://github.com/JuliaLang/www.julialang.org/actions/workflows/pages/pages-build-deployment?query=branch%3Agh-pages for most of the previous commits.

**Comment by IanButterworth** [comment]
I think https://github.com/JuliaLang/www.julialang.org/pull/2126 is the same fix JuliaCon.org needed, right?

**Comment by IanButterworth** [comment]
That didn't seem to error when the fix was reverted. It must've been a hosting issue coincidence.
