### ISSUE TITLE
Recent blog posts shows "nothing" for the blog post content

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#2144]
<img width="1154" alt="Screenshot 2024-09-13 at 10 37 30 AM" src="https://github.com/user-attachments/assets/cb68e998-c8fc-4deb-8be8-ac474dc1134f">

**Comment by cormullion** [comment]
I think this error was introduced in the update of July 23rd: 

https://github.com/JuliaLang/www.julialang.org/commit/9abba82e824f69dc2e231fb157c292d94deb0007#diff-77f6106b330f94b72767e939c4331f770846d06af4f97415d941b404087155daR65

where this code was added.

```julia

     # Franklin.pagevar appears to be an internal function that has a guard against
      # recursive overflow so we need to reset the counter to 0, otherwise we cannot read
      # pagevars for all pages.
      Franklin.PAGEVAR_DEPTH[] = 0
      title = pagevar(surl, :title; default="Untitled")
```

However my Franklin's a bit too rusty/basic for fixing this - perhaps we could get Thibaut to have a look...?

Also, there's an error in the footer:

![Image](https://github.com/user-attachments/assets/5495497f-2c86-42e4-80a7-262316e031ee)

which looks to have been added [here]
(https://github.com/JuliaLang/www.julialang.org/commit/c703e344a08fd55409ada99ff07f1cc9f4da04c6#diff-9fbced659a9c3a69fa276f1cc07a1f91d229c07f69980c786b5c1a2d9b5be3f5R47)

 (by @IanButterworth I think). I don't know where this is defined though.

**Comment by IanButterworth** [comment]
I'll look into this.

**Comment by cormullion** [comment]
> However my Franklin's a bit too rusty/basic for fixing this - perhaps we could get Thibaut to have a look...?

Perhaps this is where we’d insert `@delay` as mentioned here:

https://github.com/tlienart/Franklin.jl/issues/924#issuecomment-965736656

**Comment by cormullion** [comment]
@IanButterworth Thanks! (And sorry for finding more work for you 😀)

**Comment by cormullion** [comment]
![Image](https://github.com/user-attachments/assets/2147c09a-a503-49fe-88a9-386122453055)

**Comment by giordano** [comment]
That's #2136
