### ISSUE TITLE
Re-enable GSoC tab

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/www.julialang.org#224]
Eager students are already looking for projects and emailing. We need to get the tab for GSoC re-enabled.

**Comment by ChrisRackauckas** [comment]
It seems the templates for the re-added GSoC pages need to be updated. I tried just changing the template in https://github.com/JuliaLang/www.julialang.org/pull/226 , but reverted that change because it seemed to make it worse https://github.com/JuliaLang/www.julialang.org/pull/228 . @ViralBShah mentioned I should ping @essenciary for help.

**Comment by ViralBShah** [comment]
Or even @shashi if he knows how to fix.

**Comment by essenciary** [comment]
I bit busy these days but I'll take a look.

**Comment by ViralBShah** [comment]
This looks fixed.
