### ISSUE TITLE
Show only one video

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#238]
I think that showing 3 videos is not quite working, since you can't see what the video is about.

What we need is to show only one random video, which is much larger, and can be played right within the page.

@shashi Is this something you can help with?

**Comment by essenciary** [comment]
Super swamped with work and study these weeks, but I've added it to my list, I'll look into it ASAP.

**Comment by essenciary** [comment]
Pushed updates for both issues - however, the website is not updated yet... Anything required to trigger the build?

**Comment by essenciary** [comment]
Nevermind, it finally updated!

**Comment by ViralBShah** [comment]
Propagating to cdn takes time. Throw in `?x` at the end of url to force loading updated page
