### ISSUE TITLE
footermenu - "Ecosystem Pulse" - Last updated 2018-08-04 

### ISSUE THREAD

**Issue by ImreSamu** [JuliaLang/www.julialang.org#246]
Website ( https://julialang.org/ )   general  **footermenu** contains a link to **"Ecosystem Pulse"** - https://pkg.julialang.org/pulse.html
![julia_peek 2018-12-07 17-57](https://user-images.githubusercontent.com/2217320/49661575-b6216a80-fa49-11e8-9344-2561c46ba65c.gif)

And it is "*Last updated 2018-08-04*"  ( Today 2018-12-07! )

![screenshot from 2018-12-07 18-00-20](https://user-images.githubusercontent.com/2217320/49661699-17e1d480-fa4a-11e8-8f9d-ea4b4bf62b6f.png)

imho: If nobody fixes it - it would be better to remove the link.

___
( context: [discourse.julialang.org](https://discourse.julialang.org/t/julialang-org-website-footermenu-ecosystem-pulse-last-updated-2018-08-04/18285)  )

**Comment by ViralBShah** [comment]
Yes, we should just remove that link and find something else to mention there. Or remove that whole column.

**Comment by ImreSamu** [comment]
Done: https://github.com/JuliaLang/www.julialang.org/pull/249
