### ISSUE TITLE
Download mirrors

### ISSUE THREAD

**Issue by essenciary** [JuliaLang/www.julialang.org#250]
I noticed that downloading Julia is slow-ish, from Spain. It's probably the same for all non-US downloads. It's not critical but it would be nice to speed things up, I guess. Maybe a university could host the files somewhere in Europe, Asia, etc - if anybody can help with that? I can also take a look maybe there's a free CDN we could use? Might save on bandwidth costs as well, if that's a problem. Thoughts?

**Comment by ViralBShah** [comment]
We are already using Fastly as the CDN.

**Comment by essenciary** [comment]
Ah, OK, then bandwidth is not a problem. So they don't have servers in Europe? My download comes through Seattle. 

```
traceroute to julialang-s3.julialang.org (151.101.54.49), 64 hops max, 52 byte packets
 1  192.168.1.1 (192.168.1.1)  3.255 ms  2.629 ms  2.991 ms
 2  210.red-81-46-38.customer.static.ccgg.telefonica.net (81.46.38.210)  7.103 ms  12.094 ms  13.086 ms
 3  193.red-81-46-44.customer.static.ccgg.telefonica.net (81.46.44.193)  12.240 ms  8.227 ms  7.948 ms
 4  * * *
 5  209.red-80-58-77.staticip.rima-tde.net (80.58.77.209)  6.902 ms  20.072 ms  13.012 ms
 6  et-4-0-0-400-grtbcnes1.net.telefonicaglobalsolutions.com (213.140.50.244)  12.983 ms  7.564 ms  7.299 ms
 7  176.52.248.95 (176.52.248.95)  48.378 ms  43.788 ms
    94.142.127.159 (94.142.127.159)  34.511 ms
 8  4.68.72.161 (4.68.72.161)  41.764 ms  46.834 ms  43.286 ms
 9  ae-2-3613.edge1.seattle3.level3.net (4.69.160.73)  188.520 ms  198.474 ms  184.543 ms
```

**Comment by ViralBShah** [comment]
I see european servers on the cdn, but most of the traffic does seem to get served out of the US.

@staticfloat may know better.

**Comment by staticfloat** [comment]
Hahahahahaha, okay this one gave me a good chuckle.  I believe this is because our DNS entry for the fastly cache was set to the IP address that I looked up while in Seattle, but should instead be a CNAME that points to a fastly DNS entry that auto-selects.  I've put in a request to have the DNS changed.

**Comment by ViralBShah** [comment]
A NEWS item for Julia 1.0.3: Faster downloads!

**Comment by ViralBShah** [comment]
@staticfloat Did the DNS change get carried out?

**Comment by staticfloat** [comment]
DNS change has been carried out, give it an hour or two to propagate and this should be fixed.  @essenciary can you verify that our `julia*-s3` domains should be serving from global locations now?

**Comment by essenciary** [comment]
The traceroute is different and much faster so it looks like it worked

```
traceroute to dualstack.j2.shared.global.fastly.net (151.101.134.49), 64 hops max, 52 byte packets
 1  192.168.1.1 (192.168.1.1)  4.469 ms  2.870 ms  2.848 ms
 2  210.red-81-46-38.customer.static.ccgg.telefonica.net (81.46.38.210)  4.037 ms  4.947 ms  4.019 ms
 3  193.red-81-46-44.customer.static.ccgg.telefonica.net (81.46.44.193)  13.651 ms  14.984 ms  13.844 ms
 4  29.red-81-46-45.customer.static.ccgg.telefonica.net (81.46.45.29)  14.934 ms  14.462 ms  15.039 ms
 5  1.red-80-58-106.staticip.rima-tde.net (80.58.106.1)  14.229 ms  15.600 ms  15.841 ms
 6  46.red-81-46-0.customer.static.ccgg.telefonica.net (81.46.0.46)  17.209 ms  16.234 ms  14.471 ms
 7  18.red-81-46-3.customer.static.ccgg.telefonica.net (81.46.3.18)  13.962 ms  14.234 ms  14.618 ms
 8  225.red-81-46-7.customer.static.ccgg.telefonica.net (81.46.7.225)  14.801 ms  14.977 ms  14.951 ms
 9  ae0-400-grtmadno2.net.telefonicaglobalsolutions.com (213.140.51.56)  14.820 ms  17.202 ms  20.560 ms
10  5.53.7.225 (5.53.7.225)  15.038 ms  14.826 ms  13.578 ms
```
