### ISSUE TITLE
Linux generic-binary installation instructions are confusing

### ISSUE THREAD

**Issue by natschil** [JuliaLang/www.julialang.org#255]
The current linux generic binary installation instructions give the example of how to link /usr/local/bin/julia to /bin/julia. This is weird as nobody downloads julia to /usr/local/, and also confusing as the next line then says talks about /usr/local/bin maybe not being in a user's $PATH. 

Is it enough to link <Downloaded_folder>/bin/julia to /usr/bin/julia, or is it necessary to also link to the lib/ folders? Perhaps instead of telling people how `ln -s` works in general is to provide a list of commands that will work on ubuntu/fedora and to assume everyone using something more exotic knows what they are doing anyways?

**Comment by ViralBShah** [comment]
Just sufficient to link the binary and nothing else.

**Comment by ViralBShah** [comment]
Submit a PR? What you say sounds right.

**Comment by natschil** [comment]
#262
