### ISSUE TITLE
broken blog formatting

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#301]
Anyone knows how to fix?

![52188944-88517a00-2870-11e9-9620-ff57b56230a7](https://user-images.githubusercontent.com/744411/52190423-05e39e80-280d-11e9-908f-c1d568a53472.png)

**Comment by essenciary** [comment]
@ViralBShah Something is broken in these posts: 

Error: YAML Exception reading /Users/adrian/Dropbox/Projects/julialang/website/staging.julialang.org/blog/_posts/2018-08-08-one-point-zero-zh_cn.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 2
             Error: YAML Exception reading /Users/adrian/Dropbox/Projects/julialang/website/staging.julialang.org/blog/_posts/2018-08-08-one-point-zero-es.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 2
             Error: YAML Exception reading /Users/adrian/Dropbox/Projects/julialang/website/staging.julialang.org/blog/_posts/2018-08-08-one-point-zero-zh_tw.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 2

Removing these on localhost fixed the problem.

**Comment by ViralBShah** [comment]
That is me.

**Comment by ViralBShah** [comment]
Thank you @essenciary

**Comment by essenciary** [comment]
You're welcome @ViralBShah
