### ISSUE TITLE
Add slow initiation section/warning to Downloads/Plotting.html

### ISSUE THREAD

**Issue by cosama** [JuliaLang/www.julialang.org#305]
Importing `Plots` and the first call to the `plot` function usually takes a bit of time (20-30 seconds). This has been discussed in issue https://github.com/JuliaPlots/Plots.jl/issues/917.

https://julialang.org/downloads/plotting.html is most likely the first resource most people new to Julia and interested in plotting will seek out. I think it would be important to add a section discussing this (or a warning) to that page and add some resources that help to adopt a more julia like workflow that reduces the impact of this. Maybe https://docs.julialang.org/en/v1/manual/workflow-tips/index.html could be a start, but I'm sure there are even better articles about that.

**Comment by ViralBShah** [comment]
Maybe submit a PR that sweet the right expectation on first use?

**Comment by ViralBShah** [comment]
There have been significant improvements on this front, and it is a topic of further ongoing improvements.
