### ISSUE TITLE
Big List of GithubOrgs, links to chats etc

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/www.julialang.org#34]
New site is pretty.

Not quiet 100% of information from
https://github.com/JuliaLang/www_old.julialang.org/blob/master/ecosystems/index.md
has made it across.

For example that big list had links to all the Chatrooms, forums, facebooks, etc etc  for all the localization efforts.
New localization page only links to github orgs, or websites.
Most of those websites do then have links to the other communication channels so maybe that is OK.
On the other hand @ViralBShah's [comment here](https://discourse.julialang.org/t/chinese-discourse-is-set-up/12829/2?u=oxinabox)
about making a PR to this repo, to link to the Chinese discourse, is not possible.
(or at least would look out of place without the others.)

The other thing the ecosystems page had was a big list of all the orgs,
and all there chat rooms etc.
Some of that has made it into the new ecosystems pages.
But not all of it.

The github orgs are a big way of guiding people to packages -- it is a proxy for stability and compatibility.
Having that would help address this concern [raised on discourse](https://discourse.julialang.org/t/new-website/12844/4?u=oxinabox)

On the other hand the orgs list does become out-dated, chatrooms can become disused etc.
And the huge list is huge.

I still think it has some value that we want preserve.

Maybe there could be a "More Info" link behind the new fancy pretty ecosystems page?

**Comment by ViralBShah** [comment]
I think the old site was snapshotted a while back to work on the new version, and this happened after that. 

We should definitely bring it back in some form.

**Comment by ViralBShah** [comment]
I feel like hiding it behind `More Info` is not ideal. Let's think about a good way of presenting the information in a naturally discoverable way. Otherwise, the people who need to - the new users - just won't see it.

**Comment by oxinabox** [comment]
Not quiet closed by #70.
Links to all the localisation efforts chats still need to be readded

**Comment by ViralBShah** [comment]
I am pretty sure we decided to not carry the full list of everything at some point.
