### ISSUE TITLE
Add Makie.jl to list of plotting packages

### ISSUE THREAD

**Issue by asinghvi17** [JuliaLang/www.julialang.org#359]
Once Makie reaches a 1.0 state (which is still a bit far away), should we add it to the plotting section as well?

It would be nice if we could highlight the extremely interactive nature of Makie there.  There are a bunch of cool examples in JuliaPlots/MakieGallery.jl that could be drawn upon, and that level of interactivity without too much overhead isn't something I've seen too often in plotting packages (most of which seem to be geared to static plots).

**Comment by ViralBShah** [comment]
Sure. Can be added any time as long as the API is reasonably stable and the package is easy to install. cc @SimonDanisch

**Comment by ViralBShah** [comment]
Please make a PR.
