### ISSUE TITLE
Download link for AArch64 Linux for 1.1 is broken

### ISSUE THREAD

**Issue by Tidinho90** [JuliaLang/www.julialang.org#370]
It links to nothing.
The behaviour is the same for the GPG key.

**Comment by ViralBShah** [comment]
@staticfloat @ararslan ?

**Comment by staticfloat** [comment]
Fixed.  Some files got copied into the wrong folder.

**Comment by ararslan** [comment]
My bad. Thanks for fixing it, Elliot.
