### ISSUE TITLE
Broken links on blog page

### ISSUE THREAD

**Issue by non-Jedi** [JuliaLang/www.julialang.org#373]
As far as I can tell, all of the links on https://julialang.org/blog/ are broken. For example: https://julialang.org/blog/2019/05/beyond-ml-pipelines-with-mlj/ gives a 404.

**Comment by ViralBShah** [comment]
It was working just an hour ago. Perhaps a github outage?

**Comment by ViralBShah** [comment]
As per https://www.githubstatus.com/ Github Pages is facing degraded performance.

**Comment by ViralBShah** [comment]
Seems fixed.

**Comment by non-Jedi** [comment]
https://julialang.org/blog/2019/05/beyond-ml-pipelines-with-mlj/ continues to show 404 for me.

**Comment by ViralBShah** [comment]
Try again?

**Comment by ViralBShah** [comment]
github status says it is fixed now, and it does work for me.

**Comment by non-Jedi** [comment]
Nope. Still broken.

**Comment by ViralBShah** [comment]
Definitely working for me. Anyways, nothing we can do. Hopefully it stabilizes soon.

**Comment by ViralBShah** [comment]
Maybe geography specific with the CDN and such?

**Comment by non-Jedi** [comment]
So here's the meat of the issue I think: https://julialang.org/blog/2019/05/beyond-ml-pipelines-with-mlj works as a link, but https://julialang.org/blog/2019/05/beyond-ml-pipelines-with-mlj/ gives the 404 page. Last week, https://julialang.org/blog/ had links with the trailing backslash, but today it seems to omit the trailing backslash, and everything is peachy. Not sure what changed.
