### ISSUE TITLE
Various spelling mistakes

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/www.julialang.org#39]
in the technical section(languagefeatures.html) it reads "natrual" instead of "natural"

edit: i also found these:
in the packages section theres "the the"

**Comment by rapus95** [comment]
@ViralBShah
did you see my edit?
is it preferable to have a single spelling mistakes issue rather than a whole bunch of single issues?

**Comment by ViralBShah** [comment]
Maybe just point out all the spelling issues here.

**Comment by ViralBShah** [comment]
Also instead of mentioning here, can you edit them directly? You can do so on github.

**Comment by ViralBShah** [comment]
Don't worry about commit messages. Just leave them blank (default).

**Comment by ViralBShah** [comment]
Also which edit?

**Comment by ViralBShah** [comment]
I see the edit. BTW, add new stuff below rather than editing OP.
