### ISSUE TITLE
can we get a Gemfile that actually works?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/www.julialang.org#439]
It used to be straightforward to install jekyll and run a local copy of this website. But for years now, I've been unable to test locally that it works or looks right. Every time I try to use the Gemfile, this is what I get:
```
Invalid gemspec in [Gemfile]: undefined method `source' for Gem::Specification:Class
ERROR:  Error loading gemspec. Aborting.
```
Is this brokenness permanent, or can something be done about it?

**Comment by vtjnash** [comment]
I've never seen that.

**Comment by StefanKarpinski** [comment]
Closing as hopeless. Probably equivalent to fixing Ruby's package manager, which isn't my problem.

**Comment by vtjnash** [comment]
Perhaps just the wrong version of ruby? I currently use ruby2.6 from MacPorts and Ubuntu system ruby (2.5.1p57). Also new attempts at instructions: https://github.com/JuliaLang/www.julialang.org/pull/475 (since nothing I've written before seems to work twice.)

**Comment by StefanKarpinski** [comment]
I'm using ruby 2.6.3p62 from brew, so that shouldn't be too different if their versions are sane.
