### ISSUE TITLE
Redirect julialang.org/download to julialang.org/downloads

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/www.julialang.org#445]
Redirect julialang.org/download to julialang.org/downloads. Maybe it would also be nice with download.julialang.org?

**Comment by ViralBShah** [comment]
Any particular reason for the redirect? How about `downloads.julialang.org`? Have to do this carefully, because otherwise it can affect the search engine rankings.

**Comment by fredrikekre** [comment]
> Any particular reason for the redirect?

Because I keep going to julialang.org/download and either getting annoyed that I got it wrong or I think that the page is down.

> How about downloads.julialang.org?

Yea, IDK, maybe skip the download.julialang.org idea.

**Comment by ViralBShah** [comment]
Makes sense. I think the right way to do it is a 302 redirect.

**Comment by aviks** [comment]
I believe this should be possible to do in jekyll via a yaml header on the existing `/downloads` page.

**Comment by abhishalya** [comment]
This issue needs an update I guess. @logankilpatrick

**Comment by logankilpatrick** [comment]
Why?

**Comment by abhishalya** [comment]
Wasn't a PR merged solving this? The comments on the merged PR should be used to update this issue imo.

**Comment by logankilpatrick** [comment]
PR was merged but the issue persists.

**Comment by ViralBShah** [comment]
Attempted fix in #528 but while it worked on netlify, it doesn't work on the actual website.

**Comment by ViralBShah** [comment]
Fixed in #535 Thanks @fungktt
