### ISSUE TITLE
Learning page is broken

### ISSUE THREAD

**Issue by hossein-pourbozorg** [JuliaLang/www.julialang.org#448]
![Screenshot from 2019-09-09 17-21-54](https://user-images.githubusercontent.com/19240961/64532388-9e537b80-d326-11e9-916b-608a8ea18a34.png)

https://github.com/JuliaLang/www.julialang.org/blob/3389943a7c5af9f3c10b989109d925ebe7b46fa3/learning/index.html#L1

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/www.julialang.org/commit/3389943a7c5af9f3c10b989109d925ebe7b46fa3

cc @ViralBShah

**Comment by ViralBShah** [comment]
There are some issues with key bindings and emacs on my new keyboard... Sorry about this.
