### ISSUE TITLE
Package is available on dnf Fedora

### ISSUE THREAD

**Issue by chauhankiran** [JuliaLang/www.julialang.org#452]
A few days ago, I install Julia with the following command without configuring Copr. and I was able to successfully install the Julia on my Fedora Xfce machine 30. So, can we update this [Platform Specific Installation](https://julialang.org/downloads/platform.html) page with direct installation steps instead of providing a way to configure Copr.? Just simple command to install Julia -

```bash
$ sudo dnf install julia
```

**Comment by ViralBShah** [comment]
Could you submit a PR?

**Comment by nalimilan** [comment]
Actually, you need to enable the Copr if you want the latest version (1.2), as the official Fedora version won't change to ensure stability (except for patch releases). So the current instructions are correct.
