### ISSUE TITLE
Gender diversity notes

### ISSUE THREAD

**Issue by nassarhuda** [JuliaLang/www.julialang.org#455]
On September 12, 2019, Viral Shah posted to on the Julia Slack diversity channel some numbers about gender representation in people who access the julialang.org website. 

![Screen Shot 2019-09-18 at 5 36 07 PM](https://user-images.githubusercontent.com/12686504/65200104-e9fad900-da3a-11e9-8d1a-3b2cddc3d48b.png)

This sparked a series of suggestions and ideas to increase  diversity in the Julia community. Viral and I had already chatted about other ideas prior to the Slack conversation and below, I summarize the slack ideas + others in the form of action items.

Some notes first:

- Some of these ideas are to be implemented on the short term, and others on the long term.
- Some of these ideas require financial support and others require labor support (i.e. people in the community picking up an action item and acting on it.)
- I will create a follow up post to this post with a timeline of when should each item occur and how it's being handled.
- Anyone can be involved in this effort! So please feel free to comment, participate in the conversation, and suggest new ideas.

### Creating accessible material
- Submit workshop proposals _in force_ to places like the Grace Hopper Celebration (Quoting Nathan Daly: " If we show up with like 10 Julia proposals, and do both of the above [sponsor and recruit -- see below], it seems hard to conclude Julia is irrelevant", and reach out to Women in Data Science to see if they can give us a slot on the day before or the day after their event to give a Julia workshop.
- Create more youtube videos and place them online -- something similar to what Jane Herriman had done in the past (videos about different topics on the Julia language youtube channel).
- Create more teaching material via small anecdotal examples. The example that comes to mind is this example when someone wrote a blog post about the Santa gift matching problem (match gifts to kids) [link here](https://opensourc.es/blog/hungarian-method). This person used Julia and provided their code. These also need to be linked to in one place (something easy to find like the videos in the youtube channel).
- Create an online Julia course. Or possibly, something like Data Science in Julia. And get this learning material onto places like EDX/Coursera/etc...
### Surveying and understanding our audience better
- Create and publish a survey to understand whether non julia users seem to be turned away from using Julia due to the name, or does an opposite impact happen, or is it neutral? There was one note on the slack discussion (my own) that suggested that younger girls seem to be _curious_ about julia due to the name/logo. Another note showed that the person asked was indifferent about the name. If the hypothesis that Julia is appealing to a younger generation of girls due to the name is correct, we should take this as an advantage and act on it.
### General outreach and visibility
- Invite Julia-affiliate organizations to sponsor events such as the Grace Hopper Celebration [GHC](https://ghc.anitab.org/), Women in Data Science [WiDS](widsconference.org), Women in Machine Learning [WiML](https://wimlworkshop.org/), [data4blacklives](http://d4bl.org/), [black is tech](http://blackistechconference.com/), [Lesbians who tech](https://lesbianswhotech.org/newyork2019/), [Out in STEM](https://www.ostem.org/). Examples of Julia-affiliate organizations are organizations that are regular sponsors of JuliaCon (e.g. Julia Computing, Invenia, RelationalAI, and others). As part of sponsoring such events, there is often an opportunity to address the audience or possibly deliver a Julia workshop, which should be, quoting August Guang: "given by folks from those communities". 
### Recruitment
- Attend events such as GHC, WiDS, or WiML and _recruit_ women in computing, data science, or machine learning. Quoting Nathan Daly here: "we [RelationalAI] are planning on interviewing and recruiting for an intern and possibly a new-grad from GHC 2020. It would be great to have Julia Computing do the same." Quoting August Guang: "Recruitment should focus on not just women but women of color."
- Recruit speakers for JuliaCon in order to achieve higher diversity of speakers at JuliaCon. This entails a personal volunteer effort. If you know a person who belongs to an underrepresented group in the Julia community and might have some free time on their hands (maybe a highschool student or college student), and you are willing to mentor them on a Julia project you have in mind, or an idea they have, it might be a good idea to reach out to them and start collaborating now. We often have the funds to provide travel support to underrepresented groups in the community and this can be a motivation for the student to work on this project and potentially present it at JuliaCon. Of course, this item is by no means a promise that the talk will be accepted or travel funds will be provided, but it is worth the shot.
- Reach out to organizations such as Girls Who Code and Women Who Code, and ask about the putting Julia learning material on their websites and/or curriculum (this involves an effort to actually come up with this content).
- Run/sponsor a "data-thon" (that uses Julia exclusively) similar to what WiDS runs every year: [link here](https://www.widsconference.org/datathon.html). Half of each team participating in this competition must be from underrepresented groups in the Julia community and there is a monetary prize at the end. If the data and the problem we are solving is coming from a company, it is possible that we can get the company to sponsor part of that event.

**Comment by ViralBShah** [comment]
Once some of these ideas mature, and we have a clear call to action, we should put up a `diversity` section on our website.

**Comment by ViralBShah** [comment]
Percentage of female visitors remains at 16-18% across all julia related websites - website, discourse, juliacon, docs. youtube does not report.

**Comment by ViralBShah** [comment]
Here's the growth in number of female users on docs.julialang.org. 

![Screen Shot 2019-09-19 at 9 44 11 AM](https://user-images.githubusercontent.com/744411/65249483-10b02280-dac2-11e9-8b90-710a81c23d3e.png)

The percentage of female users in the total has also been steadily increasing.

![Screen Shot 2019-09-19 at 9 48 27 AM](https://user-images.githubusercontent.com/744411/65249922-c11e2680-dac2-11e9-8c17-87fa45da1134.png)
