### ISSUE TITLE
Julia SEO Improvements

### ISSUE THREAD

**Issue by TheComputerM** [JuliaLang/www.julialang.org#501]
This is my entry for the Google Code In task about optimizing Julia's website for SEO
[Julia SEO Report.pdf](https://github.com/JuliaLang/www.julialang.org/files/3929924/Julia.SEO.Report.pdf)

**Comment by ViralBShah** [comment]
Are you opening this as part of Google Code-In?

**Comment by logankilpatrick** [comment]
Yes. This PDF contains a bunch of actionable items we can use to improve the SEO of the site.

**Comment by TheComputerM** [comment]
Yes, my mentor told me to do so.

**Comment by ViralBShah** [comment]
Just wanted to make sure everyone else knew - otherwise it might be puzzling. Can we create a bulleted list of action items from that document right here in the github issue, so that we can track how we are doing?

**Comment by ViralBShah** [comment]
Also, welcome @TheComputerM !

**Comment by TheComputerM** [comment]
Thanks dude.

**Comment by TheComputerM** [comment]
- Every page is missing a meta description
- Use video formats instead of large gifs to boost performance
- Make titles of pages (listed in pdf) less than 65 characters and more than 20 characters
- Low word count in some pages
- Console warnings in many pages may reduce site rank

Otherwise the SEO of the site is good, the only problem is that the language is not very well known, advertising on google AdWords when users search for terms like ‘python’, ‘data science’, and ‘best programming languages for machine leaning’ may prove to improve the Julia’s popularity

**Comment by TheComputerM** [comment]
You can use googles lighthouse (a website auditing tool) to see what more can be improved. Located in chrome Devtools > Audits

**Comment by mikolajhojda** [comment]
Some ideas for improvements
[seo (1).pdf](https://github.com/JuliaLang/www.julialang.org/files/3931108/seo.1.pdf)

**Comment by ViralBShah** [comment]
Instead of linkibg a PDF, please post the suggestions right here. Even better would be to contribute PRs implementing the suggestions.

**Comment by mikolajhojda** [comment]
I think you could change using images on your page. For example in the section “Talk to us” are images assigned in CSS, not in HTML. Google suggests avoided this solution “Using CSS to display images that you want us to index”. You should make it in ‘picture’ or ‘img’ tag. In the next section “Editors and IDEs” we see images with ‘img’. You could change it to ‘picture’ with for example ‘loading="lazy”’ for better optimization or for specifying multiple options for different screen sizes for responsive images. Solutions will be better for Google algorithms. It will help with your Google index.

**Comment by soumitradev** [comment]
> Every page is missing a meta description

I will be working on this as a part of GCI

**Comment by soumitradev** [comment]
Another thing I have noticed is lot of pages are in Markdown format. If we could rewrite these in HTML, we could use Meta tags and other SEO features and optimize these pages as well. However, I'm not sure how this will affect the website's performance.

**Comment by TheComputerM** [comment]
Converting markdown to HTML would not improve the performance as Jekyll builds the site in HTML.

**Comment by soumitradev** [comment]
I was mainly focusing on SEO improvements, but according to @TheComputerM, it seems that it would not hurt performance. So, this seems like a good idea if we're purely doing this for SEO.

**Comment by ViralBShah** [comment]
You can embed html in MD. Also we may be moving to Hugo. I'm any case these are all static, so no speed problems.

**Comment by TheComputerM** [comment]
@logankilpatrick Can you add a task in GCI to port the website to HUGO. I am a material design developer and would like to remake the site using Google's material design guidelines. Here is my portfolio: [TheComputerM](https://thecomputerm.github.io)

**Comment by ViralBShah** [comment]
See #531. Maybe collaborate? Or move to Hugo first and then do material design guidelines as a separate task?

**Comment by ViralBShah** [comment]
Also relevant: https://juliacomputing.com/blog/2019/09/16/tiobe-blog.html

**Comment by ViralBShah** [comment]
@logankilpatrick Close this?
