### ISSUE TITLE
Attribution for header image

### ISSUE THREAD

**Issue by essenciary** [JuliaLang/www.julialang.org#51]
@ViralBShah I forgot about this, but the main image was inspired by: 
https://commons.wikimedia.org/wiki/File:Equation-time-graph-4.png

What's a good place to add the attribution?

**Comment by ViralBShah** [comment]
Can you suggest where to attribute? Bottom of page in the footer? We are using an updated version by @cormullion.

**Comment by cormullion** [comment]
Don’t bother on my account, wiki stuff is freely reusable!

**Comment by mbauman** [comment]
Hah, I love how the original wikimedia commons file is also by you, @cormullion! :)

On the wikimedia page you assert a by-SA CC4.0 license, which would require attribution.  Am I correct in understanding that you're waiving that here?

**Comment by cormullion** [comment]
Yes it's funny that I didn't realise this until @essenciary mentioned it in this issue. :)

I barely understand licensing, but does this paragraph in the license:

> You must attribute the work in the manner specified by the author or licensor (but not in any way that suggests that they endorse you or your use of the work).

mean that *if* I specify a "manner" then that "manner" should be copied, but if I don't, then no "manner" is required? That was my interpretation, anyway.

Everything I make with Julia (Github, Flickr, etc) is in the public domain so it's all freely copiable without attribution.

I don't expect this particular image to last too long, anyway, once the bikeshedding begins in earnest, but it was a cool placeholder to get things moving...

**Comment by mbauman** [comment]
Yup, if you created/own the content then **you** are free to do with it as you like! You can license it many different ways to many different groups; you're not beholden by the terms of the license(s) you choose.

Thanks so much for all the work you've done, and thanks again for letting us use it so freely!

**Comment by essenciary** [comment]
Thanks @cormullion that's very kind
