### ISSUE TITLE
Make a GitHub Action to deploy the site as a check after a commit

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#522]
See if it's possible to use netifly to render the site online as part of the CI/CD pipeline.

**Comment by abhishalya** [comment]
Yes, its very much possible. You can have a look at my preview [here](https://julialang-preview.netlify.com). One of the maintainer only need to add this site via Github to Netlify and add a suitable build command and target like `jekyll build` and `_site` respectively. That should be all that is required. Netlify should be able to install deps and deploy the site automatically. It also checks for mixed content, unsecured links, etc. Also it triggers deploy previews on PRs.
