### ISSUE TITLE
Add Installation Instructions for Windows 10 64 bit

### ISSUE THREAD

**Issue by TheComputerM** [JuliaLang/www.julialang.org#523]
This will provide instructions on how to add Julia binaries to windows to be run from CLI.

**Comment by logankilpatrick** [comment]
Hey, the only OS not claimed is MacOS. Can you add instructions for that or are you running windows?

**Comment by TheComputerM** [comment]
@logankilpatrick  I am using Windows but also know how to use MacOS. I can add instructions for MacOS, but I currently don't have a Mac so the images used will not be mine.

**Comment by logankilpatrick** [comment]
Probably best to do a different task then

**Comment by TheComputerM** [comment]
Ok, so do I abandon task? because that would lose me points in GCI.

**Comment by logankilpatrick** [comment]
I removed you from the task.

**Comment by TheComputerM** [comment]
Thanks
