### ISSUE TITLE
Fix dead links

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#524]
Resolves #156 

See https://github.com/JuliaLang/www.julialang.org/commit/a795c88608690f9ea896408a6884e00145ae1ddf/checks?check_suite_id=373243536

for a list of all broken/dead links in the repo. These need to be updated with the appropriate links or have their content removed.

**Comment by ViralBShah** [comment]
In some cases (of internal links) the stuff has probably moved to a new URL. For external broken links, it is worth seeing if there are updated links.

**Comment by abhishalya** [comment]
Dead links: https://gist.github.com/abhishalya/fabbc769e939fa25ff61cbdd42e5bc9f

**Comment by ViralBShah** [comment]
Do you want to put these in a spreadsheet? I can provide updated links for most of these. Can probably just write a simple sed script to auto-replace the whole thing.

**Comment by logankilpatrick** [comment]
I made this a code in task and he’s going to update them in the morning, whether that be via a sed script or manually.

**Comment by logankilpatrick** [comment]
I’m not sure what a sed script is but it may be nice to have for future broken links.

**Comment by ViralBShah** [comment]
Here's a spreadsheet:

https://docs.google.com/spreadsheets/d/1g-2o6JcSw-f_sBsMBScVWycrw0JxZsnZ7J9-YldW8WE/edit#gid=1563594672

What we need to do is to populate the second column with the replacement. Then it is trivial to write a simple script to replace the broken links in one shot.

sed: https://www.gnu.org/software/sed/manual/sed.html#Overview

**Comment by ViralBShah** [comment]
We should probably do  similar check on julia docs as well.

**Comment by logankilpatrick** [comment]
Yep, will add a PR later today for this.
