### ISSUE TITLE
Better way to handle translations of blogs

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#529]
Currently we just post a new blog post for every translation. Is it possible to set up a system where translations show up on blog posts where they are available?

**Comment by logankilpatrick** [comment]
https://weglot.com/github-students/

**Comment by ViralBShah** [comment]
This seems like automatic translation. I was referring to human-written translations. Otherwise, I find google translate does a fine job.

**Comment by abhishalya** [comment]
We can do this: http://chocanto.me/2016/04/16/jekyll-multilingual.html

**Comment by abhishalya** [comment]
Its easy to handle multilingual content through hugo:

https://gohugo.io/content-management/multilingual/

**Comment by ViralBShah** [comment]
We have individual blog pages in chinese and Spanish and then also cn.julialang.org

**Comment by goggle** [comment]
The blog overview page looks really ugly if your browser font does not include Chinese symbols:
![image](https://user-images.githubusercontent.com/1856425/72549013-32fb5680-3890-11ea-96b8-2d7b3284271b.png)
If hugo's multilingual feature can be applied to specified content (and not the whole site), that would be great!

**Comment by ViralBShah** [comment]
Not much to do here for now.
