### ISSUE TITLE
Switch to Hugo

### ISSUE THREAD

**Issue by abhishalya** [JuliaLang/www.julialang.org#531]
We need to switch from Jekyll to Hugo. There's a lot to gain from this switch.

- Faster builds
- No more dependency issues
- Very easy to set up.
- Go.
- As easy as Jekyll to deploy, both on GitHub pages and Netlify.

I'll be working on this. This is also a part of GCI.

**Comment by abhishalya** [comment]
I've ported the site, have a look at https://github.com/abhishalya/julialang-hugo
I see that we've some of the old site data in there, do we still need it?

cc @logankilpatrick @ViralBShah

**Comment by ViralBShah** [comment]
Nice! I am wondering if instead of a PR we should archive the old website repo and create a new repo.

**Comment by abhishalya** [comment]
@ViralBShah That would be really nice, although we already have an archive of old site.

**Comment by ViralBShah** [comment]
Well I meant a second old website archive.

**Comment by abhishalya** [comment]
If its okay with you, I have no problem.

**Comment by ViralBShah** [comment]
I created a new repo hugo.julialang.org. can you transfer there and set it up?

Let's announce on discourse for people to browse around and send feedback. We can make the switch over in a few days.

**Comment by abhishalya** [comment]
Thanks! I'm pushing some files to the repo now, I'll get this site completely ready by tomorrow after which we can share this for feedback.

**Comment by logankilpatrick** [comment]
Please ping us here or on slack if you run into any trouble!

**Comment by ViralBShah** [comment]
We should remember to transfer open issues to the new repo.

**Comment by logankilpatrick** [comment]
Will do so once the repo is up and running.

**Comment by abhishalya** [comment]
@ViralBShah Can you change the default branch to master, I had used `init` branch initially.

**Comment by logankilpatrick** [comment]
It’s done!

**Comment by logankilpatrick** [comment]
@ViralBShah the new site is available to preview here: https://hugo-julialang.netlify.com/

It should be identical to the existing site. 

@abhishalya great work! I will try to get the site deployed using GitHub pages in the next couple of days. Note that we still need to transfer over the most recent updates that have occurred on this repo.

**Comment by ViralBShah** [comment]
I have been browsing the new site! Looks great and clean!
