### ISSUE TITLE
Wrong link to juliabloggers.com

### ISSUE THREAD

**Issue by SaschaMann** [JuliaLang/www.julialang.org#539]
As pointed out by Colin on [Slack](https://julialang.slack.com/archives/C67KW7401/p1577583627044800), the link to juliabloggers.com on https://julialang.org/blog/ isn't working.

This can be fixed by changing https://github.com/JuliaLang/www.julialang.org/blob/f89bf137926b271b5b489788d4feb0d3df71c067/blog/index.html#L21 to link to `httpS://www.juliabloggers.com`. The non-HTTPS URL forwards to http://www.juliabloggers.com/public_html/ which only shows an error message.

I don't have jekyll installed so I can't fix it myself

**Comment by logankilpatrick** [comment]
Will fix in an hour or so. Thanks for pointing this out.

**Comment by ViralBShah** [comment]
Btw, you can directly edit the website on GitHub.
