### ISSUE TITLE
Conversion issues in blog posts

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/www.julialang.org#549]
When I did this job recently, the most trouble I had was with the maths. So:

- https://julialang.org/blog/2013/04/distributed-numerical-optimization/
- https://julialang.org/blog/2017/09/gsoc-2017-project-hamiltonian-indirect-inference/

were the first two I looked at, and the math problems are familiar - all those unconverted `$` signs. Before going through all the blog posts again†, is there some general setting that you can throw that does the maths right...? Is it a KATEX/MathJAX thing? For Julia, the maths has to be good...

† Don't do it more than once, that way madness lies... :)

**Comment by logankilpatrick** [comment]
@cormullion the issue was/is that Netlfiy was/is working its dirty magic. In the preview's it looks fine and then once it gets deployed things break.

**Comment by abhishalya** [comment]
This should be completely fixed with JuDoc implementation.
