### ISSUE TITLE
site is down

### ISSUE THREAD

**Issue by 00vareladavid** [JuliaLang/www.julialang.org#551]
From the recent commit list, seems like something went wrong in the transition to Hugo?

**Comment by ViralBShah** [comment]
Working on the transition

It is serving fine here: https://julialang.github.io/www.julialang.org/

Something with the CNAME stuff is not quite working. If you know how to troubleshoot, help on the #hugo-website slack channel is appreaciated!

**Comment by 00vareladavid** [comment]
could it be the missing newline in the CNAME file?

**Comment by logankilpatrick** [comment]
That shouldn't matter, see https://github.com/JuliaLang/hugo.julialang.org/blob/5911c1231bb681a2ceb124178dd957eec7590fc1/CNAME

**Comment by logankilpatrick** [comment]
Worked fine serving to that domain

**Comment by logankilpatrick** [comment]
All good now, @ViralBShah worked his magic
