### ISSUE TITLE
Julia Paper to cite not showing up 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#567]
See here https://julialang.org/research/

The paper to cite is missing. See "/layouts/research/list.html".

**Comment by ViralBShah** [comment]
That template bit is getting completely left out when the site is generated.

**Comment by ViralBShah** [comment]
This paper needs to show up:
 https://github.com/JuliaLang/www.julialang.org/blob/af98a5977f92cd46b2abe7566a44eae79625dfd6/layouts/research/list.html#L20

**Comment by ViralBShah** [comment]
Maybe it has to be `_publications` or something?

**Comment by logankilpatrick** [comment]
This is still an issue
