### ISSUE TITLE
Use shortcodes for html in markdown

### ISSUE THREAD

**Issue by abhishalya** [JuliaLang/www.julialang.org#574]
Using html in markdown is not suggested by Hugo, since the default markdown processor Goldmark in Hugo doesn't allow this. Currently, we use blackfriday (previous default in Hugo) for processing markdown which will soon be deprecated.

**Comment by logankilpatrick** [comment]
What needs to be done on this front?

**Comment by ViralBShah** [comment]
Move to JuDoc?

**Comment by abhishalya** [comment]
If we move to JuDoc, then this won't be an issue since we won't be following [Commonmark complaint](https://commonmark.org/).
