### ISSUE TITLE
Consider stopping the use of Netlify Deploy preview 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#576]
Hey all, Thoughts on stopping the use of Netlify deploy preview? The preview is oftentimes misleading. I just checked the preview, all was good and the issues were resolved. After I merged the branch, things are now worse off than they were before...

**Comment by logankilpatrick** [comment]
I think this may just be an 404 re-direct specific thing

**Comment by abhishalya** [comment]
I would suggest opposite, Netlify is much better than github pages specially for hugo. It provides a really nice CI/CD system which is very useful whil merging PRs.

**Comment by abhishalya** [comment]
Right now for hugo github pages seems to be buggy and isn't behaving properly wrt the changes made. I would **highly** suggest moving to Netlify completely.

**Comment by ViralBShah** [comment]
What do we need to do to move to netlify completely? Is the free tier sufficient?

**Comment by abhishalya** [comment]
Yes, it is sufficient. The only limitation is that the site settings can only be monitored by single person. If someone can take up that responsibility then it should be fine.

**Comment by logankilpatrick** [comment]
Okay, I'll do it. Where do I go?

**Comment by abhishalya** [comment]
netlify.com

**Comment by ViralBShah** [comment]
@logankilpatrick If we create an account, best to use the email subscriptions@julialang.org as the associated email. I can add you to it.

**Comment by ViralBShah** [comment]
I don't know how to configure the DNS to point to netlify (instead of gh pages). This is something that @staticfloat may know more about, since we serve the website through fastly.

**Comment by logankilpatrick** [comment]
I’ll play around with netlify and see what I can figure out.

**Comment by cormullion** [comment]
Can we afford Netlify (the free tier has restrictions...)?

**Comment by ViralBShah** [comment]
What are the restrictions? I imagine since we will be serving through our own CDN, bandwidth etc. may not matter much.

**Comment by ViralBShah** [comment]
@abhishalya Just to understand, what is github pages doing wrong for our site? Isn't hugo generating a static site for github pages to serve?

**Comment by logankilpatrick** [comment]
My opinion is that we stick with using gh-pages to serve and such. Unless others think there's something that does not work now that will work better using Netlify to deploy, I am going to delete the site on Netlfiy (this shouldn't affect anything)
