### ISSUE TITLE
Getting Started page for Google Code-in returns a 404

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#578]
https://julialang.org/learning/getting-started  is no longer working. 

Where was this file supposed to be @aviks  ? I cannot find it in the content section.

**Comment by ViralBShah** [comment]
Perhaps have to look through git history from the old website

**Comment by logankilpatrick** [comment]
I’ll find it and re-add it unless one one does before me

**Comment by aviks** [comment]
This is the PR that added it: https://github.com/JuliaLang/www.julialang.org/pull/485

**Comment by logankilpatrick** [comment]
Fixed!
