### ISSUE TITLE
Julia soc idea page gives error 404

### ISSUE THREAD

**Issue by sid21g** [JuliaLang/www.julialang.org#579]
Julia's soc/ideas [page](https://julialang.org/soc/ideas-page) gives 404 error, "It appears that you have stumbled upon a page on the Julia website that does not exist."

**Comment by ViralBShah** [comment]
We probably should reinstate a redirect for this.

**Comment by logankilpatrick** [comment]
https://discourse.gohugo.io/t/how-to-setup-redirects-with-hugo-and-github-pages/22798

**Comment by logankilpatrick** [comment]
All of these give 404's  https://www.ecosia.org/search?q=julia+lang+soc

**Comment by ViralBShah** [comment]
I thought all you have to do is create pages at the old URL location that are 302 redirects. I think the old website had some of these.

**Comment by logankilpatrick** [comment]
That may be true, I have no idea. I’ll look at the repo and try to fix it tomorrow.

**Comment by ViralBShah** [comment]
We should probably mark a tag for the old website so we can go back to it easily.

**Comment by ViralBShah** [comment]
We used to have a `redirect` layout like: https://github.com/JuliaLang/www.julialang.org/blob/15e055688a3ccc8d7d892907f131b7efcf55c1b5/_layouts/redirect.html

**Comment by logankilpatrick** [comment]
Did some work on this, but it's still an issue. I got https://julialang.org/soc/ideas-page/ to redirect but not https://julialang.org/soc/ideas-page

**Comment by logankilpatrick** [comment]
but googling "julia soc" gives this link now: https://julialang.org/soc/ideas-page.html

**Comment by abhishalya** [comment]
Fixing this in the next PR
