### ISSUE TITLE
[small] Linux platform specific instructions point to wrong download link

### ISSUE THREAD

**Issue by soumitradev** [JuliaLang/www.julialang.org#581]
In https://julialang.org/downloads/platform/, under the Linux and FreeBSD instructions, the link in the sentence has an error.

> First, download the .tar.gz file from the downloads page. You need to extract this file to a suitable location. To extract the file, you can use the following command:

The link to the downloads page simply points to the same platform specific instruction page it was on instead of the actual downloads page.

The link points to https://julialang.org/downloads/platform/ when it should point to https://julialang.org/downloads/.

**Comment by logankilpatrick** [comment]
Fixed this!
