### ISSUE TITLE
Googling "julia downloads nightly" gives a page that 404s

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/www.julialang.org#584]
The link it shows is https://julialang.org/downloads/nightlies.html but that 404s. The working one doesn't have the ´.html`.

**Comment by ViralBShah** [comment]
I think Google will catch up, but the real issue is other websites using the old links.

**Comment by logankilpatrick** [comment]
Poorly written on my part but: https://discourse.gohugo.io/t/how-to-allow-a-webpage-to-be-accessible-by-an-html-extension-in-hugo/22823

**Comment by abhishalya** [comment]
Do we want to use ugly urls (if we've used them as default previously)? Switching to them is just about adding a new setting to the config.

**Comment by fredrikekre** [comment]
Can just add redirects.

**Comment by logankilpatrick** [comment]
The issue is that we already have the file nightlies.html, but Hugo is omitting the ".html" portion to make it pretty.

**Comment by fredrikekre** [comment]
No, thats not how it works, there is `.../nightlies/index.html` (which is served when requesting `.../nightlies`.

**Comment by ViralBShah** [comment]
So might we be able to fix this by just renaming this file to `nightlies.html`?

**Comment by fredrikekre** [comment]
No, we want the current structure, but could consider adding `nightlies.html` that just redirects to the current one.

**Comment by ViralBShah** [comment]
I also wonder why Google has not caught up.

@abhishalya Do we have something in Hugo to enable the sitemap? Maybe we are already doing so?

**Comment by abhishalya** [comment]
sitemap is automatically generated by hugo using a default template. We can customize it too if we want.

https://gohugo.io/templates/sitemap-template/

**Comment by ViralBShah** [comment]
Default is good!

**Comment by logankilpatrick** [comment]
#607
