### ISSUE TITLE
CI/CD for github pages.

### ISSUE THREAD

**Issue by abhishalya** [JuliaLang/www.julialang.org#589]
I believe this should be possible. We are mostly merging stuff assuming that it works, but mostly it doesn't. To avoid bad changes we need to have a good CI platform to handle this. Netlify deploy previres were great, but it expects to handle the production deploy too. Since, we rely on Github pages, we need to figure something out.

This is for both, Hugo and JuDoc.

**Comment by logankilpatrick** [comment]
I am not sure that there is any way to do this. Open to suggestions but I am at a loss.

**Comment by ViralBShah** [comment]
At least hugo is easy enough to set up locally.

**Comment by logankilpatrick** [comment]
#576
