### ISSUE TITLE
change "Julia IDE's" to "Julia Editors" and add vim and emacs

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/www.julialang.org#59]
As discussed [here](https://discourse.julialang.org/t/new-website/12844/43?u=expandingman) I think it would be really nice if we included the [julia-vim](https://github.com/JuliaEditorSupport/julia-vim) and [julia-emacs](https://github.com/JuliaEditorSupport/julia-emacs) in the editors/IDE's section.  These packages are both well-maintained and work very well.

**Comment by ViralBShah** [comment]
We'll need a PR that works with the layout there, and the `vi` and `emacs` icons. Any takers?

**Comment by ViralBShah** [comment]
@ranjanan Can you try to add 2 more editors to this section with some nice emacs and vi logos and see if you make it all work out?

**Comment by ranjanan** [comment]
Can you give me an idea for one more editor, that way I can have 2 rows of 3 icons each.

**Comment by ChrisRackauckas** [comment]
SublimeText seems to be the next one that people always mention.

**Comment by ViralBShah** [comment]
Sublime Text used to be there and we took it off because it is not maintained. @quinnj doesn't maintain it he said.

**Comment by Evizero** [comment]
A bit of a stretch maybe, but the REPL is unusually userfriendly and featureful. maybe we could use the first slot to advertise that somehow

**Comment by ChrisRackauckas** [comment]
OhMyREPL?

Or this IntelliJ plugin has been catching my eye: https://plugins.jetbrains.com/plugin/10413-julia

**Comment by KristofferC** [comment]
I don't think OhMyREPL.jl really fits in that list :)

**Comment by ranjanan** [comment]
It looks like the sublime plugin is at least as well maintained (last commit in Jan 8, 2018) as the emacs plugin (last commit Nov 2017)

**Comment by ChrisRackauckas** [comment]
Well if you did want to point to the REPL that would be the place to point. 

What about the Atom Hydrogen plugin? That's been well-maintained for years

https://atom.io/packages/hydrogen

Though that is Atom + Jupyter.

**Comment by ExpandingMan** [comment]
I don't use the emacs plugin myself, but I'm pretty sure there are lots of people still using it, I've seen people discuss it on discourse.  @tpapp do you use that (I see you were on the last commit)?  Note that the editor plugins usually require a lot less updating than the package itself.

**Comment by ViralBShah** [comment]
Ok, the long tail needs its own page. :-) OhMyREPL should really just live in the stdlib if you ask me.

**Comment by tpapp** [comment]
Yes, I am using https://github.com/JuliaEditorSupport/julia-emacs. It is working fine, aside from some minor indentation issues.

**Comment by ranjanan** [comment]
Fixed by #65 ?

**Comment by ExpandingMan** [comment]
Looks great thanks!
