### ISSUE TITLE
Add upgrade Julia version instructions

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#590]
Per here: https://discourse.julialang.org/t/a-proper-introduction-on-how-to-update-julia-somewhere-accessible/28166

We should add some sort of “official” upgrading Julia version instructions.

**Comment by ViralBShah** [comment]
Generally, while you may want to upgrade - as in replace a patch release, you don't want to do that for minor and major releases. For those, you may want multiple versions of Julia around and we prepare the directory names and install paths carefully for that to work.

**Comment by logankilpatrick** [comment]
I am not sure I follow. What does "you don't want to do that for minor and major releases"  mean? I don't want to update my Julia version?

**Comment by ViralBShah** [comment]
A Julia 1.2 install should not be replaced with 1.3, for example but 1.2 can be replaced with 1.2.1.

**Comment by logankilpatrick** [comment]
What do you mean by "should not be replaced"? Are you saying the user should keep 1.2 and 1.3 installed?. I have like 8 versions of Julia on my computer but I still want to keep updating to the different versions. 

I want to get something on this front going since it's a common question and the process is not easy.

**Comment by ViralBShah** [comment]
Let's continue this in #926
