### ISSUE TITLE
"sudo apt-get upgrade julia" downgrades to v.1.0.4

### ISSUE THREAD

**Issue by PeterNorlindh** [JuliaLang/www.julialang.org#597]
Upgrading Julia in Ubuntu is such a pain for me. And it feels like it could just as well have been super easy...

Here's what happens. When I do "sudo apt-get upgrade julia" it doesn't upgrade to v.1.3 (which I expected), no instead it downgrades to v.1.0.4! 

I have no idea how these things are maintained and by whom, but would presume that sudo apt-get upgrade... should work, right? Perhaps the task of updating the repository has fallen between the chairs or something? Anyhow, it would be soooo great if the sudo command worked properly.

Peter

**Comment by fredrikekre** [comment]
This is not maintained by the Julia community. The recommended way to install julia is to download from: https://julialang.org/downloads/

**Comment by ViralBShah** [comment]
Cc @ginggs
