### ISSUE TITLE
macOS install instructions for Julia in the terminal don't work

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#606]
> If you are using zsh, type the following in the Terminal:
> 
> open -a TextEdit ~/.zshrc
> 

<img width="682" alt="Screen Shot 2020-01-24 at 9 31 55 AM" src="https://user-images.githubusercontent.com/35577566/73076566-5de73b00-3e8c-11ea-8a8b-309ef0752325.png">

https://julialang.org/downloads/platform/

**Comment by logankilpatrick** [comment]
@fungktt

**Comment by giordano** [comment]
What version of macOS do you have?  If I remember correctly, Catalina made ZSH the default shell

**Comment by logankilpatrick** [comment]
Yes, it's my default (I think at least from the text at the top of the terminal)

**Comment by giordano** [comment]
That's quite interesting.  I don't know how it works on macOS, but on GNU/Linux I think it's not easy to start an interactive ZSH shell without a zshrc script.

I thing you can change the wording suggesting to create the file if it doesn't exist

**Comment by logankilpatrick** [comment]
Got it. When I type `julia` it opens up version 1.0.3 but not 1.3 which is what I want so it must be set somewhere.

**Comment by fredrikekre** [comment]
Check with `which julia`.

**Comment by logankilpatrick** [comment]
Okay, I see that file but how do I make it go to 1.3 instead?

**Comment by KristofferC** [comment]
`which julia` will tell you what executable runs when `julia` is executed. The reason why that file runs is because it is the first file matching the name found in the directories in `PATH`. You can remove it and symlink the 1.3 executable to one of the folder in PATH (like `/usr/local/bin`).

**Comment by logankilpatrick** [comment]
how does one symlink ? @KristofferC

**Comment by KristofferC** [comment]
Something like `ln -s /Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia /usr/local/bin/julia`

**Comment by logankilpatrick** [comment]
That did the trick! `julia` now opens julia 1.3!

**Comment by logankilpatrick** [comment]
Just tried this again for 1.4 and it worked like a charm. Also updated the install instructions to just include this process.
