### ISSUE TITLE
Publication list formatting

### ISSUE THREAD

**Issue by thofma** [JuliaLang/www.julialang.org#614]
While looking at the publication list, I noticed that the package names are all lowercase. Also the list of packages always ends with an ", ", which is then followed by ".".

Also the author list of https://github.com/JuliaLang/www.julialang.org/blob/88404b1c83b4a121370b1be30c0747808c6d6710/content/research/BST19.md (the first item on the list) is not formatted properly.

I looked for a quick fix, but I am lacking the necessary Hugo skills.

**Comment by ViralBShah** [comment]
@abhishalya

**Comment by abhishalya** [comment]
Thanks for reporting, will fix this soon.

**Comment by abhishalya** [comment]
I've opened a PR to fix this. It does take care of the `, ` delimit thing. But I see that by default Hugo lowercases the frontmatter variables. There's some discussion [here](https://discourse.gohugo.io/t/would-be-great-if-frontmatter-variables-didnt-have-to-be-all-lowercased/1608/3) on that.
