### ISSUE TITLE
Publication list/research.html: package names malformatted

### ISSUE THREAD

**Issue by thofma** [JuliaLang/www.julialang.org#618]
There are displayed in lowercase, but they should be displayed as CamelCase.

This does not look nice. In particular if the package name appears in the title of the paper.

**Comment by abhishalya** [comment]
One way to fix this would be to have the packages listed as a list. Currently, they are represented as key-value pairs but if we can convert them into value list then it this can be fixed.

**Comment by tlienart** [comment]
Now fixed: https://julialang.org/research/

<img width="960" alt="Screen Shot 2020-03-13 at 19 51 07" src="https://user-images.githubusercontent.com/10897531/76651033-13b53880-6564-11ea-963a-76b764b5ae17.png">
