### ISSUE TITLE
Publication list/research.html: author lists malformatted

### ISSUE THREAD

**Issue by thofma** [JuliaLang/www.julialang.org#619]
If the authors are specified as "surname, forename" instead of "forename surname", the author list is displayed wrong, see for example the html output for https://github.com/JuliaLang/www.julialang.org/blob/master/content/research/KN18.md.

**Comment by abhishalya** [comment]
This is fixed in the Franklin migrationhttps://github.com/JuliaLang/www.julialang.org/pull/655
