### ISSUE TITLE
Publication list/research.html: Spurious whitespaces after year

### ISSUE THREAD

**Issue by thofma** [JuliaLang/www.julialang.org#620]
There are spurious whitespaces if some (optional) entries are missing. See for example, the first entry coming from https://github.com/JuliaLang/www.julialang.org/blob/master/content/research/BST19.md.
It displays "(2019) ." instead of "(2019).".

**Comment by abhishalya** [comment]
Fixed in https://github.com/JuliaLang/www.julialang.org/pull/655
