### ISSUE TITLE
Some links not working

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/www.julialang.org#684]
A. From the home page to Julia Observer, I mean the link takes me there, but there's some problem there. [The link next to that one gave me garbled text but seconds later when trying again it's ok.]

B. Then going to the docs, it worked (and the "Edit" in the corner), while going to release notes, the Edit in the corner no longer works, sends me to:

https://github.com/JuliaLang/julia/blob/master/doc/src/NEWS.md

Should NEWS also be there (some redirect?) or "doc/src/ be taken from the link?

C. Before in the docs, I could choose to look up older docs. Maybe it was taken out intentionally? I doubt it relates to the above, but we want to keep access to Julia 1.0 LTS docs?

**Comment by ViralBShah** [comment]
None of these seem to be julialang.org website issues. I suspect you'll have to file these in relevant repos. Please reopen if there is a broken link on julialang.org itself.

**Comment by tlienart** [comment]
Re (C) just FYI the bottom of the navbar on the left of the docs page has a version toggle 

![Screenshot 2020-03-24 at 15 51 27](https://user-images.githubusercontent.com/10897531/77439518-6eae2180-6de7-11ea-8d2c-7075933153b6.png)
(see screenshot below)
