### ISSUE TITLE
External people's PR does not trigger a build

### ISSUE THREAD

**Issue by tlienart** [JuliaLang/www.julialang.org#687]
This is not really  a  pressing issue but if someone "registered" with this repo opens a PR, it will launch a build and eventually a preview will be available at julialang.netlify.com, which is convenient. For everyone else, the github action will fail and a red cross will show. This is due to the github action and how it uses secrets (DEPLOY_KEY), there may be a way around it but I'm not familiar enough with github actions to see how to do this better.

So in this issue we could discuss how to avoid this and / or how to get previews on PR differently and in a more fool-proof way.

**Comment by abhishalya** [comment]
Sorry I think I missed this conversation on Slack, but why not use Netlify deploy previews?

**Comment by tlienart** [comment]
Can you install Julia on Netlify? if not then this is not doable (there needs to be a build process somewhere)

**Comment by abhishalya** [comment]
Ah, okay. I'll check if we can add Julia image to Netlify.

**Comment by tlienart** [comment]
Does some GA wizard know how to not trigger the CI at all if it's not a collaborator? (otherwise people get these failed CI in their  PRs and ask about it)

**Comment by logankilpatrick** [comment]
I will look into it, but it sort of defeats the purpose to not have them for external folks since seemingly the folks who are collaborators are "more trusted" and won't mess things up. But perhaps that is a wrong assumption to make.

**Comment by ViralBShah** [comment]
It would be nice if it would work for everyone. But in the meantime...

**Comment by tlienart** [comment]
^ so I've not used GA enough to really understand all this but what I think is happening is that GitHub prevents that everyone can trigger because there's a finite number of minutes per free tier

Here I think  it's an  easy work around to just avoid the trigger but also avoid the  red cross, and people can check locally  if things look good.

**Comment by giordano** [comment]
>  because there's a finite number of minutes per free tier

Isn't it unlimited for public repositories? https://github.com/pricing

**Comment by logankilpatrick** [comment]
It's a security paradigm.

**Comment by tlienart** [comment]
> > because there's a finite number of minutes per free tier
> 
> Isn't it unlimited for public repositories? https://github.com/pricing

Hmm you're probably right, maybe I misread!

Well  I'm happy for this to  trigger for everyone, just need a GA wizard to tell me how to do it :)

**Comment by logankilpatrick** [comment]
Yeah, I am on the longest ever GitHub issue thread where people just complain that the actions don't run for external people. I will email Netflix to see if they can install Julia on the servers for us, unless anyone knows a terminal command I can run to install Julia? @ViralBShah

**Comment by abhishalya** [comment]
@logankilpatrick I've already submitted a PR to Netlify build repo to add Julia in their Docker image. They haven't reviewed it yet, but I was speaking to one of the Netlify guys and they say that it mostly depends on if a lot of people use that and if the size of the dependency isn't that large.

**Comment by logankilpatrick** [comment]
@abhishalya can you send a link to that here?

**Comment by logankilpatrick** [comment]
Found it: https://github.com/netlify/build-image/pull/395, please drop a 👍 if you can!

**Comment by tlienart** [comment]
as a comparison point here's swift's PR: https://github.com/netlify/build-image/pull/364

**Comment by tlienart** [comment]
I'll close this as @DilumAluthge added a nice condition in the GA so that PRs don't  show with a  big red cross. The recommendation is still to preview things either locally or on netlify whichever is possible and convenient. Builds that get merged on master and fail don't get deployed so that's also a bit of a safety mechanism.
