### ISSUE TITLE
rss feed for blog

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#696]
We need to update/ reinstate the rss feed for our blog.

**Comment by tlienart** [comment]
Note that there's already https://github.com/JuliaLang/www.julialang.org/blob/gh-pages/index.xml which is generated from the blog posts. 

It seems mostly fine apart from a bunch of (old?) blog posts that don't have a pub date it seems and so default to Mon, 01 Jan 0001 00:00:00 +0000

**Comment by ViralBShah** [comment]
We got an email about this from feedly.com on the JSOC email address. So I guess there are people and tools out there who are consuming our feed.

**Comment by tlienart** [comment]
Ok I actually need to fix this, currently the `index.xml` is the old one that was generated by Hugo; I should set `generate_rss` to true in https://raw.githubusercontent.com/JuliaLang/www.julialang.org/master/config.md ;

I'll do this soon and test with the netlify preview

**Comment by tlienart** [comment]
ok now it's generated by Franklin; both `julialang.org/feed.xml` and `julialang.org/index.xml` can be used; maybe another step will be to add an RSS button; I'll open another issue for that.

**Comment by ViralBShah** [comment]
If I go to the feed.xml, it has this error. Is that ok?
```
This page contains the following errors:
error on line 74 at column 51: EntityRef: expecting ';'
Below is a rendering of the page up to the first error.
```

**Comment by tlienart** [comment]
I'll look into it; I suspect one or two URLs have a `&` (I think the `ml&pl`) and it just needs escaping. It's weird that some reader handle it and some don't.

**Comment by ViralBShah** [comment]
We can also rename those blogs if easier, and have redirects from the old URLs.
