### ISSUE TITLE
add RSS button

### ISSUE THREAD

**Issue by tlienart** [JuliaLang/www.julialang.org#699]
Both 

* `https://julialang.org/feed.xml`
* `https://julialang.org/index.xml` 

can be used (it's the same file); I've tried both in the Vienna RSS reader and it works well as far as I can tell. All blog posts are on it.

It could be nice to add a RSS subscription button somewhere on the page?

**Comment by ViralBShah** [comment]
@abhishalya Perhaps this is something you can provide in a few mins.

**Comment by abhishalya** [comment]
Sure! Will get this done today.
