### ISSUE TITLE
Failure of extraction of root towards negative number where power is like 1/3,5/7 without using complex numbers.

### ISSUE THREAD

**Issue by AsForMe** [JuliaLang/www.julialang.org#709]
Operations like  (-2)^(1/3), (-1)^(-4/7) should obtain a real answer, however, in Julia even the latest version, it will say 
```
Exponentiation yielding a complex result requires a complex argument.

Replace x^y with (x+0im)^y, Complex(x)^y, or similar.

```
If we try Complex(-2)^(1/3) for example, it will return an imaginary number.  Yet it should recieve a real answer without using function Complex.
For example, if we calculate (-8)^(2/3), we should get 4, yet we calculate in Julia.
```
julia> (-8)^(2/3)

ERROR: DomainError with -8.0:

Exponentiation yielding a complex result requires a complex argument.

Replace x^y with (x+0im)^y, Complex(x)^y, or similar.

Stacktrace:

 [1] throw_exp_domainerror(::Float64) at .\math.jl:36

 [2] ^ at .\math.jl:849 [inlined]

 [3] ^(::Int64, ::Float64) at .\promotion.jl:343

 [4] top-level scope at REPL[10]:1
```
If we calculate (-27)^(5/3), we should get -243, yet we calculate in Julia.

```
julia> (-27)^(5/3)

ERROR: DomainError with -27.0:

Exponentiation yielding a complex result requires a complex argument.

Replace x^y with (x+0im)^y, Complex(x)^y, or similar.

Stacktrace:

 [1] throw_exp_domainerror(::Float64) at .\math.jl:36

 [2] ^ at .\math.jl:849 [inlined]

 [3] ^(::Int64, ::Float64) at .\promotion.jl:343

 [4] top-level scope at REPL[30]:1

```

It reports failure, I guess this issue might be difficultly fixed in the source code because it seems the same problem in python where it outputs imaginery numbers (1.0000000000000002+1.7320508075688772j) when trying (-8)**(2/3) for, and it should be fixed.
Nevertheless, if we recognize the fraction clearly as odd over odd, even over odd, odd over even, then it will easily be fixed. By extracting the continued fraction , we can achive it.
Like, 
```
julia> function frac3(x)
                n = floor(x)
                tmp = x - n
                ans = []
                while abs(tmp) > 1e-3
                  push!(ans,floor(1/tmp))
                  tmp = 1/tmp % 1
                 end
                ans = map(Int64,ans)
                N = size(ans)[1]
                i = N
                tmp_f = 0
                while i > 0
                  tmp_f = 1 // (tmp_f + ans[i])
                  i = i - 1
                end
                print(tmp_f," ",n)
              end
frac3 (generic function with 1 method)

julia> frac3(5)
0 5
julia> frac3(5/3)
2//3 1.0
julia> frac3(17/14)
3//14 1.0
```
This will extract the upper part and lower part from the fraction of real number x, however, it has limited precision because the number is stored as floating-number.
Maybe the core to fix this problem is to try testing the power before it turns to a float(?) and get proper sign bit.

**Comment by tlienart** [comment]
I would suggest you redirect your questions and comments about Julia to the main forum discourse.julialang.org ; you might also want to look for similar questions that were asked in the past and answered in details.

The repo here is only about the website.

**Comment by martinholters** [comment]
It might be reasonable to allow this for `Rational` exponent, e.g. `(-2)^(1//3)`. Not really thought this through, but if someone wants to explore this, a starting point could be
```
function ^(x::Real, y::Rational)
    if x >= 0 || iseven(y.den)
        return x^(y.num/y.den)
    else
        return -(-x)^(y.num/y.den)
    end
end
```

**Comment by tlienart** [comment]
@martinholters do you want to suggest this on Discourse? the issue is that here your suggestion may get ignored as it's the repo for the website
