### ISSUE TITLE
Images in talk to us section can be links

### ISSUE THREAD

**Issue by abhishalya** [JuliaLang/www.julialang.org#711]
We can use the images in the talk to us section on the homepage to act as links, since currently we've to click a link below the image which I don't think is necessary.

Also, rather than keeping images in the repository we could just use fontawesome or similar.

**Comment by tlienart** [comment]
see #735 ; for the second part please open another issue but I'm personally  not super keen.  IMO the site should be fully working offline as it makes it easier to maintain it.
