### ISSUE TITLE
Editors and Essential Tools headings are not aligned properly

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#714]
![Screen Shot 2020-04-14 at 4 57 47 PM](https://user-images.githubusercontent.com/744411/79273504-18298580-7e71-11ea-9868-a715a2252e9f.png)
![Screen Shot 2020-04-14 at 4 57 40 PM](https://user-images.githubusercontent.com/744411/79273506-18298580-7e71-11ea-9972-a98ac87bcadb.png)

**Comment by logankilpatrick** [comment]
Yeah, the issue lies in: https://github.com/JuliaLang/www.julialang.org/blob/master/index.html

I will fix it when I have time if no one gets to it sooner

**Comment by tlienart** [comment]
it's kind of funny, when I was working on it, I assumed it was like this on purpose :joy:
