### ISSUE TITLE
Typo in platform.md file

### ISSUE THREAD

**Issue by abhishalya** [JuliaLang/www.julialang.org#722]
https://github.com/JuliaLang/www.julialang.org/blob/master/downloads/platform.md

`Navivate` -> `Navigate`

Also, by the line:
`Navivate to /usr/local/bin and remove the julia file.`

We won't have julia file here right?

**Comment by ViralBShah** [comment]
Not unless we installed a link there

**Comment by tlienart** [comment]
partly fixed, but it'd be good you double checked  @abhishalya and maybe open a PR?

**Comment by abhishalya** [comment]
Yeah, looks good. I'm not sure if we should keep or remove that particular line since any new user won't have that file there anyways. But maybe we can open a separate issue for that if required.
