### ISSUE TITLE
Julia logo is wrong?

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/www.julialang.org#732]
I think the current file:

https://github.com/JuliaLang/www.julialang.org/blob/master/_assets/infra/logo.svg 

is incorrect, and should in fact be

https://github.com/JuliaLang/julia-logo-graphics/blob/master/images/julia-logo-color.svg

See https://github.com/JuliaLang/julia/issues/35568.

I'm pleading guilty but hoping for a reduced sentence...😀

**Comment by tlienart** [comment]
should be fixed, kindly check in ~5mins

**Comment by cormullion** [comment]
@tlienart Thanks! I didn't trust myself to do this one... 🧈 ✋
