### ISSUE TITLE
Update release page to include an all releases section

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#757]
We should have a page with all Julia releases.

**Comment by ararslan** [comment]
That's what "old releases" is, effectively, save for the current versions.

**Comment by fredrikekre** [comment]
>  save for the current versions.

and old patch releases.

**Comment by KristofferC** [comment]
I've wanted to download old patch release for different benchmarks tests before so would be nice with a long list of all releases.

**Comment by ViralBShah** [comment]
I feel that it is simpler to have a Julia package to parse the XML at https://julialang-s3.julialang.org/ in a structured way (since naming conventions may have changed over time).

Do we need more than that?

**Comment by ViralBShah** [comment]
#1702 is where this should continue.
