### ISSUE TITLE
webpage never stops loading

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/www.julialang.org#76]
go to the website and the page loads but never stops "transferring data from i.ytimg.com"
that cannot be right

**Comment by mbauman** [comment]
That's a youtube site, likely from trying to load a video thumbnail for the bottom of the page.  Not sure why it's stalling, but this would probably be fixed by #74 .

**Comment by ViralBShah** [comment]
I think this is no longer an issue. Please reopen if it is.
