### ISSUE TITLE
Blog style

### ISSUE THREAD

**Issue by Keno** [JuliaLang/www.julialang.org#762]
I'm not sure I like the way the blog looks on the new website. For reference, here's how it used to look, so that's what I'm using as a reference:

https://web.archive.org/web/20160322095210/http://julialang.org/blog/2016/03/parallelaccelerator

I think the new blog should have bigger margins, particularly on large monitors. I have a large external monitor and having the text stretch from all the way across makes it bit hard to read, because it requires a lot of head movement. Usually blogging systems restrict the width of the text to 700px or so (e.g. medium.com). The old font also seems slightly better to me, but that may just be an artifact of not liking the width of the text. There are other differences, like code blocks used to be indented, rather than out-dented as they are now (we do have syntax highlighting now though, which is of course better). Also, the size of the embedded images on the blog is a bit jarring. That is probably another artifact of the width, since they'll scale to fill the width, which makes them larger than the author probably intended.

**Comment by tlienart** [comment]
Sounds good, btw I ported everything from existing style so I plead non guilty.

So actionable items would be

* change font for Georgia or similar serif font
* limit the max content width to 700px 
* make code blocks narrower than the body

all these are pretty simple changes, there's one question as to whether this should only be applied on blog pages, all pages, or all pages minus front page?

### Part of the way

Here's one way to do all of it apart from the media queries (width) which are a bit more finicky.

**config.md**

```
@def div_content = "container main"
```

**_layout/head.html**

```
{{ispage /blog/*}}
  {isnotpage /blog/index}}
    <style>
	  .main {
		  font-family: Georgia;
	  }
	  .main pre {
		  margin-left: auto;
		  margin-right: auto;
		  width: 90%;
	  }
    </style>
  {{end}}
{{end}}
```
