### ISSUE TITLE
Footer CSS not loaded properly + issue in mobile mode

### ISSUE THREAD

**Issue by tlienart** [JuliaLang/www.julialang.org#771]
The CSS of the  footer is not loaded properly. If the site is built locally, it will look fine but online it looks like this:

<img width="675" alt="Screen Shot 2020-05-04 at 10 51 09" src="https://user-images.githubusercontent.com/10897531/80949911-3857bf00-8df5-11ea-9f17-33f93e9335a8.png">

when looking at the console, it looks like some resource doesn't get loaded properly which might be a cause (not sure), I tried shifting the order of stylesheets etc around but wasn't successful.

Someone with more experience with  web dev might be able to see what's going on here.

**Edit**: there's also an issue on mobile mode where the footer doesn't span the whole width and doesn't look good. That should probably be another issue.

**Comment by DilumAluthge** [comment]
Closed by #784 ?

**Comment by tlienart** [comment]
yes thanks!
