### ISSUE TITLE
Respect dark mode preference

### ISSUE THREAD

**Issue by Keno** [JuliaLang/www.julialang.org#775]
I was looking at https://www.youtube.com/watch?v=VgZm53qgj9Q, which starts with the julia web-page but using some sort of plugin that turns it to dark mode. I'm wondering if we can do something to make the logo look better for people who do similar things.

**Comment by tlienart** [comment]
That's a job for @cormullion 😂

**Comment by cormullion** [comment]
Yes, I noticed some dark magic going on in that video - some kind of browser add-on that forces everything to dark mode. Is that @JeffBezanson 's computer?

**Comment by cormullion** [comment]
I suppose the solution is to add a dark mode switch to julialang.org, then people won't need to a dark-mode plugin that doesn't invert images. That's a job for - well, I know it's tricky, since Slack took years to do it... :)

**Comment by cormullion** [comment]
see also https://github.com/JuliaDocs/Documenter.jl/issues/1320

**Comment by ViralBShah** [comment]
It's the browser settings of the person who made the video.

**Comment by dillir07** [comment]
I believe its due to any addon/extension that changes the background. Ex: I use [DarkReader](https://darkreader.org/) in firefox.

![Darkreader in firefox](https://user-images.githubusercontent.com/47918989/95594159-3101a500-0a68-11eb-96c4-a408251f616d.png)

**Comment by Keno** [comment]
I don't suppose there's a way to detect extensions like this and automatically provide a dark mode logo?

**Comment by Keno** [comment]
Apparently there's now a CSS media query for dark mode preference: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme. That seems like something we could definitely support.

**Comment by cormullion** [comment]
I'd added a similar issue to Documenter.jl - https://github.com/JuliaDocs/Documenter.jl/issues/1320 - in case someone wanted to make the switch automatic.

**Comment by dillir07** [comment]
This may not be anywhere near the solution, but just out of curiosity I modified julia's black color in svg. It's same svg and looks okay in both light & dark background.
![julia light dark](https://user-images.githubusercontent.com/47918989/95648777-8042e680-0af7-11eb-8f16-d96c043ba91a.png)

**Comment by ViralBShah** [comment]
The JuliaLogoGraphics repo has official logos for dark background.

https://github.com/JuliaLang/julia-logo-graphics
