### ISSUE TITLE
Link to source in the footer

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/www.julialang.org#787]
I think it would be nice to link the the source repo in the footer. It makes it easier to find it if you spot a typo or w/e.

I propose adding this in the footer instead of an "Edit on GitHub" button at the top, which is also quite common. I think a note in the footer would fit better with the rest of the layout.

**Comment by tlienart** [comment]
Should the link point to the exact page or generally to the repo? In franklindocs for instance: https://franklinjl.org/syntax/divs-commands/ the link at the top points to the specific file.

**Comment by tlienart** [comment]
#787 is now in with a floating edit button
