### ISSUE TITLE
"Talk to Us" section looks strange on wide browser windows

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#798]
![Screen Shot 2020-05-12 at 2 27 01 PM](https://user-images.githubusercontent.com/744411/81731324-c1f23700-945c-11ea-8330-07e1d028c3f7.png)

**Comment by tlienart** [comment]
Oh gosh yeah, this is an easy fix the outer div should have a max width, I’ll have a look
