### ISSUE TITLE
Community page reorg

### ISSUE THREAD

**Issue by tlienart** [JuliaLang/www.julialang.org#805]
Related to #800 

The community page is a bit of a mess, too much information and not structured  enough, here are some possible points:

* [ ] add a table of content to help navigate the page
* [ ] begin the page with clear links to "where can I find a package that does X" + key Julia org. 
* [ ] have some examples with key packages, how to do X with Y (ft packages that have > 500 stars) **note** would depend on what happens on the front page with the ecosystem rework
* [x] remove the list of meetups and only have a link to the meetup aggregator
* [ ] make the juliacon event image smaller (half the width) and add key bullet points on the side

**Comment by TeAmP0is0N** [comment]
@tlienart I would like to work on this issue. Thank you!

**Comment by TeAmP0is0N** [comment]
@tlienart @VictorelPetrovich Should I start without assigning?

**Comment by tlienart** [comment]
Yes sounds good I’ll mark you as assigned when I’m on my computer

**Comment by TeAmP0is0N** [comment]
@tlienart Is there slack or any channel to join discussions?

**Comment by tlienart** [comment]
There's Julia#website but it's probably best you discuss here. Even better would be to go about this in small chunks and open PRs for each that people can comment on, thanks!

**Comment by TeAmP0is0N** [comment]
Ok, thank you.

**Comment by ViralBShah** [comment]
The community page is now community focussed and redesigned. The ecosystem page as discussed in #800 should evolve into the package related stuff discussed in OP. I am closing this one for now.
