### ISSUE TITLE
Automatically generated sitemap

### ISSUE THREAD

**Issue by zlatanvasovic** [JuliaLang/www.julialang.org#814]
Just like the list of blog posts is automatically generated, `sitemap.xml` should be generated automatically too. It speeds up the search-engine process of indexing the blog posts and other pages from the Julia website.

**Comment by tlienart** [comment]
Yes, it’s something I need to add to Franklin, the reason why the current site map was in assets was a quick fix needed recently where I generated it with an external tool and directly submitted it to google ping

**Comment by zdroid** [comment]
Closing this issue as there's already an open issue in Franklin.

**Comment by ViralBShah** [comment]
We should only close it here when this works on this site.

**Comment by zlatanvasovic** [comment]
Closing this in order to close my own issues, but you can open a new one if it's still a problem.

**Comment by zlatanvasovic** [comment]
@fredrikekre do you even read what I wrote? :/

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/www.julialang.org/issues/814#issuecomment-660371403

**Comment by ViralBShah** [comment]
@zlatanvasovic please do not open and close issues like this. It creates a lot of noise. If it bothers you, we are happy to close this but I will request you to refrain from opening new issues.

**Comment by KristofferC** [comment]
There is discussion here that is good to have kept.

**Comment by ViralBShah** [comment]
Yes, we can link it from a new issue and even summarize it in there - but clearly @zlatanvasovic wants to close this and I would prefer not to create more noise for him.
