### ISSUE TITLE
There is no ´mastering julia 1.0´ by malcolm sherrington on packt

### ISSUE THREAD

**Issue by bjrnfrdnnd** [JuliaLang/www.julialang.org#828]
The link to this Book doesn't work. A 404 error appears.
PackT Has a book by this Author about Julia but that book is not Julia 1.0 And it was published in 2015.

**Comment by tlienart** [comment]
Would you mind opening a PR removing the link? Thanks!

**Comment by bjrnfrdnnd** [comment]
No I would not. But I do not know how to open a PR In which I am request removing the link.

**Comment by bjrnfrdnnd** [comment]
I was closing the issue but I did not want to do that.

**Comment by bjrnfrdnnd** [comment]
I was actually referring to this site: [https://julialang.org/learning/](url) but I do not know how to do a change request there (there seemingly is no github page with that content)

**Comment by logankilpatrick** [comment]
In the repo: learning/index.md

**Comment by bjrnfrdnnd** [comment]
Found it thanks.

**Comment by bjrnfrdnnd** [comment]
OK PR is done
