### ISSUE TITLE
Change download order to show 64-bit first

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#837]
We've seen people sometimes download 32-bit binaries, even on 64-bit architectures, just because it is the first thing in the table.

Put the 64-bit binaries in the first column, and 32-bit in the second will hopefully lead to more people picking the right binaries.

**Comment by zdroid** [comment]
Do you mean it for the main downloads page only, or for https://julialang.org/downloads/oldreleases/ and https://julialang.org/downloads/nightlies/ as well?

Interestingly, in [Currently supported platforms](https://julialang.org/downloads/#currently_supported_platforms) 64-bit releases are displayed first.

**Comment by ViralBShah** [comment]
I don't think we should bother with the old releases. I was thinking the main downloads page - although good to be consistent with the nightlies.

**Comment by PallHaraldsson** [comment]
For same reason should we warn people about the julia snap, it gets you 32-bit (on 6-bit platform)?

There's an unofficial julia snap that doesn't have this issue, and is up-to-date (for non-LTS, the other isn't for LTS even): https://snapcraft.io/julia-mrcinv

Should we recommend non-official?
