### ISSUE TITLE
Footer is not centered

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#842]
It should either stretch to fill the page, or be centered. Looks a bit strange right now.

![Screen Shot 2020-05-28 at 8 17 57 PM](https://user-images.githubusercontent.com/744411/83207097-5bd60700-a120-11ea-89b1-955187b4aafe.png)

**Comment by tlienart** [comment]
I'll have a look

**Comment by tlienart** [comment]
should be fixed now
