### ISSUE TITLE
Bug in blog for latest entry

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/www.julialang.org#846]
Look at:
"GSoC and JSoC 2020 Project List" and it should be obvious (I thought first it was my browser failing, with lots of tabs open). Next box is "2020-05-05", then "empty".

I believe all should be one, and if you don't see this, it's my browser or has been fixed.

**Comment by zdroid** [comment]
That must be a temporary problem with the Franklin build. I built the site locally and it shows normally.

The reason for such display is that `<p></p>` tag is missing around the content.

**Comment by tlienart** [comment]
I'll fix this, thanks for raising the issue.
