### ISSUE TITLE
Prominently show Unreasonable Effectiveness of Multiple Dispatch video 

### ISSUE THREAD

**Issue by el-oso** [JuliaLang/www.julialang.org#853]
From a discussion on Slack it was mentioned that this videos has helped to change other people's minds about Multiple Dispatch and Julia. @ViralBShah suggested that perhaps it should be displayed more prominently on the website.
[Unreasonable Effectiveness of Multiple Dispatch](https://www.youtube.com/watch?v=kc9HwsxE1OY)

Perhaps add a few examples from DifferentialEquations.jl + Measurements.jl and/or JuliaRobotics would be a nice extra.

**Comment by ViralBShah** [comment]
I think we need to put a new page on the website (and link from the first page). It basically needs to dispel the object oriented myths, discuss the expression problem, show this video, and then the examples mentioned above. 

Anyone interested in leading the charge on this?

@StefanKarpinski

**Comment by TeAmP0is0N** [comment]
@ViralBShah Yes, I am in.

**Comment by ViralBShah** [comment]
Ok, let's have the PRs!
