### ISSUE TITLE
Add Julia Hello world page

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#855]
Build out a Julia Hello world page like this: https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/intro?sdk-installed=true

**Comment by ViralBShah** [comment]
I think we should literally do a better job of showcasing JuliaAcademy content. Too many different things will lead to strange cliffs - what does someone do after that? Whereas, if we get them on to JuliaAcademy and make that experience smooth and show the courses prominently on julialang.org - people can then start with the intro course and keep going to the next one and so on.

**Comment by zdroid** [comment]
@ViralBShah That's a great idea. When I was starting out, I found JuliaAcademy the most useful learning material.

**Comment by ViralBShah** [comment]
JuliaAcademy itself could use much better theming, images and so on...

**Comment by ViralBShah** [comment]
Isn't https://julialang.org/learning/code-examples/ sufficient? Maybe we can add more examples there?

**Comment by ViralBShah** [comment]
I am going to say it is sufficient, and there's a getting started with Julia page. If anything, these existing things need to be combined and made seamless. (#967)
