### ISSUE TITLE
Post-JuliaCon Banner

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#856]
I am a fan of this banner (o something like it) for post-JuliaCon
<img width="1398" alt="Screen Shot 2020-06-08 at 3 43 17 PM" src="https://user-images.githubusercontent.com/35577566/84078666-e5969780-a99e-11ea-95aa-33464b884729.png">

**Comment by zdroid** [comment]
Do you intend it to be in the same format as the current one, or you have something different in mind?

**Comment by logankilpatrick** [comment]
The same format, just adding this as a reminder for then.

**Comment by ViralBShah** [comment]
We've done this in earlier years, and we also show the random video from JuliaCon on the front page. But it would be good to have a plan on how to drive engagement post JuliaCon with all the content that will be generated.

**Comment by ViralBShah** [comment]
We have the alert on top as well as the random JuliaCon video now.
