### ISSUE TITLE
link for zulip in community

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/www.julialang.org#870]
I know the fracturing of the chat between zulip and slack is still rather controversial, but there seems to be a good number of us over on zulip who strongly prefer it.  Any chance we can get a link to the [Julia zulip](https://julialang.zulipchat.com) in the community page?

One objection I can imagine to this is that perhaps none of the people with admin rights to the JuliaLang github org have admin rights to the zulip chat, but in that case perhaps @MasonProtter or whoever else has admin rights to the Julia zulip might like to share this?

**Comment by giordano** [comment]
Note that there is a link here: https://julialang.org/community/otherchannels/

**Comment by ExpandingMan** [comment]
Sorry, didn't even see that.  I was looking under "chat".

**Comment by ViralBShah** [comment]
We should point out that many Julia sub-communities are on Zulip, and bring that into the front page. The QQ link can go - since the Chinese website has those links already.

**Comment by aramirezreyes** [comment]
> Note that there is a link here: https://julialang.org/community/otherchannels/

It is, however, one layer below Slack, it would be cool to have it on the same layer.

**Comment by ExpandingMan** [comment]
great, thanks all!
