### ISSUE TITLE
Add Team section

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#881]
It may be nice to have a "Team" section of the site: https://www.astropy.org/team.html

**Comment by ViralBShah** [comment]
You mean for GSOC? Or the whole Julia project?

**Comment by ViralBShah** [comment]
This is a very difficult list to prepare, curate and maintain!

**Comment by zdroid** [comment]
It also may be difficult to fit in the navbar or footer. Those two already have too many items (look at other similar sites for comparision), so that may need to be worked on first.

**Comment by ViralBShah** [comment]
We can always add a page to the website by itself, without weaving it into the navigation. I'd like to make sure we do this very carefully. Not having a list is fine. But having a list where people get excluded (for whatever reason), is not good.

**Comment by fredrikekre** [comment]
IMO there is not a clear enough team structure to be displayed on such a page.

**Comment by ViralBShah** [comment]
Yes, we do not have such a team structure. One can always list all the contributors ever to github - but that has the downside of valuing code contributions above non-code contributions.

**Comment by ViralBShah** [comment]
@logankilpatrick I think it is best to close this one.

**Comment by aviks** [comment]
I agree, our structure is too wide and amorphous for this to be useful.
