### ISSUE TITLE
Syntax highlighting on blog posts

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/www.julialang.org#89]
Below is a screenshot from our blog: 
<img width="444" alt="image" src="https://user-images.githubusercontent.com/9101377/43731296-f6103586-99a5-11e8-90bd-da7d88101617.png">

It would be nice to have the Julia code syntax highlighted.

**Comment by ranjanan** [comment]
I'm on Safari on MacOS High Sierra

**Comment by ViralBShah** [comment]
Does this affect existing blog posts?
