### ISSUE TITLE
Survey page contains unrendered HTML and Julia blocks

### ISSUE THREAD

**Issue by SaschaMann** [JuliaLang/www.julialang.org#894]
https://julialang.org/blog/2019/08/2019-julia-survey/

The start of the post isn't rendered:

![grafik](https://user-images.githubusercontent.com/20866761/86544559-32cb4200-bf28-11ea-847d-a68f4aa3749c.png)

Latest Firefox on Windows 10, scripts etc are all allowed except for GA.

**Comment by ViralBShah** [comment]
I get it on chrome too. Most likely there's a simple fix.

**Comment by tlienart** [comment]
I'm on it

**Comment by tlienart** [comment]
should be fixed with #896 thanks for the heads up

closes #894 and closes #895 which is a duplicate
