### ISSUE TITLE
Add book? Introduction to Quantitative Macroeconomics Using Julia: From Basic to State-of-the-Art Computational Techniques

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/www.julialang.org#899]
It seems interesting, but it says Julia 1.0 not yet out:

https://www.amazon.com/Introduction-Quantitative-Macroeconomics-Using-State-dp-0128122196/dp/0128122196/ref=mt_other

**Comment by ViralBShah** [comment]
We should generally not recommend pre-1.0 books. They can always be added back when they are updated to 1.0.
