### ISSUE TITLE
PowerPC is incorrectly formatted in the Tiers on downloads page

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#903]
PowerPC should like the x86-64 musl entry above. It is showing up in the first two columns instead of the last two. It is unclear why this is happening. The page source looks fine to me.

![Screen Shot 2020-07-10 at 5 43 29 PM](https://user-images.githubusercontent.com/744411/87205209-ea6ba580-c2d4-11ea-87b6-a2c3394d2343.png)

**Comment by ViralBShah** [comment]
@tlienart Might you know why this is happening?

**Comment by tlienart** [comment]
I’ll have a look today, thanks for the ping, maybe @zdroid has an idea too
