### ISSUE TITLE
out-of-date info at https://julialang.org/downloads/platform/ 

### ISSUE THREAD

**Issue by keithbriggs** [JuliaLang/www.julialang.org#908]
https://julialang.org/downloads/platform/ says to do "sudo apt install julia" on Ubuntu, but this does not work ("E: Package 'julia' has no installation candidate"). You have to use snap to install the Ubuntu package, but even then you get a very old version, and it installs a 32 bit binary even on a 64 bit machine. Something is misconfigured.

The should all be updated or else deleted.

**Comment by ViralBShah** [comment]
Maybe you need to specify a version number like `julia-1.4` or something?

**Comment by keithbriggs** [comment]
No, searching for "julia" on the Ubuntu software store finds only the old 1.0.4 32-bit version, with comments and reviews from 2019.  Nobody seems to be updating the Ubuntu package.

Keith

________________________________

**Comment by giordano** [comment]
What version of Ubuntu are you talking about?  20.04 has Julia v1.4.1: https://packages.ubuntu.com/focal/julia

**Comment by keithbriggs** [comment]
Ok, mine is 18.



________________________________

**Comment by giordano** [comment]
What 18 version?  There are two releases every year.  Anyway, both releases are not supported anymore and Ubuntu never upgrades packages like this within a release

**Comment by keithbriggs** [comment]
Ubuntu 18.04.4 LTS

________________________________

**Comment by christopher-dG** [comment]
I'd like to point out one more thing that's out-of-date: there are references to `~/.juliarc.jl` and `~/.julia_history` on that page. They have been replaced with `~/.julia/config/startup.jl` and `~/.julia/logs/history`.

**Comment by zdroid** [comment]
@christopher-dG Can you open a PR to fix that?

@keithbriggs There is no package for 18.04, as you can see on https://packages.ubuntu.com/search?keywords=julia. That package is unofficial nevertheless. There even wasn't a release for 1.4.2, and it'll probably some time for 1.5.0 too.
