### ISSUE TITLE
404 on julia-1.5.0-rc2-musl-x86_64.tar.gz.asc

### ISSUE THREAD

**Issue by tianon** [JuliaLang/www.julialang.org#929]
As part of the recent v1.5.0-rc2 upload, it looks like we got `julia-1.5.0-rc2-musl-x86_64.tar.gz`, but `julia-1.5.0-rc2-musl-x86_64.tar.gz.asc` is missing (linked from https://julialang.org/downloads/#upcoming_release_vupcoming_release_upcoming_release_date).

- working: https://julialang-s3.julialang.org/bin/musl/x64/1.5/julia-1.5.0-rc2-musl-x86_64.tar.gz
- 404: https://julialang-s3.julialang.org/bin/musl/x64/1.5/julia-1.5.0-rc2-musl-x86_64.tar.gz.asc

Was this an oversight in uploading or an intentional change?
(Wanting to adjust our artifact consumption over in https://hub.docker.com/_/julia if it was intentional, but I'm guessing it wasn't. :sweat_smile: :heart:)

**Comment by ararslan** [comment]
Good catch! Fixed, and thanks!
