### ISSUE TITLE
Add back links to portable builds on Windows

### ISSUE THREAD

**Issue by musm** [JuliaLang/www.julialang.org#939]
I don't see which PR removed them, but we should add them back.

**Comment by tlienart** [comment]
hey @musm do you have a link (e.g. from wayback machine) showing what was there before that was removed? that will help bring stuff back asap, thanks!

**Comment by musm** [comment]
THey all look like this https://github.com/JuliaLang/www.julialang.org/commit/d25e90a662637fc3c74cfe0f5f2e1808b9663d0a

Just replace the .exe name with with .zip.
