### ISSUE TITLE
Revert or fix one of the recent PR to Downloads

### ISSUE THREAD

**Issue by tlienart** [JuliaLang/www.julialang.org#940]
It seems that a  bunch of things disappeared from the downloads page in a recent PR:

* windows portable links -- PR #901 but then #939 
* musm/glibc linux footnote -- PR #931 but now I can just see the footnote but not the reference to  the footnote (nor the download link with musm/glibc differentiation) 

was that on  purpose? 

cc @musm @ViralBShah @logankilpatrick

**Comment by musm** [comment]
Did someone force push? That's the only explanation I can think of.

**Comment by fredrikekre** [comment]
> Did someone force push? That's the only explanation I can think of.


No, it was merged in #937
