### ISSUE TITLE
Update website video playlist to JuliaCon 2020

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/www.julialang.org#946]
Pretty self-explanatory.

**Comment by ViralBShah** [comment]
Yeah... Must do. Urgently.

**Comment by logankilpatrick** [comment]
Will fix tonight unless I'm beat to it.

**Comment by logankilpatrick** [comment]
Sort of fixed via: 117e125... Did last year's data get generated somewhere? I don't have the bandwidth at the moment to manually copy and past 165 URL's

**Comment by ViralBShah** [comment]
Don't we have a spreadsheet with all the YouTube URLs @aviks ?

**Comment by logankilpatrick** [comment]
Ah, yes we do. Good call. 

Best, 
Logan Kilpatrick
