### ISSUE TITLE
[sugg] packages of the month

### ISSUE THREAD

**Issue by tlienart** [JuliaLang/www.julialang.org#955]
I keep discovering packages everywhere and I often wish there'd be a place where I could regularly go to check out interesting packages. Of course there's the discourse ANN and then there's juliahub, juliaobserver etc but that will give an idea of new packages or will work if you know what you're looking for. 

It might not be too hard to automatically generate a list of packages every month out of JuliaHub maybe grouping them in a few broad categories like "numerics" "data" "misc" and have 5 or so packages with a blurb in each of those, chosen at random among packages that have -- say -- at least 10 ⭐ , and have seen some activity in the last 3 months?

**Comment by ViralBShah** [comment]
I wouldn't mind have a monthly list of all new packages registered in that month, sorted by stars or some metric. If we recommend common tags for the package ecosystem for packages to use on github, then we can just use those for the grouping too.

**Comment by tlienart** [comment]
Hmm but then new users would potentially only see new packages?

**Comment by logankilpatrick** [comment]
Maybe this could be added to the JC monthly newsletter and I'll include it in our NF newsletter as well. Only thing that remains is discovering the packages.

**Comment by giordano** [comment]
I believe R has something like that, could be useful lookin how it works

**Comment by ViralBShah** [comment]
Yes, we can definitely add to the monthly newsletters. 

@aviks @pfitzseb
