### ISSUE TITLE
{{stable_release}} substitutes with patch number but patch number is not in path on MacOS

### ISSUE THREAD

**Issue by pkalikman** [JuliaLang/www.julialang.org#956]
As a result this instruction

`ln -s /Applications/Julia-1.5.0.app/Contents/Resources/julia/bin/julia /usr/local/bin/julia`

on 

https://julialang.org/downloads/platform/#macos

is incorrect--the right path is `.../Julia-1.5.app/...`, at least on my MacOS Catalina machine. 

Apologies that I don't know how to format that token or I'd submit the PR to fix myself :)

**Comment by fredrikekre** [comment]
You can probably just change `{{ stable_release }}` to `{{ stable_release_short }}` in https://github.com/JuliaLang/www.julialang.org/blob/master/downloads/platform.md.

**Comment by pkalikman** [comment]
Thanks! Will try this.
