### ISSUE TITLE
Add Details on How to become a Steward

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#962]
Hey @StefanKarpinski @ViralBShah @mbauman 

I think it would be great to publicize how to become a Discourse mod and how one becomes a Julia Language steward. 

CC @jiahao for suggesting the idea.

**Comment by logankilpatrick** [comment]
@JuliaLang/stewards bumping this. It may help to add some transparency around how the stewards are chosen, etc. Even if it's only a few sentences that say 
> "Long time Julia community members are eligible to be Stewards if the existing Steward group nominates them. There is no fixed time duration for someone to be in the community before they can become a steward, but generally the Steward role is associated with a high trust level forged over many years of contributions to the Julia community".

**Comment by ViralBShah** [comment]
Sure - I am ok with the proposed text.
