### ISSUE TITLE
Blog doesn't render on localhost

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#969]
@tlienart When I run the Franklin server locally to test, the blog doesn't work right. Only the Julia-1.5 highlights post and the Yao post can be clicked on localhost:8000. The rest all say that the page does not exist. 

But everything works fine on julialang.org.

**Comment by tlienart** [comment]
am having a look now

**Comment by ViralBShah** [comment]
I also noticed the website pulling in a bunch of stuff. I have been just doing simple PR merging for the most part. I did update to Franklin 0.9, which may be where I am seeing this. Maybe the deployment is unaffected because it is on the older version.

**Comment by tlienart** [comment]
I can reproduce; it's a bug. I'll try to fix it asap once I've figured out what's going on. thanks for reporting and apologies for the nuisance... good that the deploy is fixed on 0.8 atm

**Comment by tlienart** [comment]
Is fixed in `0.9.10`; will open and merge directly a PR that does a slight update of the scripts here.

**Comment by ViralBShah** [comment]
Should we deploy 0.9.10 to production as well?

**Comment by tlienart** [comment]
it's already done
