### ISSUE TITLE
Close to 4200 packages

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/www.julialang.org#971]
https://juliacomputing.com/

still only states over 3,500 packages. I brought it up elsewhere, but not sure where else to point it out. I would like it updated too, not just at julialang.org (and keep in sync).

I.e. with the packages waiting in queue, close to 4200. Not saying wait for that or we need to use that number. I'm ok with "over 4000", or a higher one if you want...

**Comment by fredrikekre** [comment]
Perhaps email JuliaComputing support then.

**Comment by logankilpatrick** [comment]
I would ping the folks at JC. We could also pretty easily scrape JuliaHub for this info and populate the number dynamically though I'm not sure if it's worth the effort. @StefanKarpinski perhaps you can make a Julia Computing website issues repo like this one: https://github.com/JuliaComputing/JuliaProIssues

**Comment by PallHaraldsson** [comment]
I already emailed, well through their box at juliacomputing, and pointed to this (closed) issue. I'm not trying to make (programming) work for you, I tend to make PRs here, maybe I could ping someone each time, in cases like this, where it applies? I realize julialang.org is independent, I've just seen many of the same people here.

**Comment by KristofferC** [comment]
There is no point in making issues about juliacomputing.com on this repo at least.

**Comment by logankilpatrick** [comment]
No worries @PallHaraldsson, hopefully, Stefan can make that public-facing issues repo as he did for JuliaHub and JuliaPro!

**Comment by StefanKarpinski** [comment]
Just email <info@juliacomputing.com> if you have suggestions. Note that I created the JuliaProIssues repo and there haven't been any issues filed so far. I don't think it makes sense to have issues repos for everything that someone might want to give feedback about, especially things that aren't applications.
