### ISSUE TITLE
provide some compatible links to old assets?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/www.julialang.org#993]
I realize this repo changed some of its asset names recently, which as a result breaks a bunch of README, doc images, e.g https://github.com/JuliaLang/julia/blob/master/doc/build/README.md the Julia logo is not there anymore. Thus I'm wondering if we could consider

1. create a tag in the future? so some of the links won't be broken.
2. make some of the assets link more stable? or consider move all Julia logo etc. assets to a separate repo so the links won't change.

**Comment by logankilpatrick** [comment]
There already is a separate repo for the Julia Logos and we should most definitely link there rather than here IMO.

**Comment by giordano** [comment]
> e.g https://github.com/JuliaLang/julia/blob/master/doc/build/README.md the Julia logo is not there anymore.

It doesn't use an image from this repository anymore: https://github.com/JuliaLang/julia/pull/37627

**Comment by Roger-luo** [comment]
Should this website also uses julia-logo-graphics as well then?

**Comment by ViralBShah** [comment]
Yes, I think so.
