### ISSUE TITLE
JuliaOpt is dead, should provide link to different project

### ISSUE THREAD

**Issue by asmarcz** [JuliaLang/www.julialang.org#995]
Ecosystem -> Scientific Domains

**Comment by ViralBShah** [comment]
The website is still live and in process of migration to http://jump.dev

**Comment by asmarcz** [comment]
Well, I just wanted to report this as it doesn't put a good impression on someone - like me - who is learning about Julia for the first time. I cannot really resolve the context.

**Comment by ViralBShah** [comment]
@logankilpatrick Is this something you can update?

**Comment by logankilpatrick** [comment]
Fixed, thanks for reporting! 

Best, 
Logan Kilpatrick
