### ISSUE TITLE
"teaching julia at mit" link at the very top of the julialang.org is broken again

### ISSUE THREAD

**Issue by PROinALL** [JuliaLang/www.julialang.org#999]
wrong link (current): https://computationalthinking.mit.edu/fall20/
right link (needed): https://computationalthinking.mit.edu/Fall20/

**Comment by logankilpatrick** [comment]
It's working right now, thanks for reporting.

**Comment by ViralBShah** [comment]
Damn it - it changed twice. @shashi why does this URL keep changing?

**Comment by shashi** [comment]
It did not change twice, it was wrong here.

**Comment by ViralBShah** [comment]
It certainly did. I personally saw the 404 and changed Fall20 to fall20 and then it had to be changed back.

**Comment by shashi** [comment]
https://github.com/mitmath/18S191/commit/c1a6867f864e4a31624c01e396db70259526148b --> https://github.com/mitmath/18S191/commit/c4f3fdbb68251d3bdb5706557031c49976ba93f0

 ^--- it wasn't me. :man_shrugging:

**Comment by ViralBShah** [comment]
That's cool - but people notice it in minutes and file issues.
